#define X_NOSCOPE scope = 0; \
scopeCurator = 0;

class RDS_T72_AAF_04;
class RDS_BMP2_AAF_01;
class RDS_BMP2_HQ_AAF_01;
class RDS_BMP2_Ambul_01;
class RDS_ZSU_AAF_04;
class CDF_A3_BRDM2_Base;
class CDF_A3_BRDM2_ATGM_Base;
class CDF_A3_BRDM2_HQ_Base;

class CDF_A3_T72: RDS_T72_AAF_04 { X_NOSCOPE };
class CDF_A3_BMP2: RDS_BMP2_AAF_01 { X_NOSCOPE };
class CDF_A3_BMP2_HQ: RDS_BMP2_HQ_AAF_01 { X_NOSCOPE };
class CDF_A3_BMP2_Ambul: RDS_BMP2_Ambul_01 { X_NOSCOPE };
class CDF_A3_ZSU: RDS_ZSU_AAF_04 { X_NOSCOPE };
class CDF_A3_BRDM2: CDF_A3_BRDM2_Base { X_NOSCOPE };
class CDF_A3_BRDM2_ATGM: CDF_A3_BRDM2_ATGM_Base { X_NOSCOPE };
class CDF_A3_BRDM2_HQ: CDF_A3_BRDM2_HQ_Base { X_NOSCOPE };