class I_mas_BMP1_base: Tank_F { X_SCOPE(0) };
class I_mas_BMP1_AAF_base: I_mas_BMP1_base {};
class I_mas_BMP1_AAF_01: I_mas_BMP1_AAF_base { X_SCOPE(0) };
class O_mas_BMP1_OPF_01: I_mas_BMP1_AAF_01 { X_SCOPE(0) };
class I_mas_BMP1P_AAF_base: I_mas_BMP1_base {};
class I_mas_BMP1P_AAF_01: I_mas_BMP1P_AAF_base { X_SCOPE(0) };
class O_mas_BMP1P_OPF_01: I_mas_BMP1P_AAF_01 { X_SCOPE(0) };
class I_mas_BMP2_base: I_mas_BMP1_base {};
class I_mas_BMP2_AAF_base: I_mas_BMP2_base {};
class I_mas_BMP2_AAF_01: I_mas_BMP2_AAF_base { X_SCOPE(0) };
class O_mas_BMP2_OPF_01: I_mas_BMP2_AAF_01 { X_SCOPE(0) };
class I_mas_BMP2_HQ_Base: I_mas_BMP2_base {};
class I_mas_BMP2_HQ_AAF_base: I_mas_BMP2_HQ_Base {};
class I_mas_BMP2_HQ_AAF_01: I_mas_BMP2_HQ_AAF_base { X_SCOPE(0) };
class O_mas_BMP2_HQ_OPF_01: I_mas_BMP2_HQ_AAF_01 { X_SCOPE(0) };
class I_mas_BMP2_Ambul_Base: I_mas_BMP2_base {};
class I_mas_BMP2_Ambul_AAF_base: I_mas_BMP2_Ambul_Base {};
class I_mas_BMP2_Ambul_01: I_mas_BMP2_Ambul_AAF_base { X_SCOPE(0) };
class O_mas_BMP2_Ambul_01: I_mas_BMP2_Ambul_01 { X_SCOPE(0) };