class I_mas_ZU23_AAF;
class I_mas_DSHKM_AAF;
class I_mas_DSHkM_Mini_TriPod;
class I_mas_AGS_AAF;
class I_mas_Metis_AAF;
class I_mas_SPG9_AAF;
class I_mas_Stinger_AA_pod_AAF;
class I_mas_2b14_82mm_AAF;

class B_mas_ZU23_FIA: I_mas_ZU23_AAF { X_SCOPE(0) };
class B_mas_DSHKM_FIA: I_mas_DSHKM_AAF { X_SCOPE(0) };
class B_mas_DSHkM_Mini_TriPod_FIA: I_mas_DSHkM_Mini_TriPod { X_SCOPE(0) };
class B_mas_M2StaticMG_FIA: I_mas_M2StaticMG_AAF { X_SCOPE(0) };
class B_mas_M2StaticMG_MiniTripod_FIA: I_mas_M2StaticMG_MiniTripod_AAF { X_SCOPE(0) };
class B_mas_AGS_FIA: I_mas_AGS_AAF { X_SCOPE(0) };
class B_mas_Metis_FIA: I_mas_Metis_AAF { X_SCOPE(0) };
class B_mas_SPG9_AAF: I_mas_SPG9_AAF { X_SCOPE(0) };
class B_mas_Stinger_AA_pod_FIA: I_mas_Stinger_AA_pod_AAF { X_SCOPE(0) };
class B_mas_2b14_82mm_FIA: I_mas_2b14_82mm_AAF { X_SCOPE(0) };
class B_mas_D30_FIA: I_mas_D30_AAF { X_SCOPE(0) };
class B_mas_D30_AT_FIA: I_mas_D30_AT_AAF { X_SCOPE(0) };