// config.bin - 14:48:16 02/19/15, generated in 0.03 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class cdf_a3_main_c {
		units[] = {"B_CDF_A3_Soldier", "B_CDF_A3_Soldier_Light", "B_CDF_A3_Soldier_GL", "B_CDF_A3_Soldier_Militia", "B_CDF_A3_Soldier_Medic", "B_CDF_A3_Soldier_Sniper", "B_CDF_A3_Soldier_Spotter", "B_CDF_A3_Soldier_Marksman", "B_CDF_A3_Soldier_RPG", "B_CDF_A3_Soldier_Strela", "B_CDF_A3_Soldier_AR", "B_CDF_A3_Soldier_MG", "B_CDF_A3_Soldier_TL", "B_CDF_A3_Soldier_Officer", "B_CDF_A3_Commander", "B_CDF_A3_Soldier_Pilot", "B_CDF_A3_Soldier_Crew", "B_CDF_A3_Soldier_Engineer", "CDF_A3_Mi_24v", "CDF_A3_Mi_24p", "CDF_A3_Mi17", "CDF_A3_Mi17_rockets", "CDF_A3_Mi17_medevac", CDF_A3_UAZ_469, "CDF_A3_UAZ_469_Open", "CDF_A3_Su25SM", CDF_A3_T72, CDF_A3_BMP2, CDF_A3_BMP2_HQ, "CDF_A3_BMP2_Ambul", CDF_A3_ZSU, "CDF_A3_Ural", "CDF_A3_Ural_Open", "CDF_A3_Ural_Fuel", CDF_A3_BM21, CDF_A3_ZU23, CDF_A3_DSHKM, "CDF_A3_DSHkM_Mini_TriPod", CDF_A3_AGS, CDF_A3_SPG9, "CDF_A3_2b14_82mm", CDF_A3_D30, CDF_A3_BRDM2, CDF_A3_BRDM2_ATGM, CDF_A3_UAZ_MG, CDF_A3_UAZ_AGS30, CDF_A3_UAZ_SPG9, "CDF_A3_Ural_Repair", "CDF_A3_Ural_Reammo", "CDF_A3_Ural_ZU23", CDF_A3_BMD2, CDF_A3_BTR70, "B_CDF_A3_Soldier_Base", "B_CDF_A3_Backpack", "CDF_A3_Ural_Empty", CDF_A3_BRDM2_HQ};
		weapons[] = {"V_CDF_A3_6b23", "V_CDF_A3_6b23_rifleman_01", "V_CDF_A3_6b23_rifleman_02", "V_CDF_A3_6b23_crewofficer", "V_CDF_A3_6b23_crew", "V_CDF_A3_6b23_engineer", "V_CDF_A3_6b23_medic", "U_CDF_A3_uniform_ttsko"};
		requiredVersion = 0.1;
		requiredAddons[] = {"rhs_c_troops", "RHS_A2_AirImport", "RDS_Tanks", RDS_APC, "cdf_a3_vehicles"};
	};
};

class cfgFactionClasses {
	class CDF_A3 {
		displayName = CDF;
		priority = 1;
		side = 1;
		genericNames = "CzechMen";
		identityTypes[] = {"LanguageCDF", "Language_ACR_CZ", "Head_Euro"};
		flag = "cdf_a3\cdf_a3_main\data\flag_cdf_co.paa";
		icon = "cdf_a3\cdf_a3_main\data\icon_cdf_co.paa";
	};
};
class DefaultEventhandlers;	// External class reference

class CfgVehicles {
	class rhs_infantry_msv_base;	// External class reference
	
	class B_CDF_A3_Soldier_Base : rhs_infantry_msv_base {
		author = CDF_A3;
		identityTypes[] = {"Head_Euro", "Language_CZ", "Language_ACR_CZ"};
		faceType = "Man_A3";
		side = 1;
		faction = CDF_A3;
		genericNames = "CzechMen";
		vehicleClass = "Men";
		portrait = "";
		picture = "";
		icon = "iconMan";
		accuracy = 2.3;
		sensitivity = 3;
		threat[] = {1, 0.1, 0.1};
		camouflage = 1.4;
		minFireTime = 7;
		scope = 1;
		scopeCurator = 0;
		cost = 40000;
		canCarryBackPack = 1;
		modelSides[] = {1, 3};
		nakedUniform = "U_BasicBody";
		uniformClass = "U_CDF_A3_uniform_ttsko";
		weapons[] = {"hlc_rifle_ak74", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "HandGrenade"};
		respawnWeapons[] = {"hlc_rifle_ak74", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade"};
		Items[] = {"FirstAidKit"};
		RespawnItems[] = {"FirstAidKit"};
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_rifleman_01", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_rifleman_01", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		hiddenSelections[] = {"camo1", "camo2", "camob", "insignia"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\CDF_uniform.paa", "", ""};
		armor = 2;
		armorStructural = 5;
	};
	class Bag_Base;	// External class reference
	
	class B_CDF_A3_Backpack : Bag_Base {
		author = CDF_A3;
		scope = 2;
		displayName = "Small Bag [CDF]";
		descriptionShort = "Bag [CDF]";
		picture = "\cdf_a3\cdf_a3_main\data\UI\icon_pack.paa";
		model = "\cdf_a3\cdf_a3_main\cdf_backpack.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\cdf_a3\cdf_a3_main\data\equip_co.paa"};
		maximumLoad = 100;
		mass = 10;
	};
	
	class B_CDF_A3_Soldier : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_A3_CfgVehicles_B_Soldier_F0";
		backpack = "B_CDF_A3_Backpack";
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_rifleman_02", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_rifleman_02", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Light : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_Soldier_lite_F0";
		weapons[] = {"Throw", "Put"};
		magazines[] = {};
		respawnWeapons[] = {"Throw", "Put"};
		respawnMagazines[] = {};
		camouflage = 1.2;
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_GL : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_Soldier_GL_F0";
		cost = 50000;
		backpack = "B_CDF_A3_Backpack";
		weapons[] = {"hlc_rifle_aks74_GL", "Throw", "Put"};
		threat[] = {1, 0.3, 0.1};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK"};
		respawnWeapons[] = {"hlc_rifle_aks74_GL", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK", "hlc_VOG25_AK"};
	};
	
	class B_CDF_A3_Soldier_Militia : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = $STR_DN_CDF_A3_SOLDIER_MILITIA;
		weapons[] = {"hlc_rifle_akm", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "HandGrenade", "HandGrenade"};
		respawnWeapons[] = {"hlc_rifle_akm", "Throw", "Put"};
		respawnmagazines[] = {"hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "hlc_30Rnd_762x39_b_ak", "HandGrenade"};
		linkedItems[] = {"H_CDF_A3_fieldcap", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_fieldcap", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Medic : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_medic_s"};
				speechPlural[] = {"veh_infantry_medic_p"};
			};
		};
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_medic_F0";
		picture = "pictureHeal";
		textSingular = "medic";
		textPlural = "medics";
		attendant = 1;
		camouflage = 1.6;
		sensitivity = 2.5;
		cost = 60000;
		backpack = "rhs_assault_umbts_medic";
		weapons[] = {"hlc_rifle_aks74u", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "SmokeShellOrange"};
		respawnWeapons[] = {"hlc_rifle_aks74u", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "SmokeShellOrange"};
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_medic", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_medic", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		icon = "iconManMedic";
	};
	
	class B_CDF_A3_Soldier_Sniper : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		displayName = "$STR_B_sniper_F0";
		scope = 2;
		scopeCurator = 2;
		threat[] = {1, 0.3, 0.3};
		camouflage = 0.6;
		sensitivity = 3.5;
		cost = 250000;
		model = "\A3\characters_f\Common\ghillie.p3d";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\cdf_a3\cdf_a3_main\data\ghillie.paa"};
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_sniper_s"};
				speechPlural[] = {"veh_infantry_sniper_p"};
			};
		};
		textSingular = "sniper";
		textPlural = "snipers";
		uniformClass = "U_CDF_A3_SniperGhillie";
		weapons[] = {"rhs_weap_svdp_wd", "NVGoggles", "Throw", "Put", "Binocular"};
		magazines[] = {"rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShellOrange"};
		respawnWeapons[] = {"rhs_weap_svdp_wd", "NVGoggles", "", "Throw", "Put", "Binocular"};
		respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "rhs_10Rnd_762x54mmR_7N1", "HandGrenade", "SmokeShellOrange"};
		linkedItems[] = {"V_CDF_A3_6b23_rifleman_01", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_CDF_A3_6b23_rifleman_01", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Spotter : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_SF_s"};
				speechPlural[] = {"veh_infantry_SF_p"};
			};
		};
		displayName = "$STR_B_spotter_F0";
		scope = 2;
		scopeCurator = 2;
		threat[] = {1, 0.3, 0.3};
		camouflage = 0.6;
		sensitivity = 3.5;
		cost = 150000;
		model = "\A3\characters_f\Common\ghillie.p3d";
		hiddenSelections[] = {"Camo"};
		hiddenSelectionsTextures[] = {"\cdf_a3\cdf_a3_main\data\ghillie.paa"};
		textSingular = "sniper";
		textPlural = "snipers";
		uniformClass = "U_CDF_A3_SniperGhillie";
		weapons[] = {"hlc_rifle_aks74u", "Binocular", "NVGoggles", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "HandGrenade", "SmokeShellOrange", "SmokeShell"};
		respawnWeapons[] = {"hlc_rifle_aks74u", "Binocular", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "SmokeShell"};
		linkedItems[] = {"V_CDF_A3_6b23_rifleman_01", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"V_CDF_A3_6b23_rifleman_01", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Marksman : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_soldier_M_F0";
		sensitivity = 3.3;
		cost = 200000;
		backpack = "B_CDF_A3_Backpack";
		weapons[] = {"hlc_rifle_aks74", "Binocular", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "HandGrenade", "SmokeShellOrange", "SmokeShell"};
		respawnWeapons[] = {"hlc_rifle_aks74", "Binocular", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "SmokeShell"};
	};
	
	class B_CDF_A3_Soldier_RPG : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_AT_s"};
				speechPlural[] = {"veh_infantry_AT_p"};
			};
		};
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_soldier_AT_F0";
		cost = 120000;
		threat[] = {1, 1, 0.8};
		camouflage = 1.5;
		textSingular = "launcherSoldier";
		textPlural = "launcherSoldiers";
		backpack = "rhs_rpg";
		weapons[] = {"hlc_rifle_ak74", "rhs_weap_rpg7", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "rhs_rpg7_PG7VL_mag", "rhs_rpg7_PG7VL_mag", "rhs_rpg7_PG7VL_mag"};
		respawnWeapons[] = {"hlc_rifle_ak74", "rhs_weap_rpg7", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "rhs_rpg7_PG7VL_mag", "rhs_rpg7_PG7VL_mag"};
		icon = "iconManAT";
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Strela : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_AT_s"};
				speechPlural[] = {"veh_infantry_AT_p"};
			};
		};
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_soldier_AA_F0";
		textSingular = "launcherSoldier";
		textPlural = "launcherSoldiers";
		threat[] = {1, 1, 0.8};
		camouflage = 1.5;
		cost = 100000;
		backpack = "";
		weapons[] = {"hlc_rifle_ak74", "rhs_weap_igla", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "rhs_mag_9k38_rocket"};
		respawnWeapons[] = {"hlc_rifle_ak74", "rhs_weap_igla", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "rhs_mag_9k38_rocket"};
		icon = "iconManAT";
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		
		class eventHandlers {
			init = "_unit = _this select 0;_unit addBackpack 'B_CDF_A3_Backpack';_unit addMagazines ['rhs_mag_9k38_rocket',1];";
		};
	};
	
	class B_CDF_A3_Soldier_AR : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_MG_s"};
				speechPlural[] = {"veh_infantry_MG_p"};
			};
		};
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_soldier_AR_F0";
		textSingular = "mgunner";
		textPlural = "mgunners";
		threat[] = {1, 0.1, 0.3};
		cost = 80000;
		backpack = "B_CDF_A3_Backpack";
		weapons[] = {"hlc_rifle_rpk", "Throw", "Put"};
		magazines[] = {"hlc_75rnd_762x39_m_rpk", "hlc_75rnd_762x39_m_rpk", "hlc_75rnd_762x39_m_rpk", "hlc_75rnd_762x39_m_rpk", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShell"};
		respawnWeapons[] = {"hlc_rifle_rpk", "Throw", "Put"};
		respawnMagazines[] = {"hlc_75rnd_762x39_m_rpk", "hlc_75rnd_762x39_m_rpk", "hlc_75rnd_762x39_m_rpk", "HandGrenade", "SmokeShell"};
		icon = "iconManMG";
	};
	
	class B_CDF_A3_Soldier_MG : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		cost = 90000;
		accuracy = 3.7;
		textSingular = "mgunner";
		textPlural = "mgunners";
		displayName = "$STR_B_soldier_AR_F0";
		backpack = "rhs_sidorMG";
		weapons[] = {"CUP_lmg_PKM", "Throw", "Put"};
		magazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M", "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M", "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M", "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M", "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};
		threat[] = {1, 0.1, 0.8};
		respawnWeapons[] = {"CUP_lmg_PKM", "Throw", "Put"};
		respawnMagazines[] = {"CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M", "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M", "CUP_100Rnd_TE4_LRT4_762x54_PK_Tracer_Green_M"};
		icon = "iconManMG";
	};
	
	class B_CDF_A3_Soldier_TL : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_Soldier_TL_F0";
		textSingular = "officer";
		textPlural = "officers";
		camouflage = 1.4;
		sensitivity = 3.3;
		cost = 350000;
		backpack = "rhs_sidor";
		weapons[] = {"hlc_rifle_aks74", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "HandGrenade", "SmokeShell", "SmokeShell", "SmokeShellOrange", "SmokeShellBlue"};
		respawnWeapons[] = {"hlc_rifle_aks74", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "SmokeShell", "SmokeShellOrange", "SmokeShellBlue"};
		icon = "iconManLeader";
		linkedItems[] = {"H_CDF_A3_fieldcap", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_fieldcap", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Officer : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_officer_s"};
				speechPlural[] = {"veh_infantry_officer_p"};
			};
		};
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_officer_F0";
		textSingular = "officer";
		textPlural = "officers";
		identityTypes[] = {"Head_Euro", "Language_CZ", "Language_ACR_CZ"};
		camouflage = 1.6;
		sensitivity = 3;
		cost = 700000;
		weapons[] = {"hlc_rifle_aks74u", "CUP_hgun_Makarov", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M"};
		respawnWeapons[] = {"hlc_rifle_aks74u", "CUP_hgun_Makarov", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put"};
		respawnmagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M"};
		icon = "iconManOfficer";
		linkedItems[] = {"H_CDF_A3_fieldcap", "V_CDF_A3_6b23_crewofficer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_fieldcap", "V_CDF_A3_6b23_crewofficer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Commander : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = $STR_DN_GENERAL_CDF_A3;
		identityTypes[] = {"Head_Euro", "Language_CZ", "Language_ACR_CZ"};
		textSingular = "officer";
		textPlural = "officers";
		camouflage = 1.6;
		sensitivity = 3;
		cost = 900000;
		weapons[] = {"hlc_rifle_aks74u", "CUP_hgun_Makarov", "NVGoggles", "ItemGPS", "Binocular", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M"};
		respawnWeapons[] = {"hlc_rifle_aks74u", "CUP_hgun_Makarov", "NVGoggles", "ItemGPS", "Binocular", "Throw", "Put"};
		respawnmagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "CUP_8Rnd_9x18_Makarov_M", "CUP_8Rnd_9x18_Makarov_M"};
		icon = "iconManOfficer";
		linkedItems[] = {"H_CDF_A3_fieldcap", "rhs_vest_commander", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_fieldcap", "rhs_vest_commander", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Pilot : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		
		class SpeechVariants {
			class Default {
				speechSingular[] = {"veh_infantry_pilot_s"};
				speechPlural[] = {"veh_infantry_pilot_p"};
			};
		};
		cost = 20000;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_Pilot_F0";
		textSingular = "pilot";
		textPlural = "pilots";
		weapons[] = {"hlc_rifle_aks74u", "NVGoggles", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "SmokeShellOrange", "SmokeShellBlue"};
		respawnWeapons[] = {"hlc_rifle_aks74u", "NVGoggles", "Throw", "Put"};
		respawnmagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "SmokeShellOrange", "SmokeShellBlue"};
		linkedItems[] = {"rhs_zsh7a_mike", "rhs_6sh46", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"rhs_zsh7a_mike", "rhs_6sh46", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Crew : B_CDF_A3_Soldier_Base {
		author = CDF_A3;
		camouflage = 1.6;
		sensitivity = 2.5;
		cost = 20000;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_crew_F0";
		weapons[] = {"hlc_rifle_aks74u", "NVGoggles", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "HandGrenade"};
		respawnWeapons[] = {"hlc_rifle_aks74u", "NVGoggles", "Throw", "Put"};
		respawnmagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade"};
		textSingular = "crew";
		textPlural = "crews";
		linkedItems[] = {"rhs_tsh4", "V_CDF_A3_6b23_crew", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"rhs_tsh4", "V_CDF_A3_6b23_crew", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class B_CDF_A3_Soldier_Engineer : B_CDF_A3_Soldier {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		displayName = "$STR_B_engineer_F0";
		camouflage = 1.6;
		sensitivity = 2.5;
		cost = 60000;
		detectSkill = 60;
		threat[] = {1, 0.5, 0.1};
		canDeactivateMines = 1;
		engineer = 1;
		backpack = "rhs_assault_umbts_engineer";
		weapons[] = {"hlc_rifle_ak74", "Throw", "Put"};
		magazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade", "HandGrenade"};
		respawnWeapons[] = {"hlc_rifle_ak74", "Throw", "Put"};
		respawnMagazines[] = {"hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "hlc_30Rnd_545x39_B_AK", "HandGrenade"};
		icon = "iconManEngineer";
		picture = "pictureRepair";
		linkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnLinkedItems[] = {"H_CDF_A3_HelmetIA", "V_CDF_A3_6b23_engineer", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	class RHS_Mi24_base;	// External class reference
	class RHS_Mi24V_base;	// External class reference
	
	class CDF_A3_Mi_24v : RHS_Mi24V_base {
		accuracy = 0.5;
		author = CDF_A3;
		displayName = "Mi-24V";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Pilot";
		typicalCargo[] = {"B_CDF_A3_Soldier_Pilot"};
		faction = CDF_A3;
		vehicleclass = "Air";
		hiddenSelections[] = {"camo1", "camo2", "n1", "n2", "exhaust", "tail_decals"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\mi35_001_blu_co.paa", "cdf_a3\cdf_a3_main\data\mi35_002_co.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_a2port_air\Mi17\data\camo\mi8_det_g_camo1_co.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa"};
	};
	
	class CDF_A3_Mi_24p : RHS_Mi24_base {
		accuracy = 0.5;
		author = CDF_A3;
		displayName = "Mi-24P";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Pilot";
		typicalCargo[] = {"B_CDF_A3_Soldier_Pilot"};
		faction = CDF_A3;
		vehicleclass = "Air";
		hiddenSelections[] = {"camo1", "camo2", "n1", "n2", "exhaust", "tail_decals"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\mi35_001_blu_co.paa", "cdf_a3\cdf_a3_main\data\mi35_002_co.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_a2port_air\Mi17\data\camo\mi8_det_g_camo1_co.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa"};
	};
	class RHS_Mi8AMT_base;	// External class reference
	class RHS_Mi8AMTSh_base;	// External class reference
	class RHS_Mi8_base;	// External class reference
	
	class CDF_A3_Mi17 : RHS_Mi8_base {
		author = CDF_A3;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Pilot";
		typicalCargo[] = {"B_CDF_A3_Soldier_Pilot"};
		scope = 2;
		scopeCurator = 2;
		displayName = "Mi-17";
		side = 1;
		vehicleclass = "Air";
		hiddenSelections[] = {"Camo1", "Camo2", "Camo3", "Camo4", "n1", "n2", "tail_decals"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\mi8_body_g_cdf_co.paa", "\rhsafrf\addons\rhs_a2port_air\Mi17\data\camo\mi8_det_g_camo1_co.paa", "a3\data_f\clear_empty.paa", "rhsafrf\addons\rhs_a2port_air\mi17\data\mi8_decals_ca.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa"};
	};
	
	class CDF_A3_Mi17_rockets : RHS_Mi8AMTSh_base {
		scope = 2;
		scopeCurator = 2;
		displayName = "Mi-17 (Rockets)";
		author = CDF_A3;
		crew = "B_CDF_A3_Soldier_Pilot";
		typicalCargo[] = {"B_CDF_A3_Soldier_Pilot"};
		faction = CDF_A3;
		side = 1;
		vehicleclass = "Air";
		hiddenSelections[] = {"Camo1", "Camo2", "Camo3", "Camo4", "n1", "n2", "tail_decals"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\mi8_body_g_cdf_co.paa", "\rhsafrf\addons\rhs_a2port_air\Mi17\data\camo\mi8_det_g_camo1_co.paa", "a3\data_f\clear_empty.paa", "rhsafrf\addons\rhs_a2port_air\mi17\data\mi8_decals_ca.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa"};
	};
	
	class CDF_A3_Mi17_medevac : RHS_Mi8AMT_base {
		scope = 2;
		scopeCurator = 2;
		displayName = "Mi-17 (Medevac)";
		author = CDF_A3;
		crew = "B_CDF_A3_Soldier_Pilot";
		typicalCargo[] = {"B_CDF_A3_Soldier_Pilot"};
		faction = CDF_A3;
		side = 1;
		vehicleClass = "Support";
		hiddenSelections[] = {"Camo1", "Camo2", "Camo3", "Camo4", "n1", "n2", "tail_decals"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\mi8_body_g_cdf_co.paa", "\rhsafrf\addons\rhs_a2port_air\Mi17\data\camo\mi8_det_g_camo2_co.paa", "a3\data_f\clear_empty.paa", "rhsafrf\addons\rhs_a2port_air\mi17\data\mi8_decals_ca.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa"};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 30;
			};
			
			class _xx_Medikit {
				name = "Medikit";
				count = 15;
			};
		};
	};
	class RHS_Su25SM_vvs;	// External class reference
	
	class CDF_A3_Su25SM : RHS_Su25SM_vvs {
		faction = CDF_A3;
		author = CDF_A3;
		crew = "B_CDF_A3_Soldier_Pilot";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		displayName = "$STR_RHS_SU25SM_Name";
		vehicleclass = "Air";
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\su25_body1_cdf_co.paa", "cdf_a3\cdf_a3_main\data\su25_body2_cdf_co.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa"};
	};
	class LandVehicle;	// External class reference
	
	class Car : LandVehicle {
		class HitPoints;	// External class reference
		class NewTurret;	// External class reference
	};
	
	class Car_F : Car {
		class Turrets {
			class MainTurret : NewTurret {
				disableSoundAttenuation = 1;
				class ViewOptics;	// External class reference
			};
		};
		
		class HitPoints {
			class HitLFWheel;	// External class reference
			class HitLF2Wheel;	// External class reference
			class HitRFWheel;	// External class reference
			class HitRF2Wheel;	// External class reference
			class HitBody;	// External class reference
			class HitGlass1;	// External class reference
			class HitGlass2;	// External class reference
			class HitGlass3;	// External class reference
			class HitGlass4;	// External class reference
			class HitGlass5;	// External class reference
			class HitGlass6;	// External class reference
		};
		class EventHandlers;	// External class reference
		class AnimationSources;	// External class reference
	};
	
	class Offroad_01_base_F : Car_F {};
	
	class Truck_F : Car_F {};
	
	class RHS_UAZ_Base : Offroad_01_base_F {};
	
	class rhs_uaz_open_Base : RHS_UAZ_Base {};
	
	class CDF_A3_UAZ_469 : RHS_UAZ_Base {
		accuracy = 0.5;
		author = CDF_A3;
		vehicleClass = "Car";
		displayName = UAZ;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		faction = CDF_A3;
		hiddenSelections[] = {"camo1", "camog1", "camog2", "n1", "n2", "n3", "n4", "i1", "i2", "i3", "i4"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\uaz_main_CDF_old_co.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa"};
		
		class EventHandlers : EventHandlers {
			init = "_this call SLX_XEH_EH_Init;_this call compile preProcessFile '\cdf_a3\cdf_a3_main_c\scripts\rhs_decal_init.sqf'";
		};
	};
	
	class CDF_A3_UAZ_469_Open : rhs_uaz_open_Base {
		accuracy = 0.5;
		author = CDF_A3;
		vehicleClass = "Car";
		displayName = "UAZ (Open)";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		faction = CDF_A3;
		hiddenSelections[] = {"camo1", "camog1", "camog2", "n1", "n2", "n3", "n4", "i1", "i2", "i3", "i4"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\uaz_main_CDF_old_co.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa", "a3\data_f\clear_empty.paa"};
		
		class EventHandlers : EventHandlers {
			init = "_this call SLX_XEH_EH_Init;_this call compile preProcessFile '\cdf_a3\cdf_a3_main_c\scripts\rhs_decal_init.sqf'";
		};
	};
	
	class CDF_A3_UAZ_Base : RHS_UAZ_Base {};
	
	class CDF_A3_UAZ_MG_Base : CDF_A3_UAZ_Base {};
	
	class CDF_A3_UAZ_MG : CDF_A3_UAZ_MG_Base {
		author = CDF_A3;
		vehicleClass = "Car";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		faction = CDF_A3;
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\uaz_main_CDF_old_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	
	class CDF_A3_UAZ_AGS30_Base : CDF_A3_UAZ_Base {};
	
	class CDF_A3_UAZ_AGS30 : CDF_A3_UAZ_AGS30_Base {
		author = CDF_A3;
		vehicleClass = "Car";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		faction = CDF_A3;
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\uaz_main_CDF_old_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	
	class CDF_A3_UAZ_SPG9_Base : CDF_A3_UAZ_Base {};
	
	class CDF_A3_UAZ_SPG9 : CDF_A3_UAZ_SPG9_Base {
		author = CDF_A3;
		vehicleClass = "Car";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		faction = CDF_A3;
		hiddenSelections[] = {"camo1"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\uaz_main_CDF_old_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	
	class RHS_Ural_BaseTurret : Truck_F {};
	
	class RHS_Ural_Base : RHS_Ural_BaseTurret {};
	
	class RHS_Ural_MSV_Base : RHS_Ural_Base {};
	
	class CDF_A3_Ural : RHS_Ural_MSV_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		vehicleClass = "Car";
		displayName = "Ural";
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2", "n1", "n2", "n3", "n4", "i1", "i2", "i3", "i4"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_plachta_camo_co.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa"};
		
		class EventHandlers : EventHandlers {
			init = "_this call SLX_XEH_EH_Init;_this call compile preProcessFile '\cdf_a3\cdf_a3_main_c\scripts\rhs_decal_init.sqf'";
		};
	};
	
	class RHS_Ural_Open_MSV_01 : RHS_Ural_MSV_Base {};
	
	class CDF_A3_Ural_Open : RHS_Ural_Open_MSV_01 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		vehicleClass = "Car";
		displayName = "Ural (Open)";
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2", "n1", "n2", "n3", "n4", "i1", "i2", "i3", "i4"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_open_cdf_co.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa"};
		
		class EventHandlers : EventHandlers {
			init = "_this call SLX_XEH_EH_Init;_this call compile preProcessFile '\cdf_a3\cdf_a3_main_c\scripts\rhs_decal_init.sqf'";
		};
	};
	
	class RHS_Ural_Support_MSV_Base_01 : RHS_Ural_MSV_Base {};
	
	class RHS_Ural_Fuel_MSV_01 : RHS_Ural_Support_MSV_Base_01 {};
	
	class CDF_A3_Ural_Fuel : RHS_Ural_Fuel_MSV_01 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		vehicleClass = "Support";
		displayName = "Ural (Fuel)";
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2", "camo3", "n1", "n2", "n3", "n4", "i1", "i2", "i3", "i4"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_open_cdf_co.paa", "cdf_a3\cdf_a3_main\data\ural_fuel_cdf_co.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa"};
		
		class EventHandlers : EventHandlers {
			init = "_this call SLX_XEH_EH_Init;_this call compile preProcessFile '\cdf_a3\cdf_a3_main_c\scripts\rhs_decal_init.sqf'";
		};
	};
	
	class RHS_BM21_MSV_01 : RHS_Ural_BaseTurret {};
	
	class CDF_A3_BM21 : RHS_BM21_MSV_01 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		vehicleClass = "Car";
		displayName = "BM-21 Grad";
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2", "camog1", "camog2", "n1", "n2", "n3", "n4", "i1", "i2", "i3", "i4"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_bm21_cdf_co.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa"};
		
		class EventHandlers : EventHandlers {
			init = "_this call SLX_XEH_EH_Init;_this call compile preProcessFile '\cdf_a3\cdf_a3_main_c\scripts\rhs_decal_init.sqf'";
		};
	};
	
	class CDF_A3_Ural_Support_Base : RHS_Ural_BaseTurret {};
	
	class CDF_A3_Ural_Repair_Base : CDF_A3_Ural_Support_Base {};
	
	class CDF_A3_Ural_Repair : CDF_A3_Ural_Repair_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_repair_cdf_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	
	class CDF_A3_Ural_Empty_Base : CDF_A3_Ural_Repair_Base {};
	
	class CDF_A3_Ural_Empty : CDF_A3_Ural_Empty_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_plachta_camo_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	
	class CDF_A3_Ural_Reammo_Base : CDF_A3_Ural_Support_Base {};
	
	class CDF_A3_Ural_Reammo : CDF_A3_Ural_Reammo_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_plachta_camo_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	
	class CDF_A3_Ural_ZU23_Base : RHS_Ural_BaseTurret {};
	
	class CDF_A3_Ural_ZU23 : CDF_A3_Ural_ZU23_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier_Militia";
		typicalCargo[] = {"B_CDF_A3_Soldier_Militia"};
		hiddenSelections[] = {"camo1", "camo2"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\ural_kabina_camo_co.paa", "cdf_a3\cdf_a3_main\data\ural_open_cdf_co.paa"};
		
		class EventHandlers : EventHandlers {
			init = "";
		};
	};
	class RDS_T72_AAF_04;	// External class reference
	
	class CDF_A3_T72 : RDS_T72_AAF_04 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		displayName = "T-72";
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
	};
	class RDS_BMP2_AAF_01;	// External class reference
	
	class CDF_A3_BMP2 : RDS_BMP2_AAF_01 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		hiddenselectionstextures[] = {"\RDS_APC\BMP2\data\bmp2_01_camo_co.paa", "\RDS_APC\BMP2\data\bmp2_02_camo_co.paa"};
	};
	class RDS_BMP2_HQ_AAF_01;	// External class reference
	
	class CDF_A3_BMP2_HQ : RDS_BMP2_HQ_AAF_01 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		hiddenselectionstextures[] = {"\RDS_APC\BMP2\data\bmp2_01_camo_co.paa", "\RDS_APC\BMP2\data\bmp2_02_camo_co.paa"};
	};
	class RDS_BMP2_Ambul_01;	// External class reference
	
	class CDF_A3_BMP2_Ambul : RDS_BMP2_Ambul_01 {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		hiddenselectionstextures[] = {"\RDS_APC\BMP2\data\bmp2_01_camo_co.paa", "\RDS_APC\BMP2\data\bmp2_02_camo_co.paa"};
	};
	class RDS_ZSU_AAF_04;	// External class reference
	
	class CDF_A3_ZSU : RDS_ZSU_AAF_04 {
		author = CDF_A3;
		displayName = "ZSU-23 Shilka";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
	};
	class CDF_A3_BRDM2_Base;	// External class reference
	
	class CDF_A3_BRDM2 : CDF_A3_BRDM2_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\brdm2_01_camo_co.paa"};
	};
	class CDF_A3_BRDM2_ATGM_Base;	// External class reference
	
	class CDF_A3_BRDM2_ATGM : CDF_A3_BRDM2_ATGM_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\brdm2_atgm_01_camo_co.paa"};
	};
	class CDF_A3_BRDM2_HQ_Base;	// External class reference
	
	class CDF_A3_BRDM2_HQ : CDF_A3_BRDM2_HQ_Base {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		hiddenselectionstextures[] = {"cdf_a3\cdf_a3_main\data\brdm2_01_camo_co.paa"};
	};
	class rhs_bmd2_base;	// External class reference
	
	class CDF_A3_BMD2 : rhs_bmd2_base {
		author = $STR_RHS_AUTHOR_FULL;
		displayName = "BMD-2";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		vehicleClass = "Armored";
		hiddenSelectionsTextures[] = {"rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "rhsafrf\addons\rhs_decals\Data\Labels\Misc\no_ca.paa", "cdf_a3\cdf_a3_main\data\sa_bmd2_01_cdf_co.paa", "cdf_a3\cdf_a3_main\data\sa_bmd2_02_cdf_co.paa", "cdf_a3\cdf_a3_main\data\sa_bmd2_03_cdf_co.paa", "cdf_a3\cdf_a3_main\data\sa_bmd2_01_cdf_co.paa"};
	};
	class rhs_btr_base;	// External class reference
	
	class CDF_A3_BTR70 : rhs_btr_base {
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = CDF_A3;
		crew = "B_CDF_A3_Soldier_Crew";
		typicalCargo[] = {"B_CDF_A3_Soldier_Crew"};
		driverRightLegAnimName = "pedalR";
		driverLeftLegAnimName = "pedalL";
		author = $STR_RHS_AUTHOR_FULL;
		displayName = "BTR-70";
		vehicleClass = "Armored";
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\btr70_CDF_1_co.paa", "cdf_a3\cdf_a3_main\data\btr70_CDF_2_co.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa", "\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa"};
	};
	class RDS_ZU23_AAF;	// External class reference
	class RDS_DSHKM_AAF;	// External class reference
	class RDS_DSHkM_Mini_TriPod;	// External class reference
	class RDS_AGS_AAF;	// External class reference
	class RDS_SPG9_AAF;	// External class reference
	class RDS_2b14_82mm_AAF;	// External class reference
	class RDS_D30_AAF;	// External class reference
	
	class CDF_A3_ZU23 : RDS_ZU23_AAF {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
	
	class CDF_A3_DSHKM : RDS_DSHKM_AAF {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
	
	class CDF_A3_DSHkM_Mini_TriPod : RDS_DSHkM_Mini_TriPod {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
	
	class CDF_A3_AGS : RDS_AGS_AAF {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
	
	class CDF_A3_SPG9 : RDS_SPG9_AAF {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
	
	class CDF_A3_2b14_82mm : RDS_2b14_82mm_AAF {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
	
	class CDF_A3_D30 : RDS_D30_AAF {
		author = CDF_A3;
		scope = 2;
		scopeCurator = 2;
		faction = CDF_A3;
		side = 1;
		crew = "B_CDF_A3_Soldier";
		typicalCargo[] = {"B_CDF_A3_Soldier"};
	};
};

class CfgWorlds {
	class GenericNames {
		class CzechMen {
			class FirstNames {
				petr = "Petr";
				david = "David";
				roman = "Roman";
				ivan = "Ivan";
				jan = "Jan";
				honza = "Honza";
				jenda = "Jenda";
				adam = "Adam";
				bohuslav = "Bohuslav";
				borek = "Borek";
				boris = "Boris";
				cecil = "Cecil";
				cyril = "Cyril";
				daniel = "Daniel";
				dalibor = "Dalibor";
				dan = "Dan";
				denis = "Denis";
				tom = "Tom";
				emil = "Emil";
				erik = "Erik";
				felix = "Felix";
				jakub = "Jakub";
				ladislav = "Ladislav";
				lubor = "Lubor";
				michael = "Michael";
				michal = "Michal";
				milan = "Milan";
				miroslav = "Miroslav";
				mirek = "Mirek";
				oskar = "Oskar";
				oliver = "Oliver";
				osvald = "Osvald";
				otakar = "Otakar";
				pavel = "Pavel";
				patrik = "Patrik";
				prokop = "Prokop";
				radek = "Radek";
				karel = "Karel";
				martin = "Martin";
				vojta = "Vojta";
				hugo = "Hugo";
				josef = "Josef";
				lukas = "Lukas";
				bolek = "Bolek";
				standa = "Standa";
				filip = "Filip";
				libor = "Libor";
				richard = "Richard";
				igor = "Igor";
				adolf = "Adolf";
				gustav = "Gustav";
				bohdan = "Bohdan";
				dubroslav = "Dubroslav";
				silvestr = "Silvestr";
				hynek = "Hynek";
				sasha = "Sasha";
			};
			
			class LastNames {
				soukup = "Soukup";
				svoboda = "Svoboda";
				zeman = "Zeman";
				marek = "Marek";
				david = "David";
				urban = "Urban";
				valenta = "Valenta";
				vacek = "Vacek";
				stejskal = "Stejskal";
				kraus = "Kraus";
				klaus = "Klaus";
				straka = "Straka";
				kohout = "Kohout";
				vlk = "Vlk";
				adamec = "Adamec";
				zelenka = "Zelenka";
				macek = "Macek";
				brabec = "Brabec";
				linhart = "Linhart";
				mozek = "Mozek";
				koudelka = "Koudelka";
				kouba = "Kouba";
				smetana = "Smetana";
				kvapil = "Kvapil";
				hoffmann = "Hofman";
				Dohnal = "Dohnal";
				trnka = "Trnka";
				sobotka = "Sobotka";
				musil = "Musil";
				martin = "Martin";
				michal = "Michal";
				daniel = "Daniel";
				satan = "Satan";
				turek = "Turek";
				back = "Back";
				havel = "Havel";
				malarkey = "Malarkey";
				janda = "Janda";
				strana = "Strana";
				beran = "Beran";
				nosek = "Nosek";
				vrba = "Vrba";
				sochor = "Sochor";
			};
		};
	};
};
class UniformSlotInfo;	// External class reference

class CfgWeapons {
	class Uniform_Base;	// External class reference
	class ItemInfo;	// External class reference
	class UniformItem;	// External class reference
	class rhs_6b23;	// External class reference
	
	class V_CDF_A3_6b23 : rhs_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF";
		scope = 2;
		picture = "\cdf_a3\cdf_a3_main\data\UI\icon_vest.paa";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23";
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"cdf_a3\cdf_a3_main\data\CDF_vestpart1.paa", "cdf_a3\cdf_a3_main\data\CDF_vestpart2.paa"};
		
		class ItemInfo : ItemInfo {
			hiddenSelections[] = {"Camo1", "Camo2"};
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23";
			containerClass = "Supply80";
			mass = 60;
			armor = 12;
			passThrough = 0.4;
		};
	};
	
	class V_CDF_A3_6b23_rifleman_01 : V_CDF_A3_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF (Rifleman 1)";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_sniper";
		
		class ItemInfo : ItemInfo {
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_sniper";
			containerClass = "Supply120";
			mass = 60;
		};
	};
	
	class V_CDF_A3_6b23_rifleman_02 : V_CDF_A3_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF (Rifleman 2)";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_rifleman";
		
		class ItemInfo : ItemInfo {
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_rifleman";
			containerClass = "Supply120";
			mass = 60;
		};
	};
	
	class V_CDF_A3_6b23_crewofficer : V_CDF_A3_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF (Officer)";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_crewofficer";
		
		class ItemInfo : ItemInfo {
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_crewofficer";
			containerClass = "Supply80";
			mass = 60;
		};
	};
	
	class V_CDF_A3_6b23_crew : V_CDF_A3_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF (Crew)";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_6sh46";
		
		class ItemInfo : ItemInfo {
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_6sh46";
			containerClass = "Supply120";
			mass = 60;
		};
	};
	
	class V_CDF_A3_6b23_engineer : V_CDF_A3_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF (Engineer)";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_engineer";
		
		class ItemInfo : ItemInfo {
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_engineer";
			containerClass = "Supply120";
			mass = 60;
		};
	};
	
	class V_CDF_A3_6b23_medic : V_CDF_A3_6b23 {
		author = CDF_A3;
		displayName = "6B23 CDF (Medic)";
		model = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_medic";
		
		class ItemInfo : ItemInfo {
			uniformModel = "rhsafrf\addons\rhs_infantry\gear\vests\rhs_6b23_medic";
			containerClass = "Supply140";
			mass = 60;
		};
	};
	class H_HelmetB;	// External class reference
	
	class H_CDF_A3_HelmetIA : H_HelmetB {
		author = CDF_A3;
		_generalMacro = "H_HelmetIA";
		displayName = "$STR_cdf_a3_h_helmet";
		picture = "\cdf_a3\cdf_a3_main\data\UI\icon_helmet.paa";
		model = "\cdf_a3\cdf_a3_main\cdf_helmet.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\cdf_a3\cdf_a3_main\data\helmets_co.paa"};
		
		class ItemInfo : ItemInfo {
			mass = 40;
			allowedSlots[] = {901, 605};
			uniformModel = "\cdf_a3\cdf_a3_main\cdf_helmet.p3d";
			modelSides[] = {6};
			armor = 4;
			passThrough = 0.5;
		};
	};
	
	class H_CDF_A3_fieldcap : H_HelmetB {
		author = CDF_A3;
		displayName = "Field Cap [CDF]";
		picture = "\cdf_a3\cdf_a3_main\data\UI\icon_cap.paa";
		model = "\cdf_a3\cdf_a3_main\cdf_nco_cap.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\cdf_a3\cdf_a3_main\data\helmets_co.paa"};
		
		class ItemInfo : ItemInfo {
			mass = 10;
			uniformModel = "\cdf_a3\cdf_a3_main\cdf_nco_cap.p3d";
			allowedSlots[] = {801, 901, 701, 605};
			modelSides[] = {6};
			armor = 0;
			passThrough = 1;
		};
	};
	
	class U_CDF_A3_uniform_ttsko : Uniform_Base {
		author = CDF_A3;
		scope = 2;
		displayName = "$STR_A3_combat_fatigues_cdf_a3";
		picture = "\cdf_a3\cdf_a3_main\data\UI\icon_uniform.paa";
		model = "\A3\Characters_F\Common\Suitpacks\suitpack_universal_F.p3d";
		hiddenSelections[] = {"camo"};
		hiddenSelectionsTextures[] = {"\cdf_a3\cdf_a3_main\data\Suitpacks\suitpack_CDF.paa"};
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "B_CDF_A3_Soldier_Base";
			containerClass = "Supply40";
			mass = 40;
		};
	};
	class U_B_GhillieSuit;	// External class reference
	
	class U_CDF_A3_SniperGhillie : U_B_GhillieSuit {
		author = CDF_A3;
		displayName = "$STR_A3_ghillie_suit_cdf_a3";
		picture = "\cdf_a3\cdf_a3_main\data\UI\icon_ghillie.paa";
		
		class ItemInfo : UniformItem {
			uniformModel = "-";
			uniformClass = "B_CDF_A3_Soldier_Sniper";
			containerClass = "Supply40";
			mass = 60;
		};
	};
};

class CfgGroups {
	class West {
		name = "$STR_A3_CfgGroups_West0";
		
		class CDF_A3 {
			name = CDF;
			
			class Infantry {
				name = "$STR_A3_CfgGroups_West_BLU_F_Infantry0";
				
				class CDF_InfSquad {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad0";
					faction = CDF_A3;
					rarityGroup = 0.6;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_TL";
						rank = LIEUTENANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier";
						rank = CORPORAL;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = CORPORAL;
						position[] = {11, 0, 0};
					};
					
					class Unit6 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
					
					class Unit7 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = PRIVATE;
						position[] = {15, 0, 0};
					};
					
					class Unit8 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier";
						rank = PRIVATE;
						position[] = {17, 0, 0};
					};
					
					class Unit9 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Medic";
						rank = PRIVATE;
						position[] = {19, 0, 0};
					};
				};
				
				class CDF_InfSquad_Weapons {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfSquad_Weapons0";
					faction = CDF_A3;
					rarityGroup = 0.6;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_TL";
						rank = LIEUTENANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_AR";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
					
					class Unit4 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = CORPORAL;
						position[] = {9, 0, 0};
					};
					
					class Unit5 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = CORPORAL;
						position[] = {11, 0, 0};
					};
					
					class Unit6 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
					
					class Unit7 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Marksman";
						rank = PRIVATE;
						position[] = {15, 0, 0};
					};
				};
				
				class CDF_InfSection_AT {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfTeam_AT0";
					faction = CDF_A3;
					rarityGroup = 0.2;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_AR";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class CDF_InfSection_AA {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_InfTeam_AA0";
					faction = CDF_A3;
					rarityGroup = 0.1;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Strela";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Strela";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class CDF_InfSection_MG {
					name = "$STR_A3_CfgGroups_West_BLU_F_Support_BUS_Support_MG0";
					faction = CDF_A3;
					rarityGroup = 0.1;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = SERGEANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_AR";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class CDF_InfSection_Patrol {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_ReconPatrol0";
					faction = CDF_A3;
					rarityGroup = 0.3;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Militia";
						rank = CORPORAL;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Militia";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Militia";
						rank = PRIVATE;
						position[] = {5, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Militia";
						rank = PRIVATE;
						position[] = {7, 0, 0};
					};
				};
				
				class CDF_SniperTeam {
					name = "$STR_A3_CfgGroups_West_BLU_F_Infantry_BUS_SniperTeam0";
					faction = CDF_A3;
					rarityGroup = 0.05;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Sniper";
						rank = SERGEANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Spotter";
						rank = CORPORAL;
						position[] = {3, 0, 0};
					};
				};
			};
			
			class Motorized {
				name = "$STR_A3_CfgGroups_West_BLU_F_Motorized0";
				
				class CDF_MotInfSquad {
					name = "$STR_A3_CfgGroups_West_BLU_F_Motorized_BUS_MotInf_Team0";
					faction = CDF_A3;
					rarityGroup = 0.4;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_TL";
						rank = LIEUTENANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "CDF_A3_Ural";
						rank = SERGEANT;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit4 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
					
					class Unit5 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier";
						rank = CORPORAL;
						position[] = {9, 0, 0};
					};
					
					class Unit6 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = CORPORAL;
						position[] = {11, 0, 0};
					};
					
					class Unit7 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
					
					class Unit8 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = PRIVATE;
						position[] = {15, 0, 0};
					};
					
					class Unit9 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier";
						rank = PRIVATE;
						position[] = {17, 0, 0};
					};
					
					class Unit10 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Medic";
						rank = PRIVATE;
						position[] = {19, 0, 0};
					};
				};
				
				class CDF_MotInfSection {
					name = "$STR_CfgGroups_West_CDF_A3_Motorized_CDF_MotInfSection";
					faction = CDF_A3;
					rarityGroup = 0.15;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = SERGEANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = CDF_A3_UAZ_469;
						rank = CORPORAL;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = PRIVATE;
						position[] = {3, 0, 0};
					};
				};
			};
			
			class Mechanized {
				name = "$STR_A3_CfgGroups_West_BLU_F_Mechanized0";
				
				class CDF_MechInfSquad {
					name = "$STR_A3_CfgGroups_West_BLU_F_Mechanized_BUS_MechInfSquad0";
					faction = CDF_A3;
					rarityGroup = 0.9;
					
					class Unit0 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_TL";
						rank = SERGEANT;
						position[] = {0, "+5", 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = CDF_A3_BMP2;
						rank = SERGEANT;
						position[] = {-5, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = SERGEANT;
						position[] = {3, 0, 0};
					};
					
					class Unit3 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_MG";
						rank = CORPORAL;
						position[] = {5, 0, 0};
					};
					
					class Unit4 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_Marksman";
						rank = CORPORAL;
						position[] = {7, 0, 0};
					};
					
					class Unit5 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_RPG";
						rank = PRIVATE;
						position[] = {9, 0, 0};
					};
					
					class Unit6 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier_GL";
						rank = PRIVATE;
						position[] = {11, 0, 0};
					};
					
					class Unit7 {
						side = 1;
						vehicle = "B_CDF_A3_Soldier";
						rank = PRIVATE;
						position[] = {13, 0, 0};
					};
				};
			};
			
			class Armored {
				name = "$STR_A3_CfgGroups_West_BLU_F_Armored0";
				
				class CDF_TankPlatoon {
					name = "$STR_A3_CfgGroups_West_BLU_F_Armored_BUS_TankPlatoon0";
					faction = CDF_A3;
					rarityGroup = 0.25;
					
					class Unit0 {
						side = 1;
						vehicle = CDF_A3_T72;
						rank = CAPTAIN;
						position[] = {0, +10, 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = CDF_A3_T72;
						rank = LIEUTENANT;
						position[] = {5, 0, 0};
					};
					
					class Unit2 {
						side = 1;
						vehicle = CDF_A3_T72;
						rank = SERGEANT;
						position[] = {10, 0, 0};
					};
				};
			};
			
			class Air {
				name = "$STR_CfgGroups_West_CDF_A3_Air";
				
				class CDF_Mi24DSquadron {
					name = "$STR_CfgGroups_West_CDF_A3_Air_CDF_Mi24DSquadron";
					faction = CDF_A3;
					rarityGroup = 0.1;
					minAltitude = 40;
					maxAltitude = 100;
					
					class Unit0 {
						side = 1;
						vehicle = "CDF_A3_Mi_24p";
						rank = CAPTAIN;
						position[] = {0, +15, 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "CDF_A3_Mi_24p";
						rank = LIEUTENANT;
						position[] = {15, 0, 0};
					};
				};
				
				class CDF_Mi8Squadron {
					name = "$STR_CfgGroups_West_CDF_A3_Air_CDF_Mi8Squadron";
					faction = CDF_A3;
					rarityGroup = 0.3;
					minAltitude = 60;
					maxAltitude = 150;
					
					class Unit0 {
						side = 1;
						vehicle = "CDF_A3_Mi17";
						rank = CAPTAIN;
						position[] = {0, +15, 0};
					};
					
					class Unit1 {
						side = 1;
						vehicle = "CDF_A3_Mi17";
						rank = LIEUTENANT;
						position[] = {15, 0, 0};
					};
				};
			};
		};
	};
};
