class Heli_Light_01_unarmed_base_F;
class Heli_Light_01_armed_base_F;
class Heli_Light_01_civil_base_F;
class Heli_Light_02_base_F;
class Heli_Light_02_unarmed_base_F;
class Heli_Attack_01_base_F;
class Heli_Attack_02_base_F;
class Heli_Transport_01_base_F;
class Heli_Transport_02_base_F;
class Heli_light_03_base_F;
class Heli_light_03_unarmed_base_F;
class Plane_CAS_01_base_F;
class Plane_CAS_02_base_F;
class Plane_Fighter_03_base_F;
class Heli_Transport_03_base_F;
class Heli_Transport_03_unarmed_base_F;
class Heli_Transport_04_base_F;
class UAV_01_base_F;
class UAV_02_base_F;
class UAV_02_CAS_base_F;
class B_Heli_Light_01_F: Heli_Light_01_unarmed_base_F { scope = 1; };
class B_Heli_Light_01_armed_F: Heli_Light_01_armed_base_F { scope = 1; };
class C_Heli_Light_01_civil_F: Heli_Light_01_civil_base_F { scope = 1; };
class O_Heli_Light_02_F: Heli_Light_02_base_F { scope = 1; };
class O_Heli_Light_02_unarmed_F: Heli_Light_02_unarmed_base_F { scope = 1; };
class O_Heli_Light_02_v2_F: Heli_Light_02_base_F { scope = 1; };
class B_Heli_Attack_01_F: Heli_Attack_01_base_F { scope = 1; };
class O_Heli_Attack_02_F: Heli_Attack_02_base_F { scope = 1; };
class O_Heli_Attack_02_black_F: Heli_Attack_02_base_F { scope = 1; };
class B_Heli_Transport_01_F: Heli_Transport_01_base_F { scope = 1; };
class B_Heli_Transport_01_camo_F: B_Heli_Transport_01_F { scope = 1; };
class I_Heli_Transport_02_F: Heli_Transport_02_base_F { scope = 1; };
class I_Heli_light_03_F: Heli_light_03_base_F { scope = 1; };
class I_Heli_light_03_unarmed_F: Heli_light_03_unarmed_base_F { scope = 1; };
class B_Plane_CAS_01_F: Plane_CAS_01_base_F { scope = 1; };
class O_Plane_CAS_02_F: Plane_CAS_02_base_F { scope = 1; };
class I_Plane_Fighter_03_CAS_F: Plane_Fighter_03_base_F { scope = 1; };
class I_Plane_Fighter_03_AA_F: I_Plane_Fighter_03_CAS_F { scope = 1; };
class B_Heli_Transport_03_F: Heli_Transport_03_base_F { scope = 1; };
class B_Heli_Transport_03_unarmed_F: Heli_Transport_03_unarmed_base_F { scope = 1; };
class O_Heli_Transport_04_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_ammo_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_bench_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_box_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_covered_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_fuel_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_medevac_F: Heli_Transport_04_base_F { scope = 1; };
class O_Heli_Transport_04_repair_F: Heli_Transport_04_base_F { scope = 1; };
class B_UAV_01_F: UAV_01_base_F { scope = 1; };
class O_UAV_01_F: UAV_01_base_F { scope = 1; };
class I_UAV_01_F: UAV_01_base_F { scope = 1; };
class B_UAV_02_F: UAV_02_base_F { scope = 1; };
class O_UAV_02_F: UAV_02_base_F { scope = 1; };
class I_UAV_02_F: UAV_02_base_F { scope = 1; };
class B_UAV_02_CAS_F: UAV_02_CAS_base_F { scope = 1; };
class O_UAV_02_CAS_F: UAV_02_CAS_base_F { scope = 1; };
class I_UAV_02_CAS_F: UAV_02_CAS_base_F { scope = 1; };
