class MRAP_01_base_F;
class MRAP_01_gmg_base_F;
class MRAP_01_hmg_base_F;
class MRAP_02_base_F;
class MRAP_02_hmg_base_F;
class MRAP_02_gmg_base_F;
class Offroad_01_civil_base_F;
class Offroad_01_repair_base_F;
class Offroad_01_repair_military_base_F;
class I_G_Offroad_01_F;
class I_G_Offroad_01_armed_F;
class Quadbike_01_base_F;
class I_G_Quadbike_01_F;
class MRAP_03_base_F;
class MRAP_03_hmg_base_F;
class MRAP_03_gmg_base_F;
class Truck_01_base_F;
class Truck_02_base_F;
class Truck_02_transport_base_F;
class Truck_03_base_F;
class Hatchback_01_base_F;
class Hatchback_01_sport_base_F;
class SUV_01_base_F;
class Truck_02_box_base_F;
class Truck_02_medical_base_F;
class Truck_02_Ammo_base_F;
class Truck_02_fuel_base_F;
class Van_01_transport_base_F;
class Van_01_box_base_F;
class Van_01_fuel_base_F;
class I_G_Van_01_transport_F;
class I_G_Van_01_fuel_F;
class C_Kart_01_F_Base;
class B_APC_Wheeled_01_base_F;
class O_APC_Wheeled_02_base_F;
class I_APC_Wheeled_03_base_F;
class UGV_01_base_F;
class UGV_01_rcws_base_F;
class B_MRAP_01_F: MRAP_01_base_F { scope = 1; };
class B_MRAP_01_gmg_F: MRAP_01_gmg_base_F { scope = 1; };
class B_MRAP_01_hmg_F: MRAP_01_hmg_base_F { scope = 1; };
class O_MRAP_02_F: MRAP_02_base_F { scope = 1; };
class O_MRAP_02_hmg_F: MRAP_02_hmg_base_F { scope = 1; };
class O_MRAP_02_gmg_F: MRAP_02_gmg_base_F { scope = 1; };
// class C_Offroad_01_F: Offroad_01_civil_base_F { scope = 1; };
// class C_Offroad_01_repair_F: Offroad_01_repair_base_F { scope = 1; };
// class B_G_Offroad_01_repair_F: Offroad_01_repair_military_base_F { scope = 1; };
// class B_G_Offroad_01_F: I_G_Offroad_01_F { scope = 1; };
class B_G_Offroad_01_armed_F: I_G_Offroad_01_armed_F { scope = 1; };
// class C_Quadbike_01_F: Quadbike_01_base_F { scope = 1; };
// class B_Quadbike_01_F: Quadbike_01_base_F { scope = 1; };
// class O_Quadbike_01_F: Quadbike_01_base_F { scope = 1; };
// class I_Quadbike_01_F: Quadbike_01_base_F { scope = 1; };
// class B_G_Quadbike_01_F: I_G_Quadbike_01_F { scope = 1; };
class I_MRAP_03_F: MRAP_03_base_F { scope = 1; };
class I_MRAP_03_hmg_F: MRAP_03_hmg_base_F { scope = 1; };
class I_MRAP_03_gmg_F: MRAP_03_gmg_base_F { scope = 1; };
// class B_Truck_01_transport_F: Truck_01_base_F { scope = 1; };
// class B_Truck_01_covered_F: B_Truck_01_transport_F { scope = 1; };
// class O_Truck_02_covered_F: Truck_02_base_F { scope = 1; };
// class O_Truck_02_transport_F: Truck_02_transport_base_F { scope = 1; };
// class I_Truck_02_covered_F: Truck_02_base_F { scope = 1; };
// class I_Truck_02_transport_F: Truck_02_transport_base_F { scope = 1; };
// class O_Truck_03_transport_F: Truck_03_base_F { scope = 1; };
// class O_Truck_03_covered_F: Truck_03_base_F { scope = 1; };
// class O_Truck_03_repair_F: Truck_03_base_F { scope = 1; };
// class O_Truck_03_ammo_F: Truck_03_base_F { scope = 1; };
// class O_Truck_03_fuel_F: Truck_03_base_F { scope = 1; };
// class O_Truck_03_medical_F: Truck_03_base_F { scope = 1; };
// class O_Truck_03_device_F: Truck_03_base_F { scope = 1; };
// class C_Hatchback_01_F: Hatchback_01_base_F { scope = 1; };
// class C_Hatchback_01_sport_F: Hatchback_01_sport_base_F { scope = 1; };
// class C_SUV_01_F: SUV_01_base_F { scope = 1; };
// class B_Truck_01_mover_F: B_Truck_01_transport_F { scope = 1; };
// class B_Truck_01_box_F: B_Truck_01_mover_F { scope = 1; };
// class B_Truck_01_Repair_F: B_Truck_01_mover_F { scope = 1; };
// class B_Truck_01_ammo_F: B_Truck_01_mover_F { scope = 1; };
// class B_Truck_01_fuel_F: B_Truck_01_mover_F { scope = 1; };
// class B_Truck_01_medical_F: B_Truck_01_transport_F { scope = 1; };
// class O_Truck_02_box_F: Truck_02_box_base_F { scope = 1; };
// class O_Truck_02_medical_F: Truck_02_medical_base_F { scope = 1; };
// class O_Truck_02_Ammo_F: Truck_02_Ammo_base_F { scope = 1; };
// class O_Truck_02_fuel_F: Truck_02_fuel_base_F { scope = 1; };
// class I_Truck_02_ammo_F: Truck_02_Ammo_base_F { scope = 1; };
// class I_Truck_02_box_F: Truck_02_box_base_F { scope = 1; };
// class I_Truck_02_medical_F: Truck_02_medical_base_F { scope = 1; };
// class I_Truck_02_fuel_F: Truck_02_fuel_base_F { scope = 1; };
// class C_Van_01_transport_F: Van_01_transport_base_F { scope = 1; };
// class C_Van_01_box_F: Van_01_box_base_F { scope = 1; };
// class C_Van_01_fuel_F: Van_01_fuel_base_F { scope = 1; };
// class B_G_Van_01_transport_F: I_G_Van_01_transport_F { scope = 1; };
// class B_G_Van_01_fuel_F: I_G_Van_01_fuel_F { scope = 1; };
class C_Kart_01_F: C_Kart_01_F_Base { scope = 1; };
class C_Kart_01_Fuel_F: C_Kart_01_F_Base { scope = 1; };
class C_Kart_01_Blu_F: C_Kart_01_F_Base { scope = 1; };
class C_Kart_01_Red_F: C_Kart_01_F_Base { scope = 1; };
class C_Kart_01_Vrana_F: C_Kart_01_F_Base { scope = 1; };
class B_APC_Wheeled_01_cannon_F: B_APC_Wheeled_01_base_F { scope = 1; };
class O_APC_Wheeled_02_rcws_F: O_APC_Wheeled_02_base_F { scope = 1; };
class I_APC_Wheeled_03_cannon_F: I_APC_Wheeled_03_base_F { scope = 1; };
class B_UGV_01_F: UGV_01_base_F { scope = 1; };
class O_UGV_01_F: UGV_01_base_F { scope = 1; };
class I_UGV_01_F: UGV_01_base_F { scope = 1; };
class B_UGV_01_rcws_F: UGV_01_rcws_base_F { scope = 1; };
class O_UGV_01_rcws_F: UGV_01_rcws_base_F { scope = 1; };
class I_UGV_01_rcws_F: UGV_01_rcws_base_F { scope = 1; };
