class Civilian_F;
class VirtualMan_F;
class B_Soldier_base_F;
class B_Soldier_03_f;
class B_Soldier_02_f;
class B_Soldier_04_f;
class B_Soldier_05_f;
class B_Soldier_diver_base_F;
class B_Soldier_recon_base;
class B_Soldier_sniper_base_F;
class B_Soldier_support_base_F;
class I_G_Soldier_F;
class I_G_Soldier_lite_F;
class I_G_Soldier_SL_F;
class I_G_Soldier_TL_F;
class I_G_Soldier_AR_F;
class I_G_medic_F;
class I_G_engineer_F;
class I_G_Soldier_exp_F;
class I_G_Soldier_GL_F;
class I_G_Soldier_M_F;
class I_G_Soldier_LAT_F;
class I_G_Soldier_A_F;
class I_G_officer_F;
class I_Soldier_base_F;
class I_Soldier_02_F;
class I_Soldier_03_F;
class I_Soldier_04_F;
class I_Soldier_diver_base_F;
class I_Soldier_sniper_base_F;
class I_Soldier_support_base_F;
class O_Soldier_base_F;
class O_Soldier_02_F;
class O_Soldier_diver_base_F;
class O_Soldier_sniper_base_F;
class O_Soldier_recon_base;
class O_Soldier_support_base_F;
class O_Soldier_Urban_base;
class B_ghillie_base_F;
class O_ghillie_base_F;
class I_ghillie_base_F;
class I_G_Sharpshooter_F;
class C_man_1: Civilian_F { scope = 1; };
class HeadlessClient_F: VirtualMan_F { scope = 1; };
class B_Soldier_F: B_Soldier_base_F { scope = 1; };
class B_RangeMaster_F: B_Soldier_base_F { scope = 1; };
class B_Soldier_lite_F: B_Soldier_03_f { scope = 1; };
class B_Soldier_GL_F: B_Soldier_base_F { scope = 1; };
class B_soldier_AR_F: B_Soldier_02_f { scope = 1; };
class B_Soldier_SL_F: B_Soldier_03_f { scope = 1; };
class B_Soldier_TL_F: B_Soldier_03_f { scope = 1; };
class B_soldier_M_F: B_Soldier_base_F { scope = 1; };
class B_soldier_LAT_F: B_Soldier_base_F { scope = 1; };
class B_medic_F: B_Soldier_02_f { scope = 1; };
class B_soldier_repair_F: B_Soldier_base_F { scope = 1; };
class B_soldier_exp_F: B_Soldier_base_F { scope = 1; };
class B_Helipilot_F: B_Soldier_04_f { scope = 1; };
class B_Soldier_A_F: B_Soldier_base_F { scope = 1; };
class B_soldier_AT_F: B_Soldier_base_F { scope = 1; };
class B_soldier_AA_F: B_Soldier_base_F { scope = 1; };
class B_engineer_F: B_Soldier_03_f { scope = 1; };
class B_crew_F: B_Soldier_03_f { scope = 1; };
class B_officer_F: B_Soldier_base_F { scope = 1; };
class B_Competitor_F: B_RangeMaster_F { scope = 1; };
class B_Pilot_F: B_Soldier_05_f { scope = 1; };
class B_helicrew_F: B_Helipilot_F { scope = 1; };
class B_soldier_PG_F: B_Soldier_base_F { scope = 1; };
class B_soldier_UAV_F: B_Soldier_base_F { scope = 1; };
class b_soldier_unarmed_f: B_Soldier_F { scope = 1; };
class B_diver_F: B_Soldier_diver_base_F { scope = 1; };
class B_diver_TL_F: B_Soldier_diver_base_F { scope = 1; };
class B_diver_exp_F: B_Soldier_diver_base_F { scope = 1; };
class B_recon_F: B_Soldier_recon_base { scope = 1; };
class B_recon_LAT_F: B_Soldier_recon_base { scope = 1; };
class B_recon_exp_F: B_Soldier_recon_base { scope = 1; };
class B_recon_medic_F: B_Soldier_recon_base { scope = 1; };
class B_recon_TL_F: B_Soldier_recon_base { scope = 1; };
class B_recon_M_F: B_Soldier_recon_base { scope = 1; };
class B_recon_JTAC_F: B_Soldier_recon_base { scope = 1; };
class B_spotter_F: B_Soldier_sniper_base_F { scope = 1; };
class B_sniper_F: B_Soldier_sniper_base_F { scope = 1; };
class B_Story_SF_Captain_F: B_Soldier_base_F { scope = 1; };
class B_Story_Protagonist_F: B_Soldier_base_F { scope = 1; };
class B_Story_Pilot_F: B_Soldier_base_F { scope = 1; };
class B_CTRG_soldier_GL_LAT_F: B_Soldier_base_F { scope = 1; };
class B_CTRG_soldier_engineer_exp_F: B_Soldier_base_F { scope = 1; };
class B_CTRG_soldier_M_medic_F: B_Soldier_base_F { scope = 1; };
class B_CTRG_soldier_AR_A_F: B_Soldier_base_F { scope = 1; };
class B_soldier_AAR_F: B_Soldier_support_base_F { scope = 1; };
class B_soldier_AAT_F: B_Soldier_support_base_F { scope = 1; };
class B_soldier_AAA_F: B_soldier_AAT_F { scope = 1; };
class B_support_MG_F: B_Soldier_support_base_F { scope = 1; };
class B_support_GMG_F: B_Soldier_support_base_F { scope = 1; };
class B_support_Mort_F: B_Soldier_support_base_F { scope = 1; };
class B_support_AMG_F: B_Soldier_support_base_F { scope = 1; };
class B_support_AMort_F: B_Soldier_support_base_F { scope = 1; };
class C_man_1_1_F: C_man_1 { scope = 1; };
class C_man_1_2_F: C_man_1_1_F { scope = 1; };
class C_man_1_3_F: C_man_1_1_F { scope = 1; };
class C_man_polo_1_F: C_man_1 { scope = 1; };
class C_man_polo_1_F_afro: C_man_polo_1_F { scope = 1; };
class C_man_polo_1_F_euro: C_man_polo_1_F { scope = 1; };
class C_man_polo_1_F_asia: C_man_polo_1_F { scope = 1; };
class C_man_polo_2_F: C_man_polo_1_F { scope = 1; };
class C_man_polo_2_F_afro: C_man_polo_2_F { scope = 1; };
class C_man_polo_2_F_euro: C_man_polo_2_F { scope = 1; };
class C_man_polo_2_F_asia: C_man_polo_2_F { scope = 1; };
class C_man_polo_3_F: C_man_polo_1_F { scope = 1; };
class C_man_polo_3_F_afro: C_man_polo_3_F { scope = 1; };
class C_man_polo_3_F_euro: C_man_polo_3_F { scope = 1; };
class C_man_polo_3_F_asia: C_man_polo_3_F { scope = 1; };
class C_man_polo_4_F: C_man_polo_1_F { scope = 1; };
class C_man_polo_4_F_afro: C_man_polo_4_F { scope = 1; };
class C_man_polo_4_F_euro: C_man_polo_4_F { scope = 1; };
class C_man_polo_4_F_asia: C_man_polo_4_F { scope = 1; };
class C_man_polo_5_F: C_man_polo_1_F { scope = 1; };
class C_man_polo_5_F_afro: C_man_polo_5_F { scope = 1; };
class C_man_polo_5_F_euro: C_man_polo_5_F { scope = 1; };
class C_man_polo_5_F_asia: C_man_polo_5_F { scope = 1; };
class C_man_polo_6_F: C_man_polo_1_F { scope = 1; };
class C_man_polo_6_F_afro: C_man_polo_6_F { scope = 1; };
class C_man_polo_6_F_euro: C_man_polo_6_F { scope = 1; };
class C_man_polo_6_F_asia: C_man_polo_6_F { scope = 1; };
class C_man_p_fugitive_F: C_man_1 { scope = 1; };
class C_man_p_fugitive_F_afro: C_man_p_fugitive_F { scope = 1; };
class C_man_p_fugitive_F_euro: C_man_p_fugitive_F { scope = 1; };
class C_man_p_fugitive_F_asia: C_man_p_fugitive_F { scope = 1; };
class C_man_p_beggar_F: C_man_p_fugitive_F { scope = 1; };
class C_man_p_beggar_F_afro: C_man_p_beggar_F { scope = 1; };
class C_man_p_beggar_F_euro: C_man_p_beggar_F { scope = 1; };
class C_man_p_beggar_F_asia: C_man_p_beggar_F { scope = 1; };
class C_man_w_worker_F: C_man_1 { scope = 1; };
class C_scientist_F: C_man_w_worker_F { scope = 1; };
class C_man_hunter_1_F: C_man_1 { scope = 1; };
class C_man_p_shorts_1_F: C_man_1 { scope = 1; };
class C_man_p_shorts_1_F_afro: C_man_p_shorts_1_F { scope = 1; };
class C_man_p_shorts_1_F_euro: C_man_p_shorts_1_F { scope = 1; };
class C_man_p_shorts_1_F_asia: C_man_p_shorts_1_F { scope = 1; };
class C_man_shorts_1_F: C_man_p_shorts_1_F { scope = 1; };
class C_man_shorts_1_F_afro: C_man_shorts_1_F { scope = 1; };
class C_man_shorts_1_F_euro: C_man_shorts_1_F { scope = 1; };
class C_man_shorts_1_F_asia: C_man_shorts_1_F { scope = 1; };
class C_man_shorts_2_F: C_man_p_shorts_1_F { scope = 1; };
class C_man_shorts_2_F_afro: C_man_shorts_2_F { scope = 1; };
class C_man_shorts_2_F_euro: C_man_shorts_2_F { scope = 1; };
class C_man_shorts_2_F_asia: C_man_shorts_2_F { scope = 1; };
class C_man_shorts_3_F: C_man_p_shorts_1_F { scope = 1; };
class C_man_shorts_3_F_afro: C_man_shorts_3_F { scope = 1; };
class C_man_shorts_3_F_euro: C_man_shorts_3_F { scope = 1; };
class C_man_shorts_3_F_asia: C_man_shorts_3_F { scope = 1; };
class C_man_shorts_4_F: C_man_p_shorts_1_F { scope = 1; };
class C_man_shorts_4_F_afro: C_man_shorts_4_F { scope = 1; };
class C_man_shorts_4_F_euro: C_man_shorts_4_F { scope = 1; };
class C_man_shorts_4_F_asia: C_man_shorts_4_F { scope = 1; };
class C_man_pilot_F: C_man_1 { scope = 1; };
class C_journalist_F: C_man_1 { scope = 1; };
class C_Orestes: C_man_1 { scope = 1; };
class C_Nikos: C_Orestes { scope = 1; };
class C_Nikos_aged: C_Nikos { scope = 1; };
class B_G_Soldier_F: I_G_Soldier_F { scope = 1; };
class B_G_Soldier_lite_F: I_G_Soldier_lite_F { scope = 1; };
class B_G_Soldier_SL_F: I_G_Soldier_SL_F { scope = 1; };
class B_G_Soldier_TL_F: I_G_Soldier_TL_F { scope = 1; };
class B_G_Soldier_AR_F: I_G_Soldier_AR_F { scope = 1; };
class B_G_medic_F: I_G_medic_F { scope = 1; };
class B_G_engineer_F: I_G_engineer_F { scope = 1; };
class B_G_Soldier_exp_F: I_G_Soldier_exp_F { scope = 1; };
class B_G_Soldier_GL_F: I_G_Soldier_GL_F { scope = 1; };
class B_G_Soldier_M_F: I_G_Soldier_M_F { scope = 1; };
class B_G_Soldier_LAT_F: I_G_Soldier_LAT_F { scope = 1; };
class B_G_Soldier_A_F: I_G_Soldier_A_F { scope = 1; };
class B_G_officer_F: I_G_officer_F { scope = 1; };
class b_g_soldier_unarmed_f: B_G_Soldier_F { scope = 1; };
class b_g_survivor_F: B_G_Soldier_F { scope = 1; };
class I_G_Story_Protagonist_F: B_G_Soldier_F { scope = 1; };
class I_G_Story_SF_Captain_F: B_G_Soldier_F { scope = 1; };
class I_G_resistanceLeader_F: I_G_Story_Protagonist_F { scope = 1; };
class I_soldier_F: I_Soldier_base_F { scope = 1; };
class I_Soldier_lite_F: I_Soldier_02_F { scope = 1; };
class I_Soldier_A_F: I_Soldier_02_F { scope = 1; };
class I_Soldier_GL_F: I_Soldier_base_F { scope = 1; };
class I_Soldier_AR_F: I_Soldier_02_F { scope = 1; };
class I_Soldier_SL_F: I_Soldier_02_F { scope = 1; };
class I_Soldier_TL_F: I_Soldier_base_F { scope = 1; };
class I_Soldier_M_F: I_Soldier_base_F { scope = 1; };
class I_Soldier_LAT_F: I_Soldier_base_F { scope = 1; };
class I_Soldier_AT_F: I_Soldier_base_F { scope = 1; };
class I_Soldier_AA_F: I_Soldier_02_F { scope = 1; };
class I_medic_F: I_Soldier_02_F { scope = 1; };
class I_Soldier_repair_F: I_Soldier_02_F { scope = 1; };
class I_Soldier_exp_F: I_Soldier_02_F { scope = 1; };
class I_engineer_F: I_Soldier_base_F { scope = 1; };
class I_crew_F: I_Soldier_base_F { scope = 1; };
class I_helipilot_F: I_Soldier_03_F { scope = 1; };
class I_pilot_F: I_Soldier_04_F { scope = 1; };
class I_helicrew_F: I_helipilot_F { scope = 1; };
class I_officer_F: I_Soldier_base_F { scope = 1; };
class I_Story_Colonel_F: I_officer_F { scope = 1; };
class I_soldier_UAV_F: I_Soldier_base_F { scope = 1; };
class i_soldier_unarmed_f: I_soldier_F { scope = 1; };
class I_diver_F: I_Soldier_diver_base_F { scope = 1; };
class I_diver_exp_F: I_Soldier_diver_base_F { scope = 1; };
class I_diver_TL_F: I_Soldier_diver_base_F { scope = 1; };
class I_Spotter_F: I_Soldier_sniper_base_F { scope = 1; };
class I_Sniper_F: I_Soldier_sniper_base_F { scope = 1; };
class I_Soldier_AAR_F: I_Soldier_support_base_F { scope = 1; };
class I_Soldier_AAT_F: I_Soldier_support_base_F { scope = 1; };
class I_Soldier_AAA_F: I_Soldier_AAT_F { scope = 1; };
class I_support_MG_F: I_Soldier_support_base_F { scope = 1; };
class I_support_GMG_F: I_Soldier_support_base_F { scope = 1; };
class I_support_Mort_F: I_Soldier_support_base_F { scope = 1; };
class I_support_AMG_F: I_Soldier_support_base_F { scope = 1; };
class I_support_AMort_F: I_Soldier_support_base_F { scope = 1; };
class O_Soldier_F: O_Soldier_base_F { scope = 1; };
class O_officer_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_lite_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_GL_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_AR_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_SL_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_TL_F: O_Soldier_base_F { scope = 1; };
class O_soldier_M_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_LAT_F: O_Soldier_base_F { scope = 1; };
class O_medic_F: O_Soldier_base_F { scope = 1; };
class O_soldier_repair_F: O_Soldier_base_F { scope = 1; };
class O_soldier_exp_F: O_Soldier_base_F { scope = 1; };
class O_helipilot_F: O_Soldier_02_F { scope = 1; };
class O_Soldier_A_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_AT_F: O_Soldier_base_F { scope = 1; };
class O_Soldier_AA_F: O_Soldier_base_F { scope = 1; };
class O_engineer_F: O_Soldier_base_F { scope = 1; };
class O_crew_F: O_Soldier_base_F { scope = 1; };
class O_Pilot_F: O_helipilot_F { scope = 1; };
class O_helicrew_F: O_helipilot_F { scope = 1; };
class O_soldier_PG_F: O_Soldier_base_F { scope = 1; };
class O_Story_Colonel_F: O_Soldier_base_F { scope = 1; };
class O_Story_CEO_F: O_Soldier_base_F { scope = 1; };
class O_soldier_UAV_F: O_Soldier_base_F { scope = 1; };
class o_soldier_unarmed_f: O_Soldier_F { scope = 1; };
class O_diver_F: O_Soldier_diver_base_F { scope = 1; };
class O_diver_TL_F: O_Soldier_diver_base_F { scope = 1; };
class O_diver_exp_F: O_Soldier_diver_base_F { scope = 1; };
class O_spotter_F: O_Soldier_sniper_base_F { scope = 1; };
class O_sniper_F: O_Soldier_sniper_base_F { scope = 1; };
class O_recon_F: O_Soldier_recon_base { scope = 1; };
class O_recon_M_F: O_Soldier_recon_base { scope = 1; };
class O_recon_LAT_F: O_Soldier_recon_base { scope = 1; };
class O_recon_medic_F: O_Soldier_recon_base { scope = 1; };
class O_recon_exp_F: O_Soldier_recon_base { scope = 1; };
class O_recon_JTAC_F: O_Soldier_recon_base { scope = 1; };
class O_recon_TL_F: O_Soldier_recon_base { scope = 1; };
class O_Soldier_AAR_F: O_Soldier_support_base_F { scope = 1; };
class O_Soldier_AAT_F: O_Soldier_support_base_F { scope = 1; };
class O_Soldier_AAA_F: O_Soldier_AAT_F { scope = 1; };
class O_support_MG_F: O_Soldier_support_base_F { scope = 1; };
class O_support_GMG_F: O_Soldier_support_base_F { scope = 1; };
class O_support_Mort_F: O_Soldier_support_base_F { scope = 1; };
class O_support_AMG_F: O_Soldier_support_base_F { scope = 1; };
class O_support_AMort_F: O_Soldier_support_base_F { scope = 1; };
class O_soldierU_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_AR_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_AAR_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_LAT_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_AT_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_AAT_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_AA_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_AAA_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_TL_F: O_Soldier_Urban_base { scope = 1; };
class O_SoldierU_SL_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_medic_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_repair_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_exp_F: O_Soldier_Urban_base { scope = 1; };
class O_engineer_U_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_M_F: O_Soldier_Urban_base { scope = 1; };
class O_soldierU_A_F: O_Soldier_Urban_base { scope = 1; };
class O_SoldierU_GL_F: O_Soldier_Urban_base { scope = 1; };
class C_Driver_1_F: C_man_1 { scope = 1; };
class C_Driver_2_F: C_Driver_1_F { scope = 1; };
class C_Driver_3_F: C_Driver_1_F { scope = 1; };
class C_Driver_4_F: C_Driver_1_F { scope = 1; };
class C_Marshal_F: B_RangeMaster_F { scope = 1; };
class B_Soldier_VR_F: B_Soldier_base_F { scope = 1; };
class O_Soldier_VR_F: O_Soldier_base_F { scope = 1; };
class I_Soldier_VR_F: I_Soldier_base_F { scope = 1; };
class C_Soldier_VR_F: C_man_1 { scope = 1; };
class B_Protagonist_VR_F: B_Soldier_base_F { scope = 1; };
class O_Protagonist_VR_F: O_Soldier_base_F { scope = 1; };
class I_Protagonist_VR_F: I_Soldier_base_F { scope = 1; };
class B_ghillie_lsh_F: B_ghillie_base_F { scope = 1; };
class B_ghillie_sard_F: B_ghillie_base_F { scope = 1; };
class B_ghillie_ard_F: B_ghillie_base_F { scope = 1; };
class O_ghillie_lsh_F: O_ghillie_base_F { scope = 1; };
class O_ghillie_sard_F: O_ghillie_base_F { scope = 1; };
class O_ghillie_ard_F: O_ghillie_base_F { scope = 1; };
class I_ghillie_lsh_F: I_ghillie_base_F { scope = 1; };
class I_ghillie_sard_F: I_ghillie_base_F { scope = 1; };
class I_ghillie_ard_F: I_ghillie_base_F { scope = 1; };
class B_Sharpshooter_F: B_Soldier_base_F { scope = 1; };
class B_Recon_Sharpshooter_F: B_Soldier_recon_base { scope = 1; };
class B_CTRG_Sharphooter_F: B_Soldier_base_F { scope = 1; };
class B_HeavyGunner_F: B_Soldier_base_F { scope = 1; };
class O_Sharpshooter_F: O_Soldier_base_F { scope = 1; };
class O_Urban_Sharpshooter_F: O_Soldier_Urban_base { scope = 1; };
class O_Pathfinder_F: O_Soldier_recon_base { scope = 1; };
class O_HeavyGunner_F: O_Soldier_base_F { scope = 1; };
class O_Urban_HeavyGunner_F: O_Soldier_Urban_base { scope = 1; };
class B_G_Sharpshooter_F: I_G_Sharpshooter_F { scope = 1; };
class b_survivor_F: B_Soldier_F { scope = 1; };
class o_survivor_F: O_Soldier_F { scope = 1; };
class i_survivor_F: I_soldier_F { scope = 1; };
class VirtualCurator_F: VirtualMan_F { scope = 1; };
class B_VirtualCurator_F: VirtualCurator_F { scope = 1; };
class O_VirtualCurator_F: VirtualCurator_F { scope = 1; };
class I_VirtualCurator_F: VirtualCurator_F { scope = 1; };
class C_VirtualCurator_F: VirtualCurator_F { scope = 1; };
