class Boat_Armed_01_minigun_base_F;
class Boat_Armed_01_base_F;
class Rubber_duck_base_F;
class Rescue_duck_base_F;
class SDV_01_base_F;
class Boat_Civil_01_base_F;
class I_G_Boat_Transport_01_F;
class B_Boat_Armed_01_minigun_F: Boat_Armed_01_minigun_base_F { scope = 1; };
class O_Boat_Armed_01_hmg_F: Boat_Armed_01_base_F { scope = 1; };
//class B_Boat_Transport_01_F: Rubber_duck_base_F { scope = 1; };
//class O_Boat_Transport_01_F: Rubber_duck_base_F { scope = 1; };
//class B_Lifeboat: Rescue_duck_base_F { scope = 1; };
//class O_Lifeboat: Rescue_duck_base_F { scope = 1; };
//class C_Rubberboat: Rescue_duck_base_F { scope = 1; };
class I_Boat_Armed_01_minigun_F: Boat_Armed_01_minigun_base_F { scope = 1; };
//class I_Boat_Transport_01_F: Rubber_duck_base_F { scope = 1; };
//class B_SDV_01_F: SDV_01_base_F { scope = 1; };
//class O_SDV_01_F: SDV_01_base_F { scope = 1; };
//class I_SDV_01_F: SDV_01_base_F { scope = 1; };
//class C_Boat_Civil_01_F: Boat_Civil_01_base_F { scope = 1; };
//class C_Boat_Civil_01_rescue_F: Boat_Civil_01_base_F { scope = 1; };
//class C_Boat_Civil_01_police_F: Boat_Civil_01_base_F { scope = 1; };
//class B_G_Boat_Transport_01_F: I_G_Boat_Transport_01_F { scope = 1; };
