class HMG_01_base_F;
class HMG_01_high_base_F;
class HMG_01_A_base_F;
class GMG_01_base_F;
class GMG_01_high_base_F;
class GMG_01_A_base_F;
class Mortar_01_base_F;
class I_G_Mortar_01_F;
class Static_Designator_01_base_F;
class Static_Designator_02_base_F;
class Pod_Heli_Transport_04_base_F;
class AA_01_base_F;
class AT_01_base_F;
class B_HMG_01_F: HMG_01_base_F { scope = 1; };
class O_HMG_01_F: HMG_01_base_F { scope = 1; };
class I_HMG_01_F: HMG_01_base_F { scope = 1; };
class B_HMG_01_high_F: HMG_01_high_base_F { scope = 1; };
class O_HMG_01_high_F: HMG_01_high_base_F { scope = 1; };
class I_HMG_01_high_F: HMG_01_high_base_F { scope = 1; };
class B_HMG_01_A_F: HMG_01_A_base_F { scope = 1; };
class O_HMG_01_A_F: HMG_01_A_base_F { scope = 1; };
class I_HMG_01_A_F: HMG_01_A_base_F { scope = 1; };
class B_GMG_01_F: GMG_01_base_F { scope = 1; };
class O_GMG_01_F: GMG_01_base_F { scope = 1; };
class I_GMG_01_F: GMG_01_base_F { scope = 1; };
class B_GMG_01_high_F: GMG_01_high_base_F { scope = 1; };
class O_GMG_01_high_F: GMG_01_high_base_F { scope = 1; };
class I_GMG_01_high_F: GMG_01_high_base_F { scope = 1; };
class B_GMG_01_A_F: GMG_01_A_base_F { scope = 1; };
class O_GMG_01_A_F: GMG_01_A_base_F { scope = 1; };
class I_GMG_01_A_F: GMG_01_A_base_F { scope = 1; };
class B_Mortar_01_F: Mortar_01_base_F { scope = 1; };
class O_Mortar_01_F: Mortar_01_base_F { scope = 1; };
class I_Mortar_01_F: Mortar_01_base_F { scope = 1; };
class B_G_Mortar_01_F: I_G_Mortar_01_F { scope = 1; };
class B_Static_Designator_01_F: Static_Designator_01_base_F { scope = 1; };
class O_Static_Designator_02_F: Static_Designator_02_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_ammo_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_bench_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_box_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_covered_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_fuel_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_medevac_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class Land_Pod_Heli_Transport_04_repair_F: Pod_Heli_Transport_04_base_F { scope = 1; };
class B_static_AA_F: AA_01_base_F { scope = 1; };
class O_static_AA_F: AA_01_base_F { scope = 1; };
class I_static_AA_F: AA_01_base_F { scope = 1; };
class B_static_AT_F: AT_01_base_F { scope = 1; };
class O_static_AT_F: AT_01_base_F { scope = 1; };
class I_static_AT_F: AT_01_base_F { scope = 1; };
