class B_APC_Tracked_01_base_F;
class O_APC_Tracked_02_base_F;
class I_APC_tracked_03_base_F;
class I_MBT_03_base_F;
class B_MBT_01_base_F;
class B_MBT_01_arty_base_F;
class B_MBT_01_mlrs_base_F;
class O_MBT_02_base_F;
class O_MBT_02_arty_base_F;
class B_APC_Tracked_01_rcws_F: B_APC_Tracked_01_base_F { scope = 1; };
class B_APC_Tracked_01_CRV_F: B_APC_Tracked_01_base_F { scope = 1; };
class B_APC_Tracked_01_AA_F: B_APC_Tracked_01_base_F { scope = 1; };
class O_APC_Tracked_02_cannon_F: O_APC_Tracked_02_base_F { scope = 1; };
class O_APC_Tracked_02_AA_F: O_APC_Tracked_02_base_F { scope = 1; };
class I_APC_tracked_03_cannon_F: I_APC_tracked_03_base_F { scope = 1; };
class I_MBT_03_cannon_F: I_MBT_03_base_F { scope = 1; };
class B_MBT_01_cannon_F: B_MBT_01_base_F { scope = 1; };
class B_MBT_01_arty_F: B_MBT_01_arty_base_F { scope = 1; };
class B_MBT_01_mlrs_F: B_MBT_01_mlrs_base_F { scope = 1; };
class O_MBT_02_cannon_F: O_MBT_02_base_F { scope = 1; };
class O_MBT_02_arty_F: O_MBT_02_arty_base_F { scope = 1; };
class B_MBT_01_TUSK_F: B_MBT_01_cannon_F { scope = 1; };
