// config.bin - 16:56:33 02/19/15, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class CW_9LINERS_AND_NOTEPAD {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {"CBA_Extended_EventHandlers", CBA_MAIN};
		author = "Chief Wiggum";
	};
};

class cw_9liner_medv_button {
	access = 0;
	type = 1;
	text = "";
	colorText[] = {1, 1, 1, 1};
	colorDisabled[] = {0, 0, 0, 0};
	colorBackground[] = {0, 0, 0, 0};
	colorBackgroundDisabled[] = {0, 0, 0, 0};
	colorBackgroundActive[] = {0, 0, 0, 0};
	colorFocused[] = {0, 0, 0, 0};
	colorShadow[] = {0, 0, 0, 0};
	colorBorder[] = {0, 0, 0, 0};
	soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
	soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
	soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
	soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
	style = 2;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	shadow = 0;
	font = "puristaMedium";
	sizeEx = 0.03921;
	offsetX = 0.003;
	offsetY = 0.003;
	offsetPressedX = 0.002;
	offsetPressedY = 0.002;
	borderSize = 0;
};

class cw_9liner_medv_edit {
	access = 0;
	type = 2;
	style = 528;
	x = 0;
	y = 0;
	h = 0.04;
	w = 0.2;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {0, 0, 0, 1};
	colorSelection[] = {1, 1, 1, 0.25};
	colorDisabled[] = {1, 1, 1, 0.5};
	font = "TahomaB";
	sizeEx = 0.04;
	autocomplete = "";
	text = "";
	size = 0.2;
	shadow = 1;
};

class cw_9liner_medv_picture {
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class cw_9liner_medv_picture_cross {
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "\cw_nineliner_and_notepad\Data\CW_9Liner_Medivac\Images\cross.paa";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class CW_9LINER_MEDEVAC {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_9liner_medv_background : cw_9liner_medv_picture {
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_9Liner_Medivac\Images\9liner_medevac.paa";
			x = "-0.0213542 * safezoneW + safezoneX";
			y = "0.247099 * safezoneH + safezoneY";
			w = "0.4125 * safezoneW";
			h = "0.747708 * safezoneH";
			moving = 1;
		};
		
		class cw_9liner_medevac_edit_line1 : cw_9liner_medv_edit {
			idc = 1400;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.34606 * safezoneH + safezoneY";
			w = "0.189062 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line2 : cw_9liner_medv_edit {
			idc = 1401;
			x = "0.173438 * safezoneW + safezoneX";
			y = "0.390043 * safezoneH + safezoneY";
			w = "0.160417 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3 : cw_9liner_medv_edit {
			idc = 1402;
			x = "0.161979 * safezoneW + safezoneX";
			y = "0.434026 * safezoneH + safezoneY";
			w = "0.171875 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line4 : cw_9liner_medv_edit {
			idc = 1403;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.489004 * safezoneH + safezoneY";
			w = "0.189062 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line5 : cw_9liner_medv_edit {
			idc = 1404;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.554979 * safezoneH + safezoneY";
			w = "0.20625 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line6 : cw_9liner_medv_edit {
			idc = 1405;
			x = "0.133333 * safezoneW + safezoneX";
			y = "0.620953 * safezoneH + safezoneY";
			w = "0.200521 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line7 : cw_9liner_medv_edit {
			idc = 1406;
			x = "0.15625 * safezoneW + safezoneX";
			y = "0.719914 * safezoneH + safezoneY";
			w = "0.177604 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line8 : cw_9liner_medv_edit {
			idc = 1407;
			x = "0.150521 * safezoneW + safezoneX";
			y = "0.785888 * safezoneH + safezoneY";
			w = "0.183333 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medv_edit_1408 : cw_9liner_medv_edit {
			idc = 1408;
			x = "0.127604 * safezoneW + safezoneX";
			y = "0.840867 * safezoneH + safezoneY";
			w = "0.200521 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2800;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2801;
			x = "0.104688 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3_cross_picture3 : cw_9liner_medv_picture_cross {
			idc = 2802;
			x = "0.173438 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3_cross_picture4 : cw_9liner_medv_picture_cross {
			idc = 2803;
			x = "0.219271 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3_cross_picture5 : cw_9liner_medv_picture_cross {
			idc = 2804;
			x = "0.270833 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line4_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2805;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line4_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2806;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line4_cross_picture3 : cw_9liner_medv_picture_cross {
			idc = 2807;
			x = "0.179167 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line4_cross_picture4 : cw_9liner_medv_picture_cross {
			idc = 2808;
			x = "0.276563 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line5_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2809;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.57697 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line5_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2810;
			x = "0.116146 * safezoneW + safezoneX";
			y = "0.57697 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line6_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2811;
			x = "0.0588542 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line6_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2812;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line6_cross_picture3 : cw_9liner_medv_picture_cross {
			idc = 2813;
			x = "0.173438 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line6_cross_picture4 : cw_9liner_medv_picture_cross {
			idc = 2814;
			x = "0.247917 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line7_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2815;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line7_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2816;
			x = "0.104688 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line7_cross_picture3 : cw_9liner_medv_picture_cross {
			idc = 2817;
			x = "0.179167 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line7_cross_picture4 : cw_9liner_medv_picture_cross {
			idc = 2818;
			x = "0.242188 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line7_cross_picture5 : cw_9liner_medv_picture_cross {
			idc = 2819;
			x = "0.29375 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line8_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2820;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line8_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2821;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line8_cross_picture3 : cw_9liner_medv_picture_cross {
			idc = 2822;
			x = "0.161979 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line8_cross_picture4 : cw_9liner_medv_picture_cross {
			idc = 2823;
			x = "0.225 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line8_cross_picture5 : cw_9liner_medv_picture_cross {
			idc = 2824;
			x = "0.29375 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line9_cross_picture1 : cw_9liner_medv_picture_cross {
			idc = 2825;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.88485 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line9_cross_picture2 : cw_9liner_medv_picture_cross {
			idc = 2826;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.88485 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line9_cross_picture3 : cw_9liner_medv_picture_cross {
			idc = 2827;
			x = "0.161979 * safezoneW + safezoneX";
			y = "0.88485 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
		};
		
		class cw_9liner_medevac_edit_line3_cross_button1 : cw_9liner_medv_button {
			idc = 3800;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2800] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line3_cross_button2 : cw_9liner_medv_button {
			idc = 3801;
			x = "0.104688 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2801] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line3_cross_button3 : cw_9liner_medv_button {
			idc = 3802;
			x = "0.173438 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2802] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line3_cross_button4 : cw_9liner_medv_button {
			idc = 3803;
			x = "0.219271 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2803] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line3_cross_button5 : cw_9liner_medv_button {
			idc = 3804;
			x = "0.270833 * safezoneW + safezoneX";
			y = "0.456017 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2804] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line4_cross_button1 : cw_9liner_medv_button {
			idc = 3805;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2805] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line4_cross_button2 : cw_9liner_medv_button {
			idc = 3806;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2806] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line4_cross_button3 : cw_9liner_medv_button {
			idc = 3807;
			x = "0.179167 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2807] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line4_cross_button4 : cw_9liner_medv_button {
			idc = 3808;
			x = "0.276563 * safezoneW + safezoneX";
			y = "0.510996 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2808] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line5_cross_button1 : cw_9liner_medv_button {
			idc = 3809;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.57697 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2809] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line5_cross_button2 : cw_9liner_medv_button {
			idc = 3810;
			x = "0.116146 * safezoneW + safezoneX";
			y = "0.57697 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2810] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line6_cross_button1 : cw_9liner_medv_button {
			idc = 3811;
			x = "0.0588542 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2811] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line6_cross_button2 : cw_9liner_medv_button {
			idc = 2812;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2812] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line6_cross_button3 : cw_9liner_medv_button {
			idc = 3813;
			x = "0.173438 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2813] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line6_cross_button4 : cw_9liner_medv_button {
			idc = 3814;
			x = "0.247917 * safezoneW + safezoneX";
			y = "0.65394 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2814] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line7_cross_button1 : cw_9liner_medv_button {
			idc = 3815;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2815] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line7_cross_button2 : cw_9liner_medv_button {
			idc = 3816;
			x = "0.104688 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2816] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line7_cross_button3 : cw_9liner_medv_button {
			idc = 3817;
			x = "0.179167 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2817] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line7_cross_button4 : cw_9liner_medv_button {
			idc = 3818;
			x = "0.242188 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2818] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line7_cross_button5 : cw_9liner_medv_button {
			idc = 3819;
			x = "0.29375 * safezoneW + safezoneX";
			y = "0.741906 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2819] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line8_cross_button1 : cw_9liner_medv_button {
			idc = 3820;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2820] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line8_cross_button2 : cw_9liner_medv_button {
			idc = 3821;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2821] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line8_cross_button3 : cw_9liner_medv_button {
			idc = 3822;
			x = "0.161979 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2822] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line8_cross_button4 : cw_9liner_medv_button {
			idc = 3823;
			x = "0.225 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2823] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line8_cross_button5 : cw_9liner_medv_button {
			idc = 3824;
			x = "0.29375 * safezoneW + safezoneX";
			y = "0.796884 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2824] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line9_cross_button1 : cw_9liner_medv_button {
			idc = 3825;
			x = "0.0645833 * safezoneW + safezoneX";
			y = "0.88485 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2825] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line9_cross_button2 : cw_9liner_medv_button {
			idc = 3826;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.88485 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2826] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_edit_line9_cross_button3 : cw_9liner_medv_button {
			idc = 3827;
			x = "0.161979 * safezoneW + safezoneX";
			y = "0.88485 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "[2827] call cw_9liner_medv_fnc_show_or_hide_cross;";
		};
		
		class cw_9liner_medevac_bttn_nextPage : cw_9liner_medv_button {
			idc = 1600;
			x = "0.305208 * safezoneW + safezoneX";
			y = "0.928833 * safezoneH + safezoneY";
			w = "0.0229167 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_9liner_medv_fnc_nextPage";
		};
		
		class cw_9liner_medevac_bttn_previousPage : cw_9liner_medv_button {
			idc = 1601;
			x = "0.0302083 * safezoneW + safezoneX";
			y = "0.928833 * safezoneH + safezoneY";
			w = "0.0229167 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_9liner_medv_fnc_previousPage;";
		};
		
		class cw_9liner_medivac_bttn_clearthis : cw_9liner_medv_button {
			idc = 1602;
			x = "0.0817708 * safezoneW + safezoneX";
			y = "0.928833 * safezoneH + safezoneY";
			w = "0.0572917 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_9liner_medv_fnc_clearPage;";
		};
		
		class cw_9liner_medivac_bttn_clearall : cw_9liner_medv_button {
			idc = 1603;
			x = "0.225 * safezoneW + safezoneX";
			y = "0.928833 * safezoneH + safezoneY";
			w = "0.0515625 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_9liner_medv_fnc_clearall;";
		};
		
		class cw_9liner_medivac_bttn_safe : cw_9liner_medv_button {
			idc = 1604;
			x = "0.173438 * safezoneW + safezoneX";
			y = "0.928833 * safezoneH + safezoneY";
			w = "0.0229167 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_9liner_medv_fnc_savePage;";
		};
	};
};

class cw_9liner_cas_button {
	access = 0;
	type = 1;
	text = "";
	colorText[] = {1, 1, 1, 1};
	colorDisabled[] = {0, 0, 0, 0};
	colorBackground[] = {0, 0, 0, 0};
	colorBackgroundDisabled[] = {0, 0, 0, 0};
	colorBackgroundActive[] = {0, 0, 0, 0};
	colorFocused[] = {0, 0, 0, 0};
	colorShadow[] = {0, 0, 0, 0};
	colorBorder[] = {0, 0, 0, 0};
	soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
	soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
	soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
	soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
	style = 2;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	shadow = 0;
	font = "puristaMedium";
	sizeEx = 0.03921;
	offsetX = 0.003;
	offsetY = 0.003;
	offsetPressedX = 0.002;
	offsetPressedY = 0.002;
	borderSize = 0;
};

class cw_9liner_cas_edit {
	access = 0;
	type = 2;
	style = 528;
	x = 0;
	y = 0;
	h = 0.04;
	w = 0.2;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {0, 0, 0, 1};
	colorSelection[] = {0, 0, 0, 0.25};
	colorDisabled[] = {0, 0, 0, 0};
	font = "TahomaB";
	sizeEx = "0.015 / (getResolution select 5)";
	autocomplete = "";
	text = "";
	size = 0.2;
	shadow = 1;
};

class cw_9liner_cas_picture {
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class CW_9LINER_CAS {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_9liner_cas_background : cw_9liner_cas_picture {
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_9Liner_CAS\Images\9liner_cas.paa";
			x = "-0.0786458 * safezoneW + safezoneX";
			y = "0.26909 * safezoneH + safezoneY";
			w = "0.452604 * safezoneW";
			h = "0.725717 * safezoneH";
			moving = 1;
		};
		
		class cw_9liner_cas_line0_1 : cw_9liner_cas_edit {
			idc = 1400;
			x = "0.110417 * safezoneW + safezoneX";
			y = "0.384047 * safezoneH + safezoneY";
			w = "0.0802083 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line0_2 : cw_9liner_cas_edit {
			idc = 1401;
			x = "0.213542 * safezoneW + safezoneX";
			y = "0.384047 * safezoneH + safezoneY";
			w = "0.0630208 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line0_3 : cw_9liner_cas_edit {
			idc = 1420;
			x = "0.0760417 * safezoneW + safezoneX";
			y = "0.401039 * safezoneH + safezoneY";
			w = "0.0171875 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line1 : cw_9liner_cas_edit {
			idc = 1402;
			x = "0.0875 * safezoneW + safezoneX";
			y = "0.42603 * safezoneH + safezoneY";
			w = "0.189062 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line2 : cw_9liner_cas_edit {
			idc = 1403;
			x = "0.0932292 * safezoneW + safezoneX";
			y = "0.447021 * safezoneH + safezoneY";
			w = "0.154687 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line2_2 : cw_9liner_cas_edit {
			idc = 1404;
			x = "0.0875 * safezoneW + safezoneX";
			y = "0.483009 * safezoneH + safezoneY";
			w = "0.160417 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line3 : cw_9liner_cas_edit {
			idc = 1405;
			x = "0.0982292 * safezoneW + safezoneX";
			y = "0.503 * safezoneH + safezoneY";
			w = "0.183333 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line4 : cw_9liner_cas_edit {
			idc = 1406;
			x = "0.116146 * safezoneW + safezoneX";
			y = "0.546983 * safezoneH + safezoneY";
			w = "0.120313 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line5 : cw_9liner_cas_edit {
			idc = 1407;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.560979 * safezoneH + safezoneY";
			w = "0.154687 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line6 : cw_9liner_cas_edit {
			idc = 1408;
			x = "0.116146 * safezoneW + safezoneX";
			y = "0.58197 * safezoneH + safezoneY";
			w = "0.160417 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line7_1 : cw_9liner_cas_edit {
			idc = 1409;
			x = "0.0989583 * safezoneW + safezoneX";
			y = "0.624953 * safezoneH + safezoneY";
			w = "0.0859375 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line7_2 : cw_9liner_cas_edit {
			idc = 1410;
			x = "0.207813 * safezoneW + safezoneX";
			y = "0.624953 * safezoneH + safezoneY";
			w = "0.0744792 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line7_3 : cw_9liner_cas_edit {
			idc = 1411;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.65994 * safezoneH + safezoneY";
			w = "0.0630208 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line8 : cw_9liner_cas_edit {
			idc = 1412;
			x = "0.133333 * safezoneW + safezoneX";
			y = "0.680931 * safezoneH + safezoneY";
			w = "0.143229 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line8_2 : cw_9liner_cas_edit {
			idc = 1413;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.701923 * safezoneH + safezoneY";
			w = "0.154687 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line9 : cw_9liner_cas_edit {
			idc = 1414;
			x = "0.0875 * safezoneW + safezoneX";
			y = "0.724914 * safezoneH + safezoneY";
			w = "0.189062 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line10 : cw_9liner_cas_edit {
			idc = 1415;
			x = "0.0588542 * safezoneW + safezoneX";
			y = "0.768897 * safezoneH + safezoneY";
			w = "0.229167 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line11 : cw_9liner_cas_edit {
			idc = 1416;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.801884 * safezoneH + safezoneY";
			w = "0.131771 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line12 : cw_9liner_cas_edit {
			idc = 1417;
			x = "0.121875 * safezoneW + safezoneX";
			y = "0.913841 * safezoneH + safezoneY";
			w = "0.131771 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line13_1 : cw_9liner_cas_edit {
			idc = 1418;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.933833 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_line13_2 : cw_9liner_cas_edit {
			idc = 1419;
			x = "0.196354 * safezoneW + safezoneX";
			y = "0.933833 * safezoneH + safezoneY";
			w = "0.0458333 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_9liner_cas_bttn_clearThis : cw_9liner_cas_button {
			idc = 1600;
			x = "0.0780417 * safezoneW + safezoneX";
			y = "0.274 * safezoneH + safezoneY";
			w = "0.0610208 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_9liner_cas_fnc_clearPage;";
		};
		
		class cw_9liner_cas_bttn_clearAll : cw_9liner_cas_button {
			idc = 1601;
			x = "0.196354 * safezoneW + safezoneX";
			y = "0.274 * safezoneH + safezoneY";
			w = "0.0488333 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_9liner_cas_fnc_clearall;";
		};
		
		class cw_9liner_cas_bttn_save : cw_9liner_cas_button {
			idc = 1602;
			x = "0.152521 * safezoneW + safezoneX";
			y = "0.273 * safezoneH + safezoneY";
			w = "0.0286458 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_9liner_cas_fnc_savePage;";
		};
		
		class cw_9liner_cas_bttn_nextPage : cw_9liner_cas_button {
			idc = 1603;
			x = "0.253646 * safezoneW + safezoneX";
			y = "0.273 * safezoneH + safezoneY";
			w = "0.0401042 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_9liner_cas_fnc_nextPage;";
		};
		
		class cw_9liner_cas_bttn_previousPage : cw_9liner_cas_button {
			idc = 1604;
			x = "0.0359375 * safezoneW + safezoneX";
			y = "0.273 * safezoneH + safezoneY";
			w = "0.039 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_9liner_cas_fnc_previousPage;";
		};
	};
};

class cw_noteblock_text {
	access = 0;
	type = 0;
	idc = -1;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 0.7};
	text = "";
	fixedWidth = 0;
	x = 0;
	y = 0;
	h = 0.037;
	w = 0.3;
	style = 0;
	shadow = 0;
	font = "puristaMedium";
	SizeEx = 0.03921;
};

class cw_noteblock_button {
	access = 0;
	type = 1;
	text = "";
	colorText[] = {1, 1, 1, 1};
	colorDisabled[] = {0, 0, 0, 0};
	colorBackground[] = {0, 0, 0, 0};
	colorBackgroundDisabled[] = {0, 0, 0, 0};
	colorBackgroundActive[] = {0, 0, 0, 0};
	colorFocused[] = {0, 0, 0, 0};
	colorShadow[] = {0, 0, 0, 0};
	colorBorder[] = {0, 0, 0, 0};
	soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
	soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
	soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
	soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
	style = 2;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	shadow = 0;
	font = "puristaMedium";
	sizeEx = 0.03921;
	offsetX = 0.003;
	offsetY = 0.003;
	offsetPressedX = 0.002;
	offsetPressedY = 0.002;
	borderSize = 0;
};

class cw_noteblock_edit {
	access = 0;
	type = 2;
	style = 528;
	x = 0;
	y = 0;
	h = 0.04;
	w = 0.2;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {0, 0, 0, 1};
	colorSelection[] = {1, 1, 1, 0.25};
	colorDisabled[] = {1, 1, 1, 0.5};
	font = "puristaMedium";
	sizeEx = 0.04;
	autocomplete = "";
	text = "";
	size = 0.2;
	shadow = 1;
};

class cw_noteblock_picture {
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class CW_NOTEBLOCK {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_noteblock_background : cw_noteblock_picture {
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_Noteblock\Images\noteblock.paa";
			x = "-0.0557292 * safezoneW + safezoneX";
			y = "0.26909 * safezoneH + safezoneY";
			w = "0.48125 * safezoneW";
			h = "0.747708 * safezoneH";
			moving = 1;
		};
		
		class cw_noteblock_edit : cw_noteblock_edit {
			idc = 1400;
			x = "0.0416667 * safezoneW + safezoneX";
			y = "0.307 * safezoneH + safezoneY";
			w = "0.303646 * safezoneW";
			h = "0.637751 * safezoneH";
			moving = 1;
		};
		
		class cw_noteblock_bttn_nextPage : cw_noteblock_button {
			idc = 1600;
			x = "0.310937 * safezoneW + safezoneX";
			y = "0.291081 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_noteblock_fnc_nextPage;";
		};
		
		class cw_noteblock_bttn_previousPage : cw_noteblock_button {
			idc = 1601;
			x = "0.0416667 * safezoneW + safezoneX";
			y = "0.291081 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0219914 * safezoneH";
			action = "call cw_noteblock_fnc_previousPage;";
		};
		
		class cw_noteblock_bttn_save : cw_noteblock_button {
			idc = 1602;
			x = "0.3479 * safezoneW + safezoneX";
			y = "0.373 * safezoneH + safezoneY";
			w = "0.019 * safezoneW";
			h = "0.047 * safezoneH";
			action = "call cw_noteblock_fnc_savePage;";
		};
		
		class cw_noteblock_bttn_clearpage : cw_noteblock_button {
			idc = 1603;
			x = "0.3479 * safezoneW + safezoneX";
			y = "0.65 * safezoneH + safezoneY";
			w = "0.0155 * safezoneW";
			h = "0.054 * safezoneH";
			action = "call cw_noteblock_fnc_clearPage;";
		};
		
		class cw_noteblock_bttn_clearall : cw_noteblock_button {
			idc = 1604;
			x = "0.3479 * safezoneW + safezoneX";
			y = "0.788 * safezoneH + safezoneY";
			w = "0.015 * safezoneW";
			h = "0.043 * safezoneH";
			action = "call cw_noteblock_fnc_clearBlock;";
		};
		
		class cw_noteblock_bttn_close : cw_noteblock_button {
			idc = 1605;
			x = "0.3479 * safezoneW + safezoneX";
			y = "0.931 * safezoneH + safezoneY";
			w = "0.016 * safezoneW";
			h = "0.045 * safezoneH";
			action = "closeDialog 0;";
		};
	};
};

class cw_table82_text
{
   access = 0;
   type = 0;
   idc = -1;
   colorBackground[] = {0,0,0,0};
   colorText[] = {1,1,1,0.7};
   text = "";
   fixedWidth = 0;
   x = 0;
   y = 0;
   h = 0.037;
   w = 0.3;
   style = ST_LEFT;
   shadow = 0;
   font = "puristaMedium";
   SizeEx = 0.03921;
};
class cw_table82_button
{
   access = 0;
   type = 1;
   text = "";
   colorText[] = {1,1,1,1};
   colorDisabled[] = {0,0,0,0};
   colorBackground[] = {0,0,0,0};
   colorBackgroundDisabled[] = {0,0,0,0};
   colorBackgroundActive[] = {0,0,0,0};
   colorFocused[] = {0,0,0,0};
   colorShadow[] = {0,0,0,0};
   colorBorder[] = {0,0,0,0};
   soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter",0.09,1};
   soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush",0.09,1};
   soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick",0.09,1};
   soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape",0.09,1};
   style = 2;
   x = 0;
   y = 0;
   w = 0.095589;
   h = 0.039216;
   shadow = 0;
   font = "puristaMedium";
   sizeEx = 0.03921;
   offsetX = 0.003;
   offsetY = 0.003;
   offsetPressedX = 0.002;
   offsetPressedY = 0.002;
   borderSize = 0;
};
class cw_table82_edit
{
	access = 0; 
	type = CT_EDIT; 
	style = 528; 
	x = 0; 
	y = 0; 
	h = 0.04; 
	w = 0.2; 
	colorBackground[] = {0,0,0,0}; 
	colorText[] = {0,0,0,1}; 
	colorSelection[] = {1,1,1,0.25}; 
	colorDisabled[] = {1, 1, 1, 0.500000};
	font = "TahomaB"; 
	sizeEx = 0.04; 
	autocomplete = ""; 
	text = "";
	size = 0.2; 
	shadow = 1;
};
class cw_table82_picture
{
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0,0,0,0};
	colorText[] = {1,1,1,1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};


class CW_TABLE82 {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_table82_background: cw_table82_picture
		{
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_Mort82mm\Images\noteblock.paa";
			x = -0.0557292 * safezoneW + safezoneX;
			y = 0.26909 * safezoneH + safezoneY;
			w = 0.48125 * safezoneW;
			h = 0.747708 * safezoneH;
			moving = 1;
		};
		
	};
};

class cw_table82_252_text
{
   access = 0;
   type = 0;
   idc = -1;
   colorBackground[] = {0,0,0,0};
   colorText[] = {1,1,1,0.7};
   text = "";
   fixedWidth = 0;
   x = 0;
   y = 0;
   h = 0.037;
   w = 0.3;
   style = ST_LEFT;
   shadow = 0;
   font = "puristaMedium";
   SizeEx = 0.03921;
};
class cw_table82_252_button
{
   access = 0;
   type = 1;
   text = "";
   colorText[] = {1,1,1,1};
   colorDisabled[] = {0,0,0,0};
   colorBackground[] = {0,0,0,0};
   colorBackgroundDisabled[] = {0,0,0,0};
   colorBackgroundActive[] = {0,0,0,0};
   colorFocused[] = {0,0,0,0};
   colorShadow[] = {0,0,0,0};
   colorBorder[] = {0,0,0,0};
   soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter",0.09,1};
   soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush",0.09,1};
   soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick",0.09,1};
   soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape",0.09,1};
   style = 2;
   x = 0;
   y = 0;
   w = 0.095589;
   h = 0.039216;
   shadow = 0;
   font = "puristaMedium";
   sizeEx = 0.03921;
   offsetX = 0.003;
   offsetY = 0.003;
   offsetPressedX = 0.002;
   offsetPressedY = 0.002;
   borderSize = 0;
};
class cw_table82_252_edit
{
	access = 0; 
	type = CT_EDIT; 
	style = 528; 
	x = 0; 
	y = 0; 
	h = 0.04; 
	w = 0.2; 
	colorBackground[] = {0,0,0,0}; 
	colorText[] = {0,0,0,1}; 
	colorSelection[] = {1,1,1,0.25}; 
	colorDisabled[] = {1, 1, 1, 0.500000};
	font = "TahomaB"; 
	sizeEx = 0.04; 
	autocomplete = ""; 
	text = "";
	size = 0.2; 
	shadow = 1;
};
class cw_table82_252_picture
{
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0,0,0,0};
	colorText[] = {1,1,1,1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class CW_TABLE82_252
{
	idd = -1;
	movingenable = true;
	onUnload = "hint """"";
	
	class Controls
	{
		class cw_table82_252_background: cw_table82_252_picture
		{
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_Mort82_252mm\Images\noteblock.paa";
			x = -0.0557292 * safezoneW + safezoneX;
			y = 0.26909 * safezoneH + safezoneY;
			w = 0.48125 * safezoneW;
			h = 0.747708 * safezoneH;
			moving = 1;
		};
	};
};

class cw_tableags_text
{
   access = 0;
   type = 0;
   idc = -1;
   colorBackground[] = {0,0,0,0};
   colorText[] = {1,1,1,0.7};
   text = "";
   fixedWidth = 0;
   x = 0;
   y = 0;
   h = 0.037;
   w = 0.3;
   style = ST_LEFT;
   shadow = 0;
   font = "puristaMedium";
   SizeEx = 0.03921;
};
class cw_tableags_button
{
   access = 0;
   type = 1;
   text = "";
   colorText[] = {1,1,1,1};
   colorDisabled[] = {0,0,0,0};
   colorBackground[] = {0,0,0,0};
   colorBackgroundDisabled[] = {0,0,0,0};
   colorBackgroundActive[] = {0,0,0,0};
   colorFocused[] = {0,0,0,0};
   colorShadow[] = {0,0,0,0};
   colorBorder[] = {0,0,0,0};
   soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter",0.09,1};
   soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush",0.09,1};
   soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick",0.09,1};
   soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape",0.09,1};
   style = 2;
   x = 0;
   y = 0;
   w = 0.095589;
   h = 0.039216;
   shadow = 0;
   font = "puristaMedium";
   sizeEx = 0.03921;
   offsetX = 0.003;
   offsetY = 0.003;
   offsetPressedX = 0.002;
   offsetPressedY = 0.002;
   borderSize = 0;
};
class cw_tableags_edit
{
	access = 0; 
	type = CT_EDIT; 
	style = 528; 
	x = 0; 
	y = 0; 
	h = 0.04; 
	w = 0.2; 
	colorBackground[] = {0,0,0,0}; 
	colorText[] = {0,0,0,1}; 
	colorSelection[] = {1,1,1,0.25}; 
	colorDisabled[] = {1, 1, 1, 0.500000};
	font = "TahomaB"; 
	sizeEx = 0.04; 
	autocomplete = ""; 
	text = "";
	size = 0.2; 
	shadow = 1;
};
class cw_tableags_picture
{
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0,0,0,0};
	colorText[] = {1,1,1,1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};


class CW_TABLEAGS {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_tableags_background: cw_tableags_picture
		{
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_ags\Images\noteblock.paa";
			x = -0.0557292 * safezoneW + safezoneX;
			y = 0.26909 * safezoneH + safezoneY;
			w = 0.48125 * safezoneW;
			h = 0.747708 * safezoneH;
			moving = 1;
		};
		
	};
};

class cw_5liner_gcff_button {
	access = 0;
	type = 1;
	text = "";
	colorText[] = {1, 1, 1, 1};
	colorDisabled[] = {0, 0, 0, 0};
	colorBackground[] = {0, 0, 0, 0};
	colorBackgroundDisabled[] = {0, 0, 0, 0};
	colorBackgroundActive[] = {0, 0, 0, 0};
	colorFocused[] = {0, 0, 0, 0};
	colorShadow[] = {0, 0, 0, 0};
	colorBorder[] = {0, 0, 0, 0};
	soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
	soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
	soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
	soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
	style = 2;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	shadow = 0;
	font = "puristaMedium";
	sizeEx = 0.03921;
	offsetX = 0.003;
	offsetY = 0.003;
	offsetPressedX = 0.002;
	offsetPressedY = 0.002;
	borderSize = 0;
};

class cw_5liner_gcff_edit {
	access = 0;
	type = 2;
	style = 528;
	x = 0;
	y = 0;
	h = 0.04;
	w = 0.2;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {0, 0, 0, 1};
	colorSelection[] = {0, 0, 0, 0.25};
	colorDisabled[] = {0, 0, 0, 0};
	font = "TahomaB";
	sizeEx = "0.015 / (getResolution select 5)";
	autocomplete = "";
	text = "";
	size = 0.2;
	shadow = 1;
};

class cw_5liner_gcff_picture {
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class CW_GUNSHIP_CALL_FOR_FIRE {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_gcff_background : cw_5liner_gcff_picture {
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_GunshipCallForFire\Images\gunshipcallforfire.paa";
			x = "-0.0843753 * safezoneW + safezoneX";
			y = "0.225107 * safezoneH + safezoneY";
			w = "0.492708 * safezoneW";
			h = "0.802687 * safezoneH";
			moving = 1;
		};
		
		class cw_gcff_line1_1 : cw_5liner_gcff_edit {
			idc = 1400;
			x = "0.139062 * safezoneW + safezoneX";
			y = "0.384047 * safezoneH + safezoneY";
			w = "0.0515625 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_line1_2 : cw_5liner_gcff_edit {
			idc = 1401;
			x = "0.225 * safezoneW + safezoneX";
			y = "0.384047 * safezoneH + safezoneY";
			w = "0.0515625 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_line2_1 : cw_5liner_gcff_edit {
			idc = 1402;
			x = "0.190625 * safezoneW + safezoneX";
			y = "0.439026 * safezoneH + safezoneY";
			w = "0.0802083 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_line2_2 : cw_5liner_gcff_edit {
			idc = 1403;
			x = "0.0703121 * safezoneW + safezoneX";
			y = "0.472013 * safezoneH + safezoneY";
			w = "0.177604 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_line3_1 : cw_5liner_gcff_edit {
			idc = 1404;
			x = "0.104688 * safezoneW + safezoneX";
			y = "0.505 * safezoneH + safezoneY";
			w = "0.131771 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_line4_1 : cw_5liner_gcff_edit {
			idc = 1405;
			x = "0.184896 * safezoneW + safezoneX";
			y = "0.538987 * safezoneH + safezoneY";
			w = "0.0401042 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_line5_1 : cw_5liner_gcff_edit {
			idc = 1406;
			x = "0.0760417 * safezoneW + safezoneX";
			y = "0.570974 * safezoneH + safezoneY";
			w = "0.154687 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_gcff_bttn_previousPage : cw_5liner_gcff_button {
			idc = 1600;
			x = "0.0130208 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_5liner_gcff_fnc_previousPage;";
		};
		
		class cw_gcff_bttn_nextPage : cw_5liner_gcff_button {
			idc = 1601;
			x = "0.276563 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_5liner_gcff_fnc_nextPage;";
		};
		
		class cw_gcff_bttn_clearPage : cw_5liner_gcff_button {
			idc = 1602;
			x = "0.053125 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.0744792 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_5liner_gcff_fnc_clearPage;";
		};
		
		class cw_gcff_bttn_save : cw_5liner_gcff_button {
			idc = 1603;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_5liner_gcff_fnc_savePage;";
		};
		
		class cw_gcff_bttn_clearAll : cw_5liner_gcff_button {
			idc = 1604;
			x = "0.196354 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.06875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_5liner_gcff_fnc_clearall;";
		};
	};
};

class cw_cas_check_in_button {
	access = 0;
	type = 1;
	text = "";
	colorText[] = {1, 1, 1, 1};
	colorDisabled[] = {0, 0, 0, 0};
	colorBackground[] = {0, 0, 0, 0};
	colorBackgroundDisabled[] = {0, 0, 0, 0};
	colorBackgroundActive[] = {0, 0, 0, 0};
	colorFocused[] = {0, 0, 0, 0};
	colorShadow[] = {0, 0, 0, 0};
	colorBorder[] = {0, 0, 0, 0};
	soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
	soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
	soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
	soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
	style = 2;
	x = 0;
	y = 0;
	w = 0.095589;
	h = 0.039216;
	shadow = 0;
	font = "puristaMedium";
	sizeEx = 0.03921;
	offsetX = 0.003;
	offsetY = 0.003;
	offsetPressedX = 0.002;
	offsetPressedY = 0.002;
	borderSize = 0;
};

class cw_cas_check_in_edit {
	access = 0;
	type = 2;
	style = 528;
	x = 0;
	y = 0;
	h = 0.04;
	w = 0.2;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {0, 0, 0, 1};
	colorSelection[] = {0, 0, 0, 0.25};
	colorDisabled[] = {0, 0, 0, 0};
	font = "TahomaB";
	sizeEx = "0.015 / (getResolution select 5)";
	autocomplete = "";
	text = "";
	size = 0.2;
	shadow = 1;
};

class cw_cas_check_in_picture {
	access = 0;
	type = 0;
	idc = -1;
	style = 48;
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	font = "TahomaB";
	sizeEx = 0;
	lineSpacing = 0;
	text = "";
	fixedWidth = 0;
	shadow = 0;
	x = 0;
	y = 0;
	w = 0.2;
	h = 0.15;
};

class CW_CAS_CHECK_IN {
	idd = -1;
	movingenable = "true";
	onUnload = "hint """"";
	
	class Controls {
		class cw_cas_checkIn_background : cw_cas_check_in_picture {
			idc = 1200;
			text = "\cw_nineliner_and_notepad\Data\CW_CAS_Check_In\Images\cas_check_in.paa";
			x = "-0.0843753 * safezoneW + safezoneX";
			y = "0.225107 * safezoneH + safezoneY";
			w = "0.492708 * safezoneW";
			h = "0.802687 * safezoneH";
			moving = 1;
		};
		
		class cw_cas_checkIn_bttn_previousPage : cw_cas_check_in_button {
			idc = 1600;
			x = "0.0130208 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_cas_check_in_fnc_previousPage";
		};
		
		class cw_cas_checkIn_bttn_nextPage : cw_cas_check_in_button {
			idc = 1601;
			x = "0.276563 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_cas_check_in_fnc_nextPage";
		};
		
		class cw_cas_checkIn_clearPage : cw_cas_check_in_button {
			idc = 1602;
			x = "0.053125 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.0744792 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_cas_check_in_fnc_clearPage";
		};
		
		class cw_cas_checkIn_bttn_save : cw_cas_check_in_button {
			idc = 1603;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.034375 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_cas_check_in_fnc_savePage";
		};
		
		class cw_cas_checkIn_bttn_clearAll : cw_cas_check_in_button {
			idc = 1604;
			x = "0.196354 * safezoneW + safezoneX";
			y = "0.950824 * safezoneH + safezoneY";
			w = "0.06875 * safezoneW";
			h = "0.0329871 * safezoneH";
			action = "call cw_cas_check_in_fnc_clearall";
		};
		
		class cw_cas_checkIn_line0_1 : cw_cas_check_in_edit {
			idc = 1400;
			x = "0.0588542 * safezoneW + safezoneX";
			y = "0.412034 * safezoneH + safezoneY";
			w = "0.0916667 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line0_2 : cw_cas_check_in_edit {
			idc = 1401;
			x = "0.179167 * safezoneW + safezoneX";
			y = "0.412034 * safezoneH + safezoneY";
			w = "0.103125 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line1 : cw_cas_check_in_edit {
			idc = 1402;
			x = "0.144792 * safezoneW + safezoneX";
			y = "0.476009 * safezoneH + safezoneY";
			w = "0.143229 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line2 : cw_cas_check_in_edit {
			idc = 1403;
			x = "0.139062 * safezoneW + safezoneX";
			y = "0.5045 * safezoneH + safezoneY";
			w = "0.148958 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line3 : cw_cas_check_in_edit {
			idc = 1404;
			x = "0.116146 * safezoneW + safezoneX";
			y = "0.537987 * safezoneH + safezoneY";
			w = "0.171875 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line4 : cw_cas_check_in_edit {
			idc = 1405;
			x = "0.0760417 * safezoneW + safezoneX";
			y = "0.570974 * safezoneH + safezoneY";
			w = "0.211979 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line5 : cw_cas_check_in_edit {
			idc = 1406;
			x = "0.0932292 * safezoneW + safezoneX";
			y = "0.602961 * safezoneH + safezoneY";
			w = "0.194792 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line6 : cw_cas_check_in_edit {
			idc = 1407;
			x = "0.0416667 * safezoneW + safezoneX";
			y = "0.647944 * safezoneH + safezoneY";
			w = "0.246354 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
		
		class cw_cas_checkIn_line7 : cw_cas_check_in_edit {
			idc = 1408;
			x = "0.0817708 * safezoneW + safezoneX";
			y = "0.679931 * safezoneH + safezoneY";
			w = "0.20625 * safezoneW";
			h = "0.0219914 * safezoneH";
		};
	};
};

class Extended_PostInit_EventHandlers {
	TEST_addscript_PostInit = "call compile preprocessFile '\cw_nineliner_and_notepad\Data\init.sqf'";
};

class CfgWeapons {
	class ItemCore;	// External class reference
	
	class cw_item_9liner_cas : ItemCore {
		scope = 2;
		displayName = "CAS 9Line Cards [20]";
		picture = "\cw_nineliner_and_notepad\Data\UI\cas_nineliner_ca.paa";
		descriptionShort = "20 waterproof CAS 9-Liner cards.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
	
	class cw_item_9liner_medivac : ItemCore {
		scope = 2;
		displayName = "Medivac 9Line Cards [20]";
		picture = "\cw_nineliner_and_notepad\Data\UI\medv_nineliner_ca.paa";
		descriptionShort = "20 waterproof Medivac 9-Liner cards.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
	
	class cw_item_notepad : ItemCore {
		scope = 2;
		displayName = "Notepad";
		picture = "\cw_nineliner_and_notepad\Data\UI\notepad_ca.paa";
		descriptionShort = "A notepad, used to write down notes.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
	class cw_item_table82mm : ItemCore {
		scope = 2;
		displayName = "Podnos 2b14 tables";
		picture = "\cw_nineliner_and_notepad\Data\UI\notepad_ca.paa";
		descriptionShort = "A notepad, used to write down notes.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
	class cw_item_table82mm_252 : ItemCore {
		scope = 2;
		displayName = "M252 tables";
		picture = "\cw_nineliner_and_notepad\Data\UI\notepad_ca.paa";
		descriptionShort = "A notepad, used to write down notes.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};

	class cw_item_tableags : ItemCore {
		scope = 2;
		displayName = "AGS tables";
		picture = "\cw_nineliner_and_notepad\Data\UI\notepad_ca.paa";
		descriptionShort = "A notepad, used to write down notes.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
	
	class cw_item_5liner_gcff : ItemCore {
		scope = 2;
		displayName = "Gunship Call-For-Fire cards [20]";
		picture = "\cw_nineliner_and_notepad\Data\CW_GunshipCallForFire\Images\gunshipcallforfire.paa";
		descriptionShort = "20 waterproof Gunship Call-For-Fire cards.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
	
	class cw_item_cas_check_in_breef : ItemCore {
		scope = 2;
		displayName = "CAS Check-In Breefing cards [20]";
		picture = "\cw_nineliner_and_notepad\Data\CW_CAS_Check_In\Images\cas_check_in.paa";
		descriptionShort = "20 waterproof CAS Check-In Breefing cards.";
		model = "\A3\structures_f\Items\Documents\Map_F.p3d";
		
		class ItemInfo {
			mass = 3;
			type = 201;
		};
	};
};

class CfgVehicles {
	class NATO_Box_Base;	// External class reference
	
	class cw_nineliner_and_notepad_box : NATO_Box_Base {
		scope = 2;
		vehicleClass = "Ammo";
		displayName = "9Liners and Notepads";
		model = "\A3\weapons_F\AmmoBoxes\Supplydrop";
		icon = "iconCrateWpns";
		
		class TransportMagazines {};
		
		class TransportWeapons {};
		
		class TransportItems {
			class cw_item_9liner_cas_XX {
				name = "cw_item_9liner_cas";
				count = 100;
			};
			
			class cw_item_9liner_medivac_XX {
				name = "cw_item_9liner_medivac";
				count = 100;
			};
			
			class cw_item_notepad_XX {
				name = "cw_item_notepad";
				count = 100;
			};
			
			class cw_item_5liner_gcff_XX {
				name = "cw_item_5liner_gcff";
				count = 100;
			};
			class cw_item_cas_check_in_breef_XX {
				name = "cw_item_cas_check_in_breef";
				count = 100;
			};
			class cw_item_table82mm_XX {
				name = "cw_item_table82mm";
				count = 100;
			};
			class cw_item_table82mm_252_XX {
				name = "cw_item_table82mm_252";
				count = 100;
			};

			class cw_item_tableags_XX {
				name = "cw_item_tableags";
				count = 100;
			};


		};
	};
};
