// config.bin - 17:09:21 01/05/15, generated in 0.06 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class mas_vehicleweapons_Core {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.34;
		requiredAddons[] = {"A3_Static_F_Gamma", "A3_CargoPoses_F", "A3_Armor_F_Slammer", "A3_Weapons_F", "A3_Anims_F", "A3_Anims_F_Config_Sdr","HMG_Weapons_St"};
	};
};

class CfgVehicleClasses {
	class mas_ind_stat {
		displayName = "Static(OLD)";
	};
	
	class mas_ind_veh {
		displayName = "Vehicles(OLD)";
	};
};
class Mode_SemiAuto;	// External class reference
class Mode_Burst;	// External class reference


class CfgVehicles {
	class LandVehicle;	// External class reference
	
	class StaticWeapon : LandVehicle {
		class Turrets;	// External class reference
		class MainTurret;	// External class reference
	};
	
	class StaticAAWeapon : StaticWeapon {};

	
};

class CfgFunctions {
	class mas {
		tag = "mas";
		
/*		class functions {
			class D30_Pack {
				file = "\mas_vehicle\scripts\d30_pack.sqf";
				description = "D30 Assembly/Disassembly Anim";
			};
		};*/
	};
};

class CfgMovesBasic {
	class DefaultDie;	// External class reference
	
	class ManActions {
		mas_Stryker_Cargo01 = "mas_Stryker_Cargo01";
		mas_Hilux_Cargo01 = "mas_Hilux_Cargo01";
		mas_DShKM_Gunner = "mas_DShKM_Gunner";
		mas_LowTripod_Gunner = "mas_LowTripod_Gunner";
		mas_LowKORD_Gunner = "mas_LowKORD_Gunner";
		mas_KORD_Gunner = "mas_KORD_Gunner";
		mas_AGS_Gunner = "mas_AGS_Gunner";
		mas_SPG_Gunner = "mas_SPG_Gunner";
		mas_Metis_Gunner = "mas_Metis_Gunner";
		mas_D30_Commander = "mas_D30_Commander";
		mas_D30_Gunner = "mas_D30_Gunner";
		mas_D30_Cargo = "mas_D30_Cargo";
		mas_Mi17_Cargo02 = "mas_Mi17_Cargo02";
		mas_M119_Commander = "mas_M119_Commander";
		mas_M119_Gunner = "mas_M119_Gunner";
		mas_M119_Cargo = "mas_M119_Cargo";
		mas_M2_Gunner = "mas_M2_Gunner";
		mas_TOW_Gunner = "mas_TOW_Gunner";
	};
};

class CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class Crew;	// External class reference
		class mas_KIA_Stryker_Cargo01 : Crew {
			actions = "DeadActions";
			speed = 0.5;
			looped = 0;
			terminal = 1;
			connectTo[] = {"DeadState", 0.1};
			soundEnabled = 0;
			file = "\mas_apc\BMP\anim\KIA_Stryker_Cargo01.rtm";
		};
		
		class mas_Stryker_Cargo01 : Crew {
			file = "\mas_apc\BMP\anim\Stryker_Cargo01_V0.rtm";
			interpolateTo[] = {"mas_KIA_Stryker_Cargo01", 0.1};
			connectTo[] = {"mas_Stryker_Cargo01", 0.1, "mas_Stryker_Cargo01_V1", 0.1, "mas_Stryker_Cargo01_V2", 0.1, "mas_Stryker_Cargo01_V3", 0.1, "mas_Stryker_Cargo01_V4", 0.1};
			equivalentTo = "mas_Stryker_Cargo01";
			variantsAI[] = {"mas_Stryker_Cargo01", 0.6, "mas_Stryker_Cargo01_V1", 0.1, "mas_Stryker_Cargo01_V2", 0.1, "mas_Stryker_Cargo01_V3", 0.1, "mas_Stryker_Cargo01_V4", 0.1};
			variantAfter[] = {5, 10, 20};
			speed = 0.3;
		};
		
		class mas_Stryker_Cargo01_V1 : mas_Stryker_Cargo01 {
			file = "\mas_apc\BMP\anim\Stryker_Cargo01_V1.rtm";
			interpolateTo[] = {"mas_KIA_Stryker_Cargo01", 0.1};
			connectTo[] = {"mas_Stryker_Cargo01", 0.1};
			speed = 0.236;
			variantAfter[] = {4, 4, 4};
		};
		
		class mas_Stryker_Cargo01_V2 : mas_Stryker_Cargo01 {
			file = "\mas_apc\BMP\anim\Stryker_Cargo01_V2.rtm";
			interpolateTo[] = {"mas_KIA_Stryker_Cargo01", 0.1};
			connectTo[] = {"mas_Stryker_Cargo01", 0.1};
			speed = 0.169;
			variantAfter[] = {6, 6, 6};
		};
		
		class mas_Stryker_Cargo01_V3 : mas_Stryker_Cargo01 {
			file = "\mas_apc\BMP\anim\Stryker_Cargo01_V3.rtm";
			interpolateTo[] = {"mas_KIA_Stryker_Cargo01", 0.1};
			connectTo[] = {"mas_Stryker_Cargo01", 0.1};
			speed = 0.197;
			variantAfter[] = {5, 5, 5};
		};
		
		class mas_Stryker_Cargo01_V4 : mas_Stryker_Cargo01 {
			file = "\mas_apc\BMP\anim\Stryker_Cargo01_V4.rtm";
			interpolateTo[] = {"mas_KIA_Stryker_Cargo01", 0.1};
			connectTo[] = {"mas_Stryker_Cargo01", 0.1};
			speed = 0.197;
			variantAfter[] = {5, 5, 5};
		};
		
		class mas_KIA_Hilux_Cargo01 : Crew {
			actions = "DeadActions";
			file = "mas_vehicle\Anim\KIA_Hilux_Cargo01.rtm";
			speed = 0.5;
			looped = 0;
			terminal = 1;
			connectTo[] = {"DeadState", 0.1};
			soundEnabled = 0;
		};
		
		class mas_Hilux_Cargo01 : Crew {
			file = "mas_vehicle\Anim\Hilux_Cargo01.rtm";
			interpolateTo[] = {"mas_KIA_Hilux_Cargo01", 1};
		};
		
		class mas_DShKM_Gunner : Crew {
			file = "mas_vehicle\Anim\DShKM_Gunner.rtm";
			connectTo[] = {"Static_Dead", 1};
			leftHandIKBeg = 1;
			leftHandIKCurve[] = {1};
			leftHandIKEnd = 1;
			rightHandIKCurve[] = {1};
			righHandIKBeg = 1;
			righHandIKEnd = 1;
		};
		
		class mas_LowTripod_Gunner : mas_DShKM_Gunner {
			file = "mas_vehicle\Anim\LowTripod_Gunner.rtm";
		};
		
		class mas_LowKORD_Gunner : mas_DShKM_Gunner {
			file = "mas_vehicle\Anim\sittingGunner.rtm";
			interpolateTo[] = {"mas_KIA_SPG_Gunner", 1};
		};
		
		class mas_KORD_Gunner : mas_DShKM_Gunner {
			file = "mas_vehicle\Anim\standingGunner.rtm";
		};
		
		class mas_AGS_Gunner : Crew {
			file = "mas_vehicle\Anim\AGS_Gunner.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_KIA_SPG_Gunner : DefaultDie {
			actions = "DeadActions";
			file = "\A3\cargoposes_F\Anim\gunner_static_low01_KIA.rtm";
			speed = 0.5;
			looped = 0;
			terminal = 1;
			soundEnabled = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_SPG_Gunner : Crew {
			file = "mas_vehicle\Anim\SPG9_gunner.rtm";
			interpolateTo[] = {"mas_KIA_SPG_Gunner", 1};
		};
		
		class mas_Metis_Gunner : Crew {
			file = "mas_vehicle\Anim\Metis_Gunner.rtm";
			connectTo[] = {"mas_KIA_SPG_Gunner", 0.1};
		};
		
		class mas_KIA_Mi17_Cargo02 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_vehicle\Anim\KIA_Mi17_Cargo02.rtm";
			speed = 1;
			looped = 0;
			terminal = 1;
			soundEnabled = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_Mi17_Cargo02 : Crew {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V0.rtm";
			speed = 0.3;
			equivalentTo = "mas_Mi17_Cargo02";
			connectTo[] = {"mas_Mi17_Cargo02", 0.1, "mas_Mi17_Cargo02_V1", 0.1, "mas_Mi17_Cargo02_V2", 0.1, "mas_Mi17_Cargo02_V3", 0.1, "mas_Mi17_Cargo02_V4", 0.1, "mas_Mi17_Cargo02_V5", 0.1, "mas_Mi17_Cargo02_V6", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantsAI[] = {"mas_Mi17_Cargo02", 0.4, "mas_Mi17_Cargo02_V1", 0.1, "mas_Mi17_Cargo02_V2", 0.1, "mas_Mi17_Cargo02_V3", 0.1, "mas_Mi17_Cargo02_V4", 0.1, "mas_Mi17_Cargo02_V5", 0.1, "mas_Mi17_Cargo02_V6", 0.1};
			variantAfter[] = {5, 10, 20};
		};
		
		class mas_Mi17_Cargo02_V1 : mas_Mi17_Cargo02 {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V1.rtm";
			speed = 0.27;
			connectTo[] = {"mas_Mi17_Cargo02", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantAfter[] = {3.7, 3.7, 3.7};
		};
		
		class mas_Mi17_Cargo02_V2 : mas_Mi17_Cargo02 {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V2.rtm";
			speed = 0.345;
			connectTo[] = {"mas_Mi17_Cargo02", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantAfter[] = {3, 3, 3};
		};
		
		class mas_Mi17_Cargo02_V3 : mas_Mi17_Cargo02 {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V3.rtm";
			speed = 0.2;
			connectTo[] = {"mas_Mi17_Cargo02", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantAfter[] = {5, 5, 5};
		};
		
		class mas_Mi17_Cargo02_V4 : mas_Mi17_Cargo02 {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V4.rtm";
			speed = 0.201;
			connectTo[] = {"mas_Mi17_Cargo02", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantAfter[] = {5, 5, 5};
		};
		
		class mas_Mi17_Cargo02_V5 : mas_Mi17_Cargo02 {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V5.rtm";
			speed = 0.197;
			connectTo[] = {"mas_Mi17_Cargo02", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantAfter[] = {5, 5, 5};
		};
		
		class mas_Mi17_Cargo02_V6 : mas_Mi17_Cargo02 {
			file = "\mas_vehicle\Anim\Mi17_Cargo02_V6.rtm";
			speed = 0.345;
			connectTo[] = {"mas_Mi17_Cargo02", 0.1};
			interpolateTo[] = {"mas_KIA_Mi17_Cargo02", 0.1};
			variantAfter[] = {3, 3, 3};
		};
		
		class mas_D30_Commander : Crew {
			file = "mas_vehicle\Anim\D30_Commander.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_D30_Gunner : Crew {
			file = "mas_vehicle\Anim\D30_Gunner.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_D30_Cargo : Crew {
			file = "mas_vehicle\Anim\D30_Cargo.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_M119_Commander : Crew {
			file = "mas_vehicle\Anim\M119_Commander.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_M119_Gunner : Crew {
			file = "mas_vehicle\Anim\M119_Gunner.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_M119_Cargo : Crew {
			file = "mas_vehicle\Anim\M119_Cargo.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
		
		class mas_M2_Gunner : mas_DShKM_Gunner {
			file = "mas_vehicle\Anim\M2_Gunner.rtm";
		};
		
		class mas_TOW_Gunner : Crew {
			file = "mas_vehicle\Anim\D30_Cargo.rtm";
			connectTo[] = {"Static_Dead", 1};
		};
	};
};
