// config.bin - 17:59:39 01/05/15, generated in 0.04 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

class CfgPatches {
	class mas_cars_LR {
		units[] = {"B_mas_cars_LR_Unarmed", "B_mas_cars_LR_Med", "B_mas_cars_LR_M2", "B_mas_cars_LR_Mk19", "B_mas_cars_LR_TOW", "B_mas_cars_LR_SPG9", "I_mas_cars_LR_soft_Unarmed", "I_mas_cars_LR_soft_Med", "I_mas_cars_LR_soft_M2", "I_mas_cars_LR_soft_Mk19", "I_mas_cars_LR_soft_TOW", "I_mas_cars_LR_soft_SPG9"};
		weapons[] = {};
		requiredVersion = 1.34;
		requiredAddons[] = {"A3_Armor_F", "A3_Soft_F", "mas_vehicleweapons_Core", "A3_Anims_F", "A3_Anims_F_Config_Sdr", "A3_CargoPoses_F"};
	};
};

class CfgMovesBasic {
	class DefaultDie;	// External class reference
	
	class ManActions {
		mas_LR_driver_EP1 = "mas_LR_driver_EP1";
		mas_LR_Cargo01_EP1 = "mas_LR_Cargo01_EP1";
		mas_LR_Cargo02_EP1 = "mas_LR_Cargo02_EP1";
		mas_LR_Cargo03_EP1 = "mas_LR_Cargo03_EP1";
		mas_LR_Cargo04_EP1 = "mas_LR_Cargo04_EP1";
		mas_LR_Cargo05_EP1 = "mas_LR_Cargo05_EP1";
		mas_LR_gunner_EP1 = "mas_LR_gunner_EP1";
		mas_LR_gunner03_EP1 = "mas_LR_gunner03_EP1";
		mas_HMMWV_Gunner03lr = "mas_HMMWV_Gunner03lr";
	};
};

class CfgMovesMaleSdr : CfgMovesBasic {
	class States {
		class Crew;	// External class reference
		class mas_Stryker_Cargo01;	// External class reference
		
		class mas_LR_driver_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_driver";
			interpolateTo[] = {"mas_KIA_LR_driver_EP1", 1};
			speed = 1e+010;
		};
		
		class mas_KIA_LR_driver_EP1 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_cars\lr\Data\Anim\KIA_LR_driver";
			speed = 1e+010;
			terminal = 1;
			soundEnabled = 0;
			looped = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_LR_Cargo01_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_Cargo01";
			interpolateTo[] = {"mas_KIA_LR_Cargo01_EP1", 1};
			speed = 1e+010;
		};
		
		class mas_KIA_LR_Cargo01_EP1 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_cars\lr\Data\Anim\KIA_LR_Cargo01";
			speed = 1e+010;
			terminal = 1;
			soundEnabled = 0;
			looped = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_LR_Cargo02_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_Cargo02";
			interpolateTo[] = {"mas_KIA_LR_Cargo02_EP1", 1};
			speed = 1e+010;
		};
		
		class mas_KIA_LR_Cargo02_EP1 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_cars\lr\Data\Anim\KIA_LR_Cargo02";
			speed = 1e+010;
			terminal = 1;
			soundEnabled = 0;
			looped = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_LR_Cargo03_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_Cargo03";
			interpolateTo[] = {"mas_KIA_LR_Cargo03_EP1", 1};
			speed = 1e+010;
		};
		
		class mas_KIA_LR_Cargo03_EP1 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_cars\lr\Data\Anim\KIA_LR_Cargo03";
			speed = 1e+010;
			terminal = 1;
			soundEnabled = 0;
			looped = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_LR_Cargo04_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_Cargo04";
			interpolateTo[] = {"mas_KIA_LR_Cargo04_EP1", 1};
			speed = 1e+010;
		};
		
		class mas_KIA_LR_Cargo04_EP1 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_cars\lr\Data\Anim\KIA_LR_Cargo04";
			speed = 1e+010;
			terminal = 1;
			soundEnabled = 0;
			looped = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_LR_Cargo05_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_Cargo05";
			interpolateTo[] = {"mas_KIA_LR_Cargo05_EP1", 1};
			speed = 1e+010;
		};
		
		class mas_KIA_LR_Cargo05_EP1 : DefaultDie {
			actions = "DeadActions";
			file = "\mas_cars\lr\Data\Anim\KIA_LR_Cargo05";
			speed = 1e+010;
			terminal = 1;
			soundEnabled = 0;
			looped = 0;
			connectTo[] = {"Unconscious", 0.1};
		};
		
		class mas_LR_gunner_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_gunner";
			connectTo[] = {"mas_Stryker_Cargo01", 1};
			speed = 1e+010;
		};
		
		class mas_LR_gunner03_EP1 : Crew {
			file = "\mas_cars\lr\Data\Anim\LR_gunner03";
			connectTo[] = {"mas_Stryker_Cargo01", 1};
			speed = 1e+010;
		};
		
		class mas_HMMWV_Gunner03lr : Crew {
			file = "\mas_cars\lr\Data\Anim\hmmwv_TOW_gunnerOUT.rtm";
			connectTo[] = {"mas_Stryker_Cargo01", 1};
		};
	};
};
class WeaponFireGun;	// External class reference
class WeaponCloudsGun;	// External class reference
class WeaponFireMGun;	// External class reference
class WeaponCloudsMGun;	// External class reference
class RCWSOptics;	// External class reference

class CfgVehicles {
	class LandVehicle;	// External class reference
	
	class Car : LandVehicle {
		class NewTurret;	// External class reference
	};
	
	class Car_F : Car {
		class AnimationSources;	// External class reference
		
		class Turrets {
			class MainTurret : NewTurret {
				class ViewOptics;	// External class reference
			};
		};
		
		class HitPoints {
			class HitLFWheel;	// External class reference
			class HitLF2Wheel;	// External class reference
			class HitRFWheel;	// External class reference
			class HitRF2Wheel;	// External class reference
			class HitGlass1;	// External class reference
			class HitGlass2;	// External class reference
			class HitGlass3;	// External class reference
			class HitGlass4;	// External class reference
			class HitGlass5;	// External class reference
			class HitGlass6;	// External class reference
		};
	};
	
	class B_mas_cars_LR_BASE : Car_F {
		_generalMacro = "B_mas_cars_LR_BASE";
		scope = 0;
		side = 1;
		faction = BLU_F;
		vehicleClass = "mas_ind_veh";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F", "B_Soldier_F", "B_Soldier_F", "B_Soldier_F", "B_Soldier_F"};
		displayname = "LR Base";
		
		class Library {
			libTextDesc = "Land Rover";
		};
		model = "mas_cars\lr\LR";
		picture = "\mas_cars\lr\data\UI\Picture_lr_CA.paa";
		Icon = "\mas_cars\lr\data\UI\Icon_lr_transport_CA.paa";
		mapSize = 4;
		accuracy = 0.25;
		unitInfoType = "UnitInfoShip";
		driverAction = "mas_LR_Driver_EP1";
		cargoAction[] = {"mas_LR_Cargo01_EP1", "mas_LR_Cargo02_EP1", "mas_LR_Cargo03_EP1", "mas_LR_Cargo05_EP1", "mas_LR_Cargo04_EP1", "mas_LR_Cargo02_EP1", "mas_LR_Cargo03_EP1"};
		threat[] = {0.5, 0.5, 0.1};
		driverLeftHandAnimName = "drivewheel";
		driverRightHandAnimName = "drivewheel";
		antiRollbarForceCoef = 12;
		antiRollbarForceLimit = 10;
		antiRollbarSpeedMin = 20;
		antiRollbarSpeedMax = 50;
		crewVulnerable = 1;
		crewCrashProtection = 0.15;
		weapons[] = {"TruckHorn2"};
		magazines[] = {};
		damperSize = 0.2;
		damperForce = 1;
		damperDamping = 1;
		armor = 70;
		armorStructural = 4;
		damageResistance = 0.00562;
		turnCoef = 2.5;
		steerAheadPlan = 0.2;
		steerAheadSimul = 0.4;
		predictTurnPlan = 0.9;
		predictTurnSimul = 0.5;
		brakeDistance = 1.0;
		terrainCoef = 1.5;
		wheelDamageThreshold = 0.7;
		wheelDestroyThreshold = 0.99;
		wheelDamageRadiusCoef = 0.95;
		wheelDestroyRadiusCoef = 0.45;
		wheelCircumference = 2.51;
		cost = 200000;
		precision = 15;
		armorGlass = 0.5;
		soundServo[] = {"A3\sounds_f\dummysound", "db-40", 1.0, 10};
		soundEnviron[] = {"", 0.562341, 1};
		transportSoldier = 5;
		transportAmmo = 0;
		maxSpeed = 110;
		armorWheels = 0.12;
		soundGear[] = {"", "db-65", 1};
		idleRpm = 800;
		redRpm = 4500;
		brakeIdleSpeed = 1.78;
		fuelCapacity = 250;
		
		class complexGearbox {
			GearboxRatios[] = {"R1", -2.475, "N", 0, "D1", 2.367, "D2", 1.67, "D3", 1.238, "D4", 0.99, "D5", 0.802, "D6", 0.601};
			TransmissionRatios[] = {"High", 6.0};
			gearBoxMode = "auto";
			moveOffGear = 1;
			driveString = "D";
			neutralString = "N";
			reverseString = "R";
		};
		simulation = "carx";
		dampersBumpCoef = 3.0;
		differentialType = "all_limited";
		frontRearSplit = 0.5;
		frontBias = 1.3;
		rearBias = 1.3;
		centreBias = 1.3;
		clutchStrength = 20.0;
		enginePower = 276;
		maxOmega = 471;
		peakTorque = 1253;
		dampingRateFullThrottle = 0.08;
		dampingRateZeroThrottleClutchEngaged = 2.0;
		dampingRateZeroThrottleClutchDisengaged = 0.35;
		torqueCurve[] = {{0.0, 0.15}, {0.25, 0.65}, {0.35, 0.75}, {0.461, 1.0}, {0.6, 0.95}, {0.7, 0.85}, {0.8, 0.75}, {1.0, 0.5}};
		changeGearMinEffectivity[] = {0.95, 0.15, 0.95, 0.95, 0.95, 0.95, 0.95};
		switchTime = 0.31;
		latency = 1.0;
		slingLoadCargoMemoryPoints[] = {"SlingLoadCargo1", "SlingLoadCargo2", "SlingLoadCargo3", "SlingLoadCargo4"};
		cargoProxyIndexes[] = {1, 2, 3, 4, 5};
		
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				body = "mainTurret";
				gun = "mainGun";
				outGunnerMayFire = 1;
				forceHideGunner = 0;
				castGunnerShadow = 1;
				viewGunnerInExternal = 1;
				gunnerForceOptics = 0;
				weapons[] = {RHS_M2_HMG};
				soundServo[] = {"A3\sounds_f\dummysound", "db-40", 1.0, 10};
				magazines[] = {"100Rnd_127x99_mag_Tracer_Yellow", "100Rnd_127x99_mag_Tracer_Yellow", "100Rnd_127x99_mag_Tracer_Yellow", "100Rnd_127x99_mag_Tracer_Yellow"};
				gunnerAction = "mas_LR_Gunner_EP1";
				ejectDeadGunner = 1;
				minElev = -25;
				maxElev = 60;
				stabilizedInAxes = "StabilizedInAxesNone";
			};
		};
		
		class Wheels {
			class LF {
				boneName = "wheel_1_1_damper";
				steering = 1;
				side = "left";
				center = "wheel_1_1_axis";
				boundary = "wheel_1_1_bound";
				width = 0.126;
				mass = 25;
				MOI = 12.8;
				dampingRate = 0.1;
				maxBrakeTorque = 10000;
				maxHandBrakeTorque = 0;
				suspTravelDirection[] = {0, -1, 0};
				suspForceAppPointOffset = "wheel_1_1_axis";
				tireForceAppPointOffset = "wheel_1_1_axis";
				maxCompression = 0.05;
				mMaxDroop = 0.1;
				sprungMass = 825;
				springStrength = 51625;
				springDamperRate = 8920;
				longitudinalStiffnessPerUnitGravity = 10000;
				latStiffX = 25;
				latStiffY = 180;
				frictionVsSlipGraph[] = {{0, 1}, {0.5, 1}, {1, 1}};
			};
			
			class LR : LF {
				boneName = "wheel_1_2_damper";
				steering = 0;
				center = "wheel_1_2_axis";
				boundary = "wheel_1_2_bound";
				suspForceAppPointOffset = "wheel_1_2_axis";
				tireForceAppPointOffset = "wheel_1_2_axis";
				maxHandBrakeTorque = 3500;
			};
			
			class RF : LF {
				boneName = "wheel_2_1_damper";
				center = "wheel_2_1_axis";
				boundary = "wheel_2_1_bound";
				suspForceAppPointOffset = "wheel_2_1_axis";
				tireForceAppPointOffset = "wheel_2_1_axis";
				steering = 1;
				side = "right";
			};
			
			class RR : RF {
				boneName = "wheel_2_2_damper";
				steering = 0;
				center = "wheel_2_2_axis";
				boundary = "wheel_2_2_bound";
				suspForceAppPointOffset = "wheel_2_2_axis";
				tireForceAppPointOffset = "wheel_2_2_axis";
				maxHandBrakeTorque = 3500;
			};
		};
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 3;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.33;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.38;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.38;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.38;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.38;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		
		class Reflectors {
			class Left {
				color[] = {1900, 1300, 950};
				ambient[] = {5, 5, 5};
				position = "L svetlo";
				direction = "konec L svetla";
				hitpoint = "L svetlo";
				selection = "L svetlo";
				size = 1;
				innerAngle = 100;
				outerAngle = 179;
				coneFadeCoef = 10;
				intensity = 1;
				useFlare = 0;
				dayLight = 0;
				flareSize = 1.0;
				
				class Attenuation {
					start = 1.0;
					constant = 0;
					linear = 0;
					quadratic = 0.25;
					hardLimitStart = 30;
					hardLimitEnd = 60;
				};
			};
			
			class Right : Left {
				position = "P svetlo";
				direction = "konec P svetla";
				hitpoint = "P svetlo";
				selection = "P svetlo";
			};
			
			class Right2 : Right {
				useFlare = 1;
				position = "P svetlo";
			};
			
			class Left2 : Left {
				useFlare = 1;
				position = "L svetlo";
			};
		};
		attenuationEffectType = "OpenCarAttenuation";
		soundGetIn[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\Offroad_01-int-openclose", "db-7", 1};
		soundGetOut[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\Offroad_01-int-openclose", "db-7", 1, 40};
		soundDammage[] = {"", 0.562341, 1};
		soundEngineOnInt[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_start", 0.316228, 1.0};
		soundEngineOnExt[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_start", 0.398107, 1.0, 200};
		soundEngineOffInt[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_stop", 0.316228, 1.0};
		soundEngineOffExt[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_stop", 0.398107, 1.0, 200};
		buildCrash0[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_01", 1.0, 1, 150};
		buildCrash1[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_02", 1.0, 1, 150};
		buildCrash2[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_03", 1.0, 1, 150};
		buildCrash3[] = {"A3\sounds_f\Vehicles\soft\noises\crash_building_04", 1.0, 1, 150};
		soundBuildingCrash[] = {"buildCrash0", 0.25, "buildCrash1", 0.25, "buildCrash2", 0.25, "buildCrash3", 0.25};
		WoodCrash0[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_01", 1.0, 1, 100};
		WoodCrash1[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_02", 1.0, 1, 100};
		WoodCrash2[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_03", 1.0, 1, 100};
		WoodCrash3[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_04", 1.0, 1, 100};
		WoodCrash4[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_05", 1.0, 1, 100};
		WoodCrash5[] = {"A3\sounds_f\Vehicles\soft\noises\crash_mix_wood_06", 1.0, 1, 100};
		soundWoodCrash[] = {"woodCrash0", 0.166, "woodCrash1", 0.166, "woodCrash2", 0.166, "woodCrash3", 0.166, "woodCrash4", 0.166, "woodCrash5", 0.166};
		ArmorCrash0[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_01", 1.0, 1, 200};
		ArmorCrash1[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_02", 1.0, 1, 200};
		ArmorCrash2[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_03", 1.0, 1, 200};
		ArmorCrash3[] = {"A3\sounds_f\Vehicles\soft\noises\crash_vehicle_04", 1.0, 1, 200};
		soundArmorCrash[] = {"ArmorCrash0", 0.25, "ArmorCrash1", 0.25, "ArmorCrash2", 0.25, "ArmorCrash3", 0.25};
		
		class Sounds {
			class Idle_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_idle", "db-10", 1, 100};
				frequency = "0.95 + ((rpm/ 3500) factor[(200/ 3500),(580/ 3500)])*0.15";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(200/ 3500),(350/ 3500)]) * ((rpm/ 3500) factor[(580/ 3500),(400/ 3500)]))";
			};
			
			class Engine {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm1", "db-10", 1, 200};
				frequency = "0.9 + ((rpm/ 3500) factor[(380/ 3500),(960/ 3500)])*0.2";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(380/ 3500),(580/ 3500)]) * ((rpm/ 3500) factor[(960/ 3500),(700/ 3500)]))";
			};
			
			class Engine1_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm2", "db-9", 1, 225};
				frequency = "0.9 + ((rpm/ 3500) factor[(700/ 3500),(1400/ 3500)])*0.2";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(700/ 3500),(970/ 3500)]) * ((rpm/ 3500) factor[(1400/ 3500),(1100/ 3500)]))";
			};
			
			class Engine2_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm3", "db-9", 1, 250};
				frequency = "0.9 + ((rpm/ 3500) factor[(1100/ 3500),(1860/ 3500)])*0.2";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(1100/ 3500),(1430/ 3500)]) * ((rpm/ 3500) factor[(1860/ 3500),(1570/ 3500)]))";
			};
			
			class Engine3_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm4", 0.398107, 1, 275};
				frequency = "0.95 + ((rpm/ 3500) factor[(1600/ 3500),(2200/ 3500)])*0.2";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(1600/ 3500),(1860/ 3500)]) * ((rpm/ 3500) factor[(2200/ 3500),(2050/ 3500)]))";
			};
			
			class Engine4_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm5", "db-7", 1, 300};
				frequency = "0.95 + ((rpm/ 3500) factor[(2040/ 3500),(2670/ 3500)]) *0.2";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(2040/ 3500),(2200/ 3500)]) * ((rpm/ 3500) factor[(2670/ 3500),(2400/ 3500)]))";
			};
			
			class Engine5_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm6", "db-6", 1, 300};
				frequency = "0.95 + ((rpm/ 3500) factor[(2400/ 3500),(3050/ 3500)])*0.2";
				volume = "engineOn*camPos*(((rpm/ 3500) factor[(2400/ 3500),(2660/ 3500)]) * ((rpm/ 3500) factor[(3050/ 3500),(2800/ 3500)]))";
			};
			
			class Engine6_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_ext_rpm7", 0.562341, 1, 300};
				frequency = "0.95 + ((rpm/ 3500) factor[(2700/ 3500),(3500/ 3500)])*0.2";
				volume = "engineOn*camPos*((rpm/ 3500) factor[(2700/ 3500),(3200/ 3500)])";
			};
			
			class IdleThrust {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_idle", "db-6", 1, 200};
				frequency = "0.95 + ((rpm/ 3500) factor[(200/ 3500),(580/ 3500)])*0.15";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(200/ 3500),(350/ 3500)]) * ((rpm/ 3500) factor[(580/ 3500),(400/ 3500)]))";
			};
			
			class EngineThrust {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm1", 0.562341, 1, 250};
				frequency = "0.9 + ((rpm/ 3500) factor[(380/ 3500),(960/ 3500)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(380/ 3500),(580/ 3500)]) * ((rpm/ 3500) factor[(960/ 3500),(700/ 3500)]))";
			};
			
			class Engine1_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm2", 0.630957, 1, 275};
				frequency = "0.9 + ((rpm/ 3500) factor[(700/ 3500),(1400/ 3500)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(700/ 3500),(970/ 3500)]) * ((rpm/ 3500) factor[(1400/ 3500),(1100/ 3500)]))";
			};
			
			class Engine2_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm3", "db-3", 1, 300};
				frequency = "0.9 + ((rpm/ 3500) factor[(1100/ 3500),(1860/ 3500)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(1100/ 3500),(1430/ 3500)]) * ((rpm/ 3500) factor[(1860/ 3500),(1570/ 3500)]))";
			};
			
			class Engine3_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm4", "db-2", 1, 325};
				frequency = "0.95 + ((rpm/ 3500) factor[(1600/ 3500),(2200/ 3500)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(1600/ 3500),(1860/ 3500)]) * ((rpm/ 3500) factor[(2200/ 3500),(2050/ 3500)]))";
			};
			
			class Engine4_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm5", "db-1", 1, 350};
				frequency = "0.95 + ((rpm/ 3500) factor[(2040/ 3500),(2670/ 3500)]) *0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(2040/ 3500),(2200/ 3500)]) * ((rpm/ 3500) factor[(2670/ 3500),(2400/ 3500)]))";
			};
			
			class Engine5_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm6", "db0", 1, 375};
				frequency = "0.95 + ((rpm/ 3500) factor[(2400/ 3500),(3050/ 3500)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(2400/ 3500),(2660/ 3500)]) * ((rpm/ 3500) factor[(3050/ 3500),(2800/ 3500)]))";
			};
			
			class Engine6_Thrust_ext {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_ext_rpm7", "db1", 1, 400};
				frequency = "0.95 + ((rpm/ 3500) factor[(2700/ 3500),(3500/ 3500)])*0.2";
				volume = "engineOn*camPos*(0.4+(0.6*(thrust factor[0.1,1])))*((rpm/ 3500) factor[(2700/ 3500),(3200/ 3500)])";
			};
			
			class Idle_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_idle", "db-13", 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(200/ 3500),(580/ 3500)])*0.15";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(200/ 3500),(350/ 3500)]) * ((rpm/ 3500) factor[(580/ 3500),(400/ 3500)]))";
			};
			
			class Engine_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm1", "db-12", 1};
				frequency = "0.9 + ((rpm/ 3500) factor[(380/ 3500),(960/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(380/ 3500),(580/ 3500)]) * ((rpm/ 3500) factor[(960/ 3500),(700/ 3500)]))";
			};
			
			class Engine1_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm2", "db-15", 1};
				frequency = "0.9 + ((rpm/ 3500) factor[(700/ 3500),(1400/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(700/ 3500),(970/ 3500)]) * ((rpm/ 3500) factor[(1400/ 3500),(1100/ 3500)]))";
			};
			
			class Engine2_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm3", "db-10", 1};
				frequency = "0.9 + ((rpm/ 3500) factor[(1100/ 3500),(1860/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(1100/ 3500),(1430/ 3500)]) * ((rpm/ 3500) factor[(1860/ 3500),(1570/ 3500)]))";
			};
			
			class Engine3_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm4", "db-9", 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(1600/ 3500),(2200/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(1600/ 3500),(1860/ 3500)]) * ((rpm/ 3500) factor[(2200/ 3500),(2050/ 3500)]))";
			};
			
			class Engine4_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm5", 0.398107, 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(2040/ 3500),(2670/ 3500)]) *0.2";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(2040/ 3500),(2200/ 3500)]) * ((rpm/ 3500) factor[(2670/ 3500),(2400/ 3500)]))";
			};
			
			class Engine5_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm6", 0.398107, 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(2400/ 3500),(3050/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(((rpm/ 3500) factor[(2400/ 3500),(2660/ 3500)]) * ((rpm/ 3500) factor[(3050/ 3500),(2800/ 3500)]))";
			};
			
			class Engine6_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\engine_int_rpm7", "db-7", 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(2700/ 3500),(3500/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*((rpm/ 3500) factor[(2700/ 3500),(3200/ 3500)])";
			};
			
			class IdleThrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_idle", "db-10", 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(200/ 3500),(580/ 3500)])*0.15";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(200/ 3500),(350/ 3500)]) * ((rpm/ 3500) factor[(580/ 3500),(400/ 3500)]))";
			};
			
			class EngineThrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm1", "db-9", 1};
				frequency = "0.9 + ((rpm/ 3500) factor[(380/ 3500),(960/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(380/ 3500),(580/ 3500)]) * ((rpm/ 3500) factor[(960/ 3500),(700/ 3500)]))";
			};
			
			class Engine1_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm2", 0.398107, 1};
				frequency = "0.9 + ((rpm/ 3500) factor[(700/ 3500),(1400/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(700/ 3500),(970/ 3500)]) * ((rpm/ 3500) factor[(1400/ 3500),(1100/ 3500)]))";
			};
			
			class Engine2_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm3", "db-7", 1};
				frequency = "0.9 + ((rpm/ 3500) factor[(1100/ 3500),(1860/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(1100/ 3500),(1430/ 3500)]) * ((rpm/ 3500) factor[(1860/ 3500),(1570/ 3500)]))";
			};
			
			class Engine3_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm4", "db-6", 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(1600/ 3500),(2200/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(1600/ 3500),(1860/ 3500)]) * ((rpm/ 3500) factor[(2200/ 3500),(2050/ 3500)]))";
			};
			
			class Engine4_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm5", 0.562341, 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(2040/ 3500),(2670/ 3500)]) *0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(2040/ 3500),(2200/ 3500)]) * ((rpm/ 3500) factor[(2670/ 3500),(2400/ 3500)]))";
			};
			
			class Engine5_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm6", 0.630957, 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(2400/ 3500),(3050/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*(((rpm/ 3500) factor[(2400/ 3500),(2660/ 3500)]) * ((rpm/ 3500) factor[(3050/ 3500),(2800/ 3500)]))";
			};
			
			class Engine6_Thrust_int {
				sound[] = {"A3\Sounds_F\vehicles\soft\Offroad_01\exhaust_int_rpm7", "db-3", 1};
				frequency = "0.95 + ((rpm/ 3500) factor[(2700/ 3500),(3500/ 3500)])*0.2";
				volume = "engineOn*(1-camPos)*(0.4+(0.6*(thrust factor[0.1,1])))*((rpm/ 3500) factor[(2700/ 3500),(3200/ 3500)])";
			};
			
			class TiresRockOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_dirt_soft_1", "db-3", 1.0, 60};
				frequency = "1";
				volume = "camPos*rock*(speed factor[2, 20])";
			};
			
			class TiresSandOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext-tires-sand1", "db-3", 1.0, 60};
				frequency = "1";
				volume = "camPos*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_dirt_soft_2", "db-3", 1.0, 60};
				frequency = "1";
				volume = "camPos*grass*(speed factor[2, 20])";
			};
			
			class TiresMudOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext-tires-mud2", "db-3", 1.0, 60};
				frequency = "1";
				volume = "camPos*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_gravel_1", "db-3", 1.0, 60};
				frequency = "1";
				volume = "camPos*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\ext_tires_asfalt_2", "db-3", 1.0, 60};
				frequency = "1";
				volume = "camPos*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseOut {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\noise_ext_car_3", 0.562341, 1.0, 90};
				frequency = "1";
				volume = "camPos*(damper0 max 0.02)*(speed factor[0, 8])";
			};
			
			class TiresRockIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_dirt_soft_1", "db-3", 1.0};
				frequency = "1";
				volume = "(1-camPos)*rock*(speed factor[2, 20])";
			};
			
			class TiresSandIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int-tires-sand2", "db-3", 1.0};
				frequency = "1";
				volume = "(1-camPos)*sand*(speed factor[2, 20])";
			};
			
			class TiresGrassIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_dirt_soft_2", "db-3", 1.0};
				frequency = "1";
				volume = "(1-camPos)*grass*(speed factor[2, 20])";
			};
			
			class TiresMudIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int-tires-mud2", "db-3", 1.0};
				frequency = "1";
				volume = "(1-camPos)*mud*(speed factor[2, 20])";
			};
			
			class TiresGravelIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_gravel_1", "db-3", 1.0};
				frequency = "1";
				volume = "(1-camPos)*gravel*(speed factor[2, 20])";
			};
			
			class TiresAsphaltIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\tires\int_tires_asfalt_2", "db-3", 1.0};
				frequency = "1";
				volume = "(1-camPos)*asphalt*(speed factor[2, 20])";
			};
			
			class NoiseIn {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\noise_int_car_3", "db-16", 1.0};
				frequency = "1";
				volume = "(damper0 max 0.1)*(speed factor[0, 8])*(1-camPos)";
			};
			
			class breaking_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04", "db-3", 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
			
			class acceleration_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", "db-3", 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 2])";
			};
			
			class turn_left_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", "db-3", 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[2, 15])";
			};
			
			class turn_right_ext_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02", "db-3", 1, 80};
				frequency = 1;
				volume = "engineOn*camPos*asphalt*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[2, 15])";
			};
			
			class breaking_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_14_dirt_breaking", "db-3", 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class acceleration_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_16_dirt_acceleration", "db-3", 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 1])";
			};
			
			class turn_left_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt", "db-3", 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[1, 15])";
			};
			
			class turn_right_ext_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt", "db-3", 1, 60};
				frequency = 1;
				volume = "engineOn*camPos*(1-asphalt)*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class breaking_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_04_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class acceleration_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 1])";
			};
			
			class turn_left_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[1, 15])";
			};
			
			class turn_right_int_road {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_loop_02_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*asphalt*(1-camPos)*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class breaking_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_14_dirt_breaking_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(LongSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
			
			class acceleration_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_16_dirt_acceleration_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(LongSlipDrive Factor[0.1, 0.4])*(Speed Factor[15, 1])";
			};
			
			class turn_left_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(latSlipDrive Factor[0.1, 0.4])*(Speed Factor[1, 15])";
			};
			
			class turn_right_int_dirt {
				sound[] = {"A3\Sounds_F\vehicles\soft\noises\slipping_tires_18_dirt_int", "db-10", 1};
				frequency = 1;
				volume = "engineOn*(1-asphalt)*(1-camPos)*(latSlipDrive Factor[-0.1, -0.4])*(Speed Factor[1, 15])";
			};
		};
		
		class Damage {
			tex[] = {};
			mat[] = {"mas_cars\lr\Data\LR_base_baf.rvmat", "mas_cars\lr\Data\LR_base_baf_damage.rvmat", "mas_cars\lr\Data\LR_base_baf_destruct.rvmat", "mas_cars\lr\Data\LR_glass_baf.rvmat", "mas_cars\lr\Data\LR_glass_baf_damage.rvmat", "mas_cars\lr\Data\LR_glass_baf_destruct.rvmat", "mas_cars\lr\Data\LR_Special_baf.rvmat", "mas_cars\lr\Data\LR_Special_baf_damage.rvmat", "mas_cars\lr\Data\LR_Special_baf_destruct.rvmat"};
		};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_co.paa", "mas_cars\lr\data\lr_special_baf_co.paa"};
		supplyRadius = 5;
		maximumLoad = 10000;
		transportMaxWeapons = 20;
		transportMaxMagazines = 1000;
		transportMaxBackpacks = 30;
		
		class TransportMagazines {
			class _xx_30Rnd_65x39_caseless_mag {
				magazine = "30Rnd_65x39_caseless_mag";
				count = 12;
			};
			
			class _xx_30Rnd_65x39_caseless_mag_Tracer {
				magazine = "30Rnd_65x39_caseless_mag_Tracer";
				count = 6;
			};
			
			class _xx_100Rnd_65x39_caseless_mag {
				magazine = "100Rnd_65x39_caseless_mag";
				count = 4;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 4;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
			
			class _xx_Chemlight_green {
				magazine = "Chemlight_green";
				count = 8;
			};
			
			class _xx_B_IR_Grenade {
				magazine = "B_IR_Grenade";
				count = 8;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_MXC_F {
				weapon = "arifle_MXC_F";
				count = 2;
			};
			
			class _xx_launch_NLAW_F {
				weapon = "launch_NLAW_F";
				count = 1;
			};
		};
	};
	
	class B_mas_cars_LR_Unarmed : B_mas_cars_LR_BASE {
		_generalMacro = "B_mas_cars_LR_Unarmed";
		scope = 2;
		model = "mas_cars\lr\LR";
		displayname = "LR Arm. Unarmed";
		transportSoldier = 5;
		cargoProxyIndexes[] = {1, 2, 3, 4, 5};
		crew = "B_CTRG_soldier_engineer_exp_F";
		typicalCargo[] = {"B_CTRG_soldier_engineer_exp_F", "B_CTRG_soldier_engineer_exp_F", "B_CTRG_soldier_engineer_exp_F", "B_CTRG_soldier_engineer_exp_F", "B_CTRG_soldier_engineer_exp_F"};
		class CargoTurret;	// External class reference
		
		class Turrets : Turrets {
			class CargoTurret_01 : CargoTurret {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Rear Gunner Left";
				gunnerCompartments = "Compartment1";
				memoryPointsGetInGunner = "pos cargo2";
				memoryPointsGetInGunnerDir = "pos cargo dir2";
				proxyIndex = 6;
				maxElev = 12;
				minElev = -12;
				maxTurn = -30;
				minTurn = -105;
				isPersonTurret = 1;
				memoryPointGunnerOptics = "eye";
				
				class dynamicViewLimits {};
			};
			
			class CargoTurret_02 : CargoTurret_01 {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Rear Gunner Right";
				memoryPointsGetInGunner = "pos cargo";
				memoryPointsGetInGunnerDir = "pos cargo dir";
				proxyIndex = 7;
				maxTurn = 105;
				minTurn = 30;
				
				class dynamicViewLimits {};
			};
		};
		
		class RenderTargets {
			class LeftMirror {
				renderTarget = "rendertarget0";
				
				class CameraView1 {
					pointPosition = "PIP0_pos";
					pointDirection = "PIP0_dir";
					renderQuality = 2;
					renderVisionMode = 4;
					fov = 0.7;
				};
			};
			
			class RightMirror {
				renderTarget = "rendertarget1";
				
				class CameraView1 {
					pointPosition = "PIP1_pos";
					pointDirection = "PIP1_dir";
					renderQuality = 2;
					renderVisionMode = 4;
					fov = 0.7;
				};
			};
			
			class FrontCam {
				renderTarget = "rendertarget2";
				
				class CameraView1 {
					pointPosition = "PIP2_pos";
					pointDirection = "PIP2_dir";
					renderQuality = 2;
					renderVisionMode = 4;
					fov = 0.7;
				};
			};
		};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_co.paa", "mas_cars\lr\data\lr_special_baf_co.paa"};
	};
	
	class B_mas_cars_LR_Med : B_mas_cars_LR_Unarmed {
		_generalMacro = "B_mas_cars_LR_Med";
		displayName = "LR Arm. MEV";
		supplyRadius = 10;
		attendant = 1;
		threat[] = {0, 0, 0};
		crew = "B_CTRG_soldier_M_medic_F";
		typicalCargo[] = {"B_CTRG_soldier_M_medic_F", "B_CTRG_soldier_M_medic_F"};
		hiddenSelections[] = {"Camo1", "Camo2"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_cm.paa", "mas_cars\lr\data\lr_special_baf_co.paa"};
	};
	
	class B_mas_cars_LR_M2 : B_mas_cars_LR_BASE {
		_generalMacro = "B_mas_cars_LR_M2";
		scope = 2;
		crew = "B_CTRG_soldier_GL_LAT_F";
		typicalCargo[] = {"B_CTRG_soldier_GL_LAT_F", "B_CTRG_soldier_GL_LAT_F"};
		model = "\mas_cars\lr\LR_M2";
		picture = "\mas_cars\lr\data\UI\picture_lr_mg_ca.paa";
		Icon = "\mas_cars\lr\data\UI\icon_lr_mg_ca.paa";
		displayname = "LR Arm. M2.50cal";
		transportSoldier = 0;
		class CargoTurret;	// External class reference
		
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				body = "mainTurret";
				gun = "mainGun";
				outGunnerMayFire = 1;
				forceHideGunner = 0;
				castGunnerShadow = 1;
				viewGunnerInExternal = 1;
				turretInfoType = "RscOptics_Offroad_01";
				discreteDistance[] = {100, 200, 300, 400, 500, 600, 800, 1000, 1200, 1500};
				discreteDistanceInitIndex = 2;
				gunnerForceOptics = 0;
				weapons[] = {"RHS_M2_HMG"};
				soundServo[] = {"A3\sounds_f\dummysound", "db-40", 1.0, 10};
				magazines[] = {};
				gunnerAction = "mas_HMMWV_Gunner03lr";
				gunnerInAction = "mas_HMMWV_Gunner03lr";
				gunnerRightHandAnimName = "OtocHlaven_shake";
				gunnerLeftHandAnimName = "OtocHlaven_shake";
				ejectDeadGunner = 1;
				minElev = -25;
				maxElev = 60;
				stabilizedInAxes = "StabilizedInAxesNone";
				
				class ViewOptics : ViewOptics {
					initFov = 0.8;
					minFov = 0.25;
					maxFov = 1.1;
				};
				
				class ViewGunner : ViewOptics {};
			};
			
			class CargoTurret_01 : CargoTurret {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Front Gunner";
				gunnerCompartments = "Compartment1";
				memoryPointsGetInGunner = "pos codriver";
				memoryPointsGetInGunnerDir = "pos codriver dir";
				proxyIndex = 1;
				maxElev = 35;
				minElev = -10;
				maxTurn = 70;
				minTurn = -105;
				isPersonTurret = 1;
				memoryPointGunnerOptics = "eye";
				
				class dynamicViewLimits {};
			};
			
			class CargoTurret_02 : CargoTurret_01 {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Rear Gunner";
				memoryPointsGetInGunner = "pos cargo";
				memoryPointsGetInGunnerDir = "pos cargo dir";
				proxyIndex = 2;
				maxTurn = 15;
				minTurn = -105;
				isPersonTurret = 1;
				
				class dynamicViewLimits {};
			};
		};
		
		class AnimationSources : AnimationSources {
			class ReloadAnim {
				source = "reload";
				weapon = HMG_M2;
			};
			
			class ReloadMagazine {
				source = "reloadmagazine";
				weapon = HMG_M2;
			};
			
			class Revolving {
				source = "revolving";
				weapon = HMG_M2;
			};
		};
		hiddenSelections[] = {"Camo1"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_co.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {"mas_cars\lr\Data\LR_base_baf.rvmat", "mas_cars\lr\Data\LR_base_baf_damage.rvmat", "mas_cars\lr\Data\LR_base_baf_destruct.rvmat", "mas_cars\lr\Data\LR_glass_baf.rvmat", "mas_cars\lr\Data\LR_glass_baf_damage.rvmat", "mas_cars\lr\Data\LR_glass_baf_destruct.rvmat", "mas_cars\lr\data\LR_MG-SPG9.rvmat", "mas_cars\lr\data\LR_MG-SPG9_damage.rvmat", "mas_cars\lr\data\LR_MG-SPG9_destruct.rvmat"};
		};
	};
	
	class B_mas_cars_LR_Mk19 : B_mas_cars_LR_M2 {
		_generalMacro = "B_mas_cars_LR_Mk19";
		model = "\mas_cars\lr\LR_granade";
		picture = "\mas_cars\lr\data\UI\picture_lr_mg_ca.paa";
		Icon = "\mas_cars\lr\data\UI\icon_lr_mg_ca.paa";
		displayname = "LR Arm. Mk19";
		crew = "B_CTRG_soldier_AR_A_F";
		typicalCargo[] = {"B_CTRG_soldier_AR_A_F", "B_CTRG_soldier_AR_A_F"};
		transportSoldier = 0;
		class CargoTurret;	// External class reference
		
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				body = "mainTurret";
				gun = "mainGun";
				outGunnerMayFire = 1;
				forceHideGunner = 0;
				castGunnerShadow = 1;
				viewGunnerInExternal = 1;
				turretInfoType = "RscOptics_Offroad_01";
				discreteDistance[] = {100, 200, 300, 400, 500, 600, 800, 1000, 1200, 1500};
				discreteDistanceInitIndex = 2;
				gunnerForceOptics = 0;
				weapons[] = {"RHS_MK19_HMG"};
				magazines[] = {};
				soundServo[] = {"A3\sounds_f\dummysound", "db-40", 1.0, 10};
				gunnerAction = "mas_HMMWV_Gunner03lr";
				gunnerInAction = "mas_HMMWV_Gunner03lr";
				gunnerRightHandAnimName = "otochlaven";
				gunnerLeftHandAnimName = "otochlaven";
				ejectDeadGunner = 1;
				minElev = -25;
				maxElev = 60;
				stabilizedInAxes = "StabilizedInAxesNone";
				
				class ViewOptics : ViewOptics {
					initFov = 0.8;
					minFov = 0.25;
					maxFov = 1.1;
				};
				
				class ViewGunner : ViewOptics {};
			};
			
			class CargoTurret_01 : CargoTurret {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Front Gunner";
				gunnerCompartments = "Compartment1";
				memoryPointsGetInGunner = "pos codriver";
				memoryPointsGetInGunnerDir = "pos codriver dir";
				proxyIndex = 1;
				maxElev = 35;
				minElev = -10;
				maxTurn = 70;
				minTurn = -105;
				isPersonTurret = 1;
				memoryPointGunnerOptics = "eye";
				
				class dynamicViewLimits {};
			};
			
			class CargoTurret_02 : CargoTurret_01 {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Rear Gunner";
				memoryPointsGetInGunner = "pos cargo";
				memoryPointsGetInGunnerDir = "pos cargo dir";
				proxyIndex = 2;
				maxTurn = 15;
				minTurn = -105;
				isPersonTurret = 1;
				
				class dynamicViewLimits {};
			};
		};
		
		class AnimationSources : AnimationSources {
			class ReloadAnim {
				source = "reload";
				weapon = "mas_AGS40";
			};
			
			class ReloadMagazine {
				source = "reloadmagazine";
				weapon = "mas_AGS40";
			};
			
			class Revolving {
				source = "revolving";
				weapon = "mas_AGS40";
			};
		};
		hiddenSelections[] = {"Camo1"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_co.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {"mas_cars\lr\Data\LR_base_baf.rvmat", "mas_cars\lr\Data\LR_base_baf_damage.rvmat", "mas_cars\lr\Data\LR_base_baf_destruct.rvmat", "mas_cars\lr\Data\LR_glass_baf.rvmat", "mas_cars\lr\Data\LR_glass_baf_damage.rvmat", "mas_cars\lr\Data\LR_glass_baf_destruct.rvmat", "mas_cars\lr\data\LR_MG-SPG9.rvmat", "mas_cars\lr\data\LR_MG-SPG9_damage.rvmat", "mas_cars\lr\data\LR_MG-SPG9_destruct.rvmat"};
		};
	};
	
	class B_mas_cars_LR_TOW : B_mas_cars_LR_M2 {
		_generalMacro = "B_mas_cars_LR_TOW";
		scope = 2;
		model = "\mas_cars\lr\LR_TOW";
		picture = "\mas_cars\lr\data\UI\picture_lr_spg9_ca.paa";
		Icon = "\mas_cars\lr\data\UI\icon_lr_spg9_ca.paa";
		displayname = "LR Arm. TOW";
		crew = "B_CTRG_soldier_engineer_exp_F";
		typicalCargo[] = {"B_CTRG_soldier_engineer_exp_F", "B_CTRG_soldier_engineer_exp_F"};
		transportSoldier = 0;
		class CargoTurret;	// External class reference
		
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				body = "mainTurret";
				gun = "mainGun";
				outGunnerMayFire = 1;
				forceHideGunner = 0;
				castGunnerShadow = 1;
				viewGunnerInExternal = 1;
				turretInfoType = "RscOptics_Offroad_01";
				discreteDistance[] = {100, 200, 300, 400, 500, 600, 800, 1000, 1200, 1500};
				discreteDistanceInitIndex = 2;
				gunnerForceOptics = 0;
				weapons[] = {"Rhs_weap_TOW_Launcher_static"};
				magazines[] = {};
				soundServo[] = {"A3\sounds_f\dummysound", "db-40", 1.0, 10};
				gunnerAction = "mas_HMMWV_Gunner03lr";
				ejectDeadGunner = 1;
				minElev = -25;
				maxElev = 60;
				stabilizedInAxes = "StabilizedInAxesNone";
				
				class ViewGunner {
					initAngleX = 5;
					minAngleX = -30;
					maxAngleX = 30;
					initAngleY = 0;
					minAngleY = -100;
					maxAngleY = 100;
					initFov = 0.7;
					minFov = 0.25;
					maxFov = 1.1;
				};
				
				class ViewOptics {
					initAngleX = 0;
					minAngleX = -30;
					maxAngleX = 30;
					initAngleY = 0;
					minAngleY = -100;
					maxAngleY = 100;
					initFov = 0.2;
					minFov = 0.025;
					maxFov = 0.2;
					visionMode[] = {"Normal", "Ti"};
					thermalMode[] = {0, 1};
				};
				gunnerOpticsModel = "\mas_vehicle\TOW\TOW_TI";
			};
			
			class CargoTurret_01 : CargoTurret {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Front Gunner";
				gunnerCompartments = "Compartment1";
				memoryPointsGetInGunner = "pos codriver";
				memoryPointsGetInGunnerDir = "pos codriver dir";
				proxyIndex = 1;
				maxElev = 35;
				minElev = -10;
				maxTurn = 70;
				minTurn = -105;
				isPersonTurret = 1;
				memoryPointGunnerOptics = "eye";
				
				class dynamicViewLimits {};
			};
			
			class CargoTurret_02 : CargoTurret_01 {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Rear Gunner";
				memoryPointsGetInGunner = "pos cargo";
				memoryPointsGetInGunnerDir = "pos cargo dir";
				proxyIndex = 2;
				maxTurn = 15;
				minTurn = -105;
				isPersonTurret = 1;
				
				class dynamicViewLimits {};
			};
		};
		
		class AnimationSources : AnimationSources {};
		hiddenSelections[] = {"Camo1"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_co.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {"mas_cars\lr\Data\LR_base_baf.rvmat", "mas_cars\lr\Data\LR_base_baf_damage.rvmat", "mas_cars\lr\Data\LR_base_baf_destruct.rvmat", "mas_cars\lr\Data\LR_glass_baf.rvmat", "mas_cars\lr\Data\LR_glass_baf_damage.rvmat", "mas_cars\lr\Data\LR_glass_baf_destruct.rvmat", "mas_cars\lr\data\LR_MG-SPG9.rvmat", "mas_cars\lr\data\LR_MG-SPG9_damage.rvmat", "mas_cars\lr\data\LR_MG-SPG9_destruct.rvmat"};
		};
	};
	
	class B_mas_cars_LR_SPG9 : B_mas_cars_LR_TOW {
		_generalMacro = "B_mas_cars_LR_SPG9";
		model = "\mas_cars\lr\LR_SPG9";
		picture = "\mas_cars\lr\data\UI\picture_lr_spg9_ca.paa";
		Icon = "\mas_cars\lr\data\UI\icon_lr_spg9_ca.paa";
		displayname = "LR Arm. SPG9";
		crew = "B_CTRG_soldier_engineer_exp_F";
		typicalCargo[] = {"B_CTRG_soldier_engineer_exp_F", "B_CTRG_soldier_engineer_exp_F"};
		transportSoldier = 0;
		class CargoTurret;	// External class reference
		
		class Turrets : Turrets {
			class MainTurret : MainTurret {
				gunnerForceOptics = 0;
				gunnerOutOpticsShowCursor = 0;
				weapons[] = {"RDS_SPG9"};
				soundServo[] = {"A3\sounds_f\dummysound", "db-40", 1.0, 10};
				magazines[] = {};
				gunnerAction = "mas_LR_gunner03_EP1";
				gunnerInAction = "mas_LR_gunner03_EP1";
				ejectDeadGunner = 1;
				gunnerOpticsModel = "\mas_cars\UAZ\2Dscope_SPG_4";
				
				class ViewOptics : ViewOptics {
					initFov = 0.8;
					minFov = 0.25;
					maxFov = 1.1;
				};
				
				class ViewGunner : ViewOptics {};
			};
			
			class CargoTurret_01 : CargoTurret {
				gunnerAction = "passenger_inside_3";
				gunnerName = "Front Gunner";
				gunnerCompartments = "Compartment1";
				memoryPointsGetInGunner = "pos codriver";
				memoryPointsGetInGunnerDir = "pos codriver dir";
				proxyIndex = 1;
				maxElev = 35;
				minElev = -10;
				maxTurn = 70;
				minTurn = -105;
				isPersonTurret = 1;
				memoryPointGunnerOptics = "eye";
				
				class dynamicViewLimits {};
			};
		};
		
		class AnimationSources : AnimationSources {};
		hiddenSelections[] = {"Camo1"};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_w_baf_co.paa"};
		
		class Damage {
			tex[] = {};
			mat[] = {"mas_cars\lr\Data\LR_base_baf.rvmat", "mas_cars\lr\Data\LR_base_baf_damage.rvmat", "mas_cars\lr\Data\LR_base_baf_destruct.rvmat", "mas_cars\lr\Data\LR_glass_baf.rvmat", "mas_cars\lr\Data\LR_glass_baf_damage.rvmat", "mas_cars\lr\Data\LR_glass_baf_destruct.rvmat", "mas_cars\lr\data\LR_MG-SPG9.rvmat", "mas_cars\lr\data\LR_MG-SPG9_damage.rvmat", "mas_cars\lr\data\LR_MG-SPG9_destruct.rvmat"};
		};
	};
	
	class I_mas_cars_LR_soft_Unarmed : B_mas_cars_LR_Unarmed {
		_generalMacro = "I_mas_cars_LR_soft_Unarmed";
		side = 2;
		faction = IND_F;
		vehicleClass = "mas_ind_veh";
		crew = "I_Soldier_F";
		typicalCargo[] = {"I_Soldier_F", "I_Soldier_F", "I_Soldier_F", "I_Soldier_F", "I_Soldier_F"};
		displayname = "LR Unarmed";
		model = "mas_cars\lr\LR_soft";
		armor = 70;
		damageResistance = 0.00562;
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 2;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				explosionShielding = 0.5;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_baf_co.paa", "mas_cars\lr\data\lr_special_baf_co.paa"};
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 8;
			};
			
			class _xx_200Rnd_65x39_cased_Box {
				magazine = "200Rnd_65x39_cased_Box";
				count = 3;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 2;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_Mk20_F {
				weapon = "arifle_Mk20_F";
				count = 2;
			};
		};
	};
	
	class I_mas_cars_LR_soft_Med : B_mas_cars_LR_Med {
		_generalMacro = "I_mas_cars_LR_soft_Med";
		side = 2;
		faction = IND_F;
		vehicleClass = "mas_ind_veh";
		crew = "I_Medic_F";
		typicalCargo[] = {"I_Medic_F", "I_Medic_F"};
		displayName = "LR MEV";
		model = "mas_cars\lr\LR_soft";
		armor = 70;
		damageResistance = 0.00562;
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 2;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				explosionShielding = 0.5;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_baf_cm.paa", "mas_cars\lr\data\lr_special_baf_co.paa"};
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 8;
			};
			
			class _xx_200Rnd_65x39_cased_Box {
				magazine = "200Rnd_65x39_cased_Box";
				count = 3;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 2;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_Mk20_F {
				weapon = "arifle_Mk20_F";
				count = 2;
			};
		};
	};
	
	class I_mas_cars_LR_soft_M2 : B_mas_cars_LR_M2 {
		_generalMacro = "I_mas_cars_LR_soft_M2";
		side = 2;
		faction = IND_F;
		vehicleClass = "mas_ind_veh";
		crew = "I_Soldier_F";
		typicalCargo[] = {"I_Soldier_F", "I_Soldier_F"};
		displayname = "LR M2.50cal";
		model = "mas_cars\lr\LR_soft_M2";
		armor = 70;
		damageResistance = 0.00562;
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 2;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				explosionShielding = 0.5;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_baf_co.paa"};
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 8;
			};
			
			class _xx_200Rnd_65x39_cased_Box {
				magazine = "200Rnd_65x39_cased_Box";
				count = 3;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 2;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_Mk20_F {
				weapon = "arifle_Mk20_F";
				count = 2;
			};
		};
	};
	
	class I_mas_cars_LR_soft_Mk19 : B_mas_cars_LR_Mk19 {
		_generalMacro = "I_mas_cars_LR_soft_Mk19";
		side = 2;
		faction = IND_F;
		vehicleClass = "mas_ind_veh";
		crew = "I_Soldier_F";
		typicalCargo[] = {"I_Soldier_F", "I_Soldier_F"};
		displayname = "LR Mk19";
		model = "mas_cars\lr\LR_soft_granade";
		armor = 70;
		damageResistance = 0.00562;
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 2;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				explosionShielding = 0.5;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_baf_co.paa"};
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 8;
			};
			
			class _xx_200Rnd_65x39_cased_Box {
				magazine = "200Rnd_65x39_cased_Box";
				count = 3;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 2;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_Mk20_F {
				weapon = "arifle_Mk20_F";
				count = 2;
			};
		};
	};
	
	class I_mas_cars_LR_soft_TOW : B_mas_cars_LR_TOW {
		_generalMacro = "I_mas_cars_LR_soft_TOW";
		side = 2;
		faction = IND_F;
		vehicleClass = "mas_ind_veh";
		crew = "I_Soldier_F";
		typicalCargo[] = {"I_Soldier_F", "I_Soldier_F"};
		displayname = "LR TOW";
		model = "mas_cars\lr\LR_soft_TOW";
		armor = 70;
		damageResistance = 0.00562;
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 2;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				explosionShielding = 0.5;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_baf_co.paa"};
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 8;
			};
			
			class _xx_200Rnd_65x39_cased_Box {
				magazine = "200Rnd_65x39_cased_Box";
				count = 3;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 2;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_Mk20_F {
				weapon = "arifle_Mk20_F";
				count = 2;
			};
		};
	};
	
	class I_mas_cars_LR_soft_SPG9 : B_mas_cars_LR_SPG9 {
		_generalMacro = "I_mas_cars_LR_soft_SPG9";
		side = 2;
		faction = IND_F;
		vehicleClass = "mas_ind_veh";
		crew = "I_Soldier_F";
		typicalCargo[] = {"I_Soldier_F", "I_Soldier_F"};
		displayname = "LR SPG9";
		model = "mas_cars\lr\LR_soft_SPG9";
		armor = 70;
		damageResistance = 0.00562;
		
		class HitPoints : HitPoints {
			class HitGlass1 : HitGlass1 {
				armor = 0.1;
				explosionShielding = 2;
				radius = 0.25;
			};
			
			class HitFuel {
				armor = 0.5;
				material = -1;
				name = "palivo";
				visual = "";
				passThrough = 1;
			};
			
			class HitEngine {
				armor = 0.5;
				material = -1;
				name = "motor";
				visual = "";
				passThrough = 0;
				minimalHit = 0.2;
				explosionShielding = 0.2;
				radius = 0.45;
			};
			
			class HitBody {
				armor = 0.8;
				material = -1;
				name = "karoserie";
				visual = "";
				passThrough = 1;
				explosionShielding = 0.5;
			};
			
			class HitLFWheel : HitLFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitLBWheel : HitLF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRFWheel : HitRFWheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
			
			class HitRBWheel : HitRF2Wheel {
				armor = 0.2;
				explosionShielding = 1;
				radius = 0.25;
			};
		};
		hiddenSelectionsTextures[] = {"mas_cars\lr\data\lr_base_baf_co.paa"};
		
		class TransportMagazines {
			class _xx_30Rnd_556x45_Stanag {
				magazine = "30Rnd_556x45_Stanag";
				count = 8;
			};
			
			class _xx_200Rnd_65x39_cased_Box {
				magazine = "200Rnd_65x39_cased_Box";
				count = 3;
			};
			
			class _xx_HandGrenade {
				magazine = "HandGrenade";
				count = 10;
			};
			
			class _xx_1Rnd_HE_Grenade_shell {
				magazine = "1Rnd_HE_Grenade_shell";
				count = 6;
			};
			
			class _xx_1Rnd_Smoke_Grenade_shell {
				magazine = "1Rnd_Smoke_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeGreen_Grenade_shell {
				magazine = "1Rnd_SmokeGreen_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokeOrange_Grenade_shell {
				magazine = "1Rnd_SmokeOrange_Grenade_shell";
				count = 3;
			};
			
			class _xx_1Rnd_SmokePurple_Grenade_shell {
				magazine = "1Rnd_SmokePurple_Grenade_shell";
				count = 3;
			};
			
			class _xx_SmokeShell {
				magazine = "SmokeShell";
				count = 8;
			};
			
			class _xx_SmokeShellGreen {
				magazine = "SmokeShellGreen";
				count = 8;
			};
			
			class _xx_SmokeShellOrange {
				magazine = "SmokeShellOrange";
				count = 8;
			};
			
			class _xx_SmokeShellPurple {
				magazine = "SmokeShellPurple";
				count = 8;
			};
			
			class _xx_NLAW_F {
				magazine = NLAW_F;
				count = 5;
			};
			
			class _xx_Titan_AT {
				magazine = "Titan_AT";
				count = 2;
			};
			
			class _xx_Titan_AP {
				magazine = "Titan_AP";
				count = 2;
			};
			
			class _xx_Titan_AA {
				magazine = "Titan_AA";
				count = 2;
			};
			
			class _xx_DemoCharge_Remote_Mag {
				magazine = "DemoCharge_Remote_Mag";
				count = 2;
			};
			
			class _xx_Laserbatteries {
				magazine = "Laserbatteries";
				count = 4;
			};
		};
		
		class TransportItems {
			class _xx_FirstAidKit {
				name = "FirstAidKit";
				count = 10;
			};
			
			class _xx_medikit {
				name = "medikit";
				count = 1;
			};
			
			class _xx_ToolKit {
				name = "ToolKit";
				count = 1;
			};
			
			class _xx_MineDetector {
				name = "MineDetector";
				count = 1;
			};
			
			class _xx_LaserDesignator {
				name = "LaserDesignator";
				count = 1;
			};
		};
		
		class TransportBackpacks {
			class _xx_B_TacticalPack_oli {
				backpack = "B_TacticalPack_oli";
				count = 2;
			};
			
			class _xx_B_Bergen_sgg {
				backpack = "B_Bergen_sgg";
				count = 2;
			};
		};
		
		class TransportWeapons {
			class _xx_arifle_Mk20_F {
				weapon = "arifle_Mk20_F";
				count = 2;
			};
		};
	};
};
